### ISSUE TITLE
Allow to change the default installation path 

### ISSUE THREAD

**Issue by SaurabhSM** [leoafarias/fvm#101]
Currently when I install any flutter version it installs flutter on default path. However, It would be great if FVM allows to set custom location as installation path.

**Comment by leoafarias** [comment]
@SaurabhSM can you elaborate a bit more about what you mean? Fvm does allow to set a custom path where it will cache all the flutter versions.

**Comment by SaurabhSM** [comment]
So currently, i have to add variable FVM_HOME to my environment variables. However, there are situations where i've to use organization's computer where i dont have permission to set environment variables to that system. 

So if FVM has way to change the location of the installation directory from command line, that would be really helpful.

**Comment by leoafarias** [comment]
Interesting we had this feature before end I removed it because of the env var. Will look into this.

**Comment by leoafarias** [comment]
This has been updated on prerelease.  https://pub.dev/packages/fvm/versions/1.3.0-dev.0
`pub global activate fvm 1.3.0-dev.0`

**Comment by kopianan** [comment]
> FVM_HOME

How to do this ?
