### ISSUE TITLE
[Feature Request] Use different Flutter SDK versions per branch in a git repository

### ISSUE THREAD

**Issue by simonpham** [leoafarias/fvm#105]
> You can use different Flutter SDK versions per project

This is good. But it is really helpful if you can add an ability to use different Flutter SDK versions per **branch** in a git repository.

I have been working on different branches with different flutter version and it's really inconvenient to switch between flutter versions every time after I checkout to another branch.

Thank you so much!

**Comment by kuhnroyal** [comment]
This can easily be done, since you can commit the `.fvm/fvm_config.json` file to Git and just need to call `fvm use` on the new branch.
