### ISSUE TITLE
Linking issue with pub 1.9.0

### ISSUE THREAD

**Issue by jascodes** [leoafarias/fvm#116]
Hey @leoafarias 
Can you quickly try this on your machine?
I am getting stuck and hanged when I do the following. CPU start burning my laps... 😂
```
pub --version
Pub 2.9.1

hub clone https://github.com/leoafarias/fvm

pub global activate -s path . 
Precompiling executables... (47.5s)
Precompiled process_run:shell.
Precompiled process_run:shell.
Precompiled process_run:shell.
Precompiled process_run:shell.
Precompiled process_run:shell.
Precompiled test_coverage:test_coverage.
Precompiled test_coverage:test_coverage.
Precompiled test_coverage:test_coverage.
Precompiled test_coverage:test_coverage.
Precompiled test_coverage:test_coverage.
^C
```

**Comment by leoafarias** [comment]
@jascodes I was able to replicate this issue once on your PR only ... is that happening on master also?

**Comment by jascodes** [comment]
@leoafarias As I remember it was but let me double check. Are you sure you didn't had old fvm linking with 2.8.x or before and now the issue is happening?

**Comment by jascodes** [comment]
@jascodes Yea not working on master as well... I had to use 2.8.x and it works for me.

**Comment by leoafarias** [comment]
ok I will go ahead and close here and we can open an issue on the dart repo

**Comment by jonasfj** [comment]
This is 2.9.x related, unless I'm reading incorrectly:
```
pub --version
Pub 2.9.1
```

**Comment by jascodes** [comment]
@jonasfj Yes
