### ISSUE TITLE
[BUG] fvm install does not download the complete sdk

### ISSUE THREAD

**Issue by PandaGeek1024** [leoafarias/fvm#117]
**Describe the bug**
fvm install doesn't set up evertying for me. I still have to run "fvm flutter run" to download the rest of the contents. btw, it would be nice to add the full steps in readme of how to setup the configures.

**To Reproduce**
1. run 'fvm use stable' in command
2. run 'fvm install' in command
3. change Android studio flutter sdk path to "/absolute/path-to-your-project/.fvm/flutter_sdk"
4. Android studio reports sdk is incomplete. I have to run 'fvm flutter run' to trigger the download.

**Desktop (please complete the following information):**
 - OS: Mac
 - FVM Version 0.8.2

**Additional context**

**Comment by leoafarias** [comment]
@PandaGeek1024 I will go ahead and close this issue. That enhancement will be added as part of a GUI project that I am working on
