### ISSUE TITLE
[BUG] hot reload not working when using fvm

### ISSUE THREAD

**Issue by KevinTheGray** [leoafarias/fvm#124]
**Describe the bug**
When I use fvm from the terminal, I am unable to hot reload or hot restart.  

**To Reproduce**
1. Run fvm from the terminal like: `fvm flutter run --flavor development -d 9288B215-C389-4B17-B00A-8C9303B53F4D`
2. Press r to hot reload
3. The letter r shows up in the terminal

**Expected behavior**
Pressing r should do a hot reload

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4 
 - FVM Version 1.2.3

**fvm flutter doctor -v**
```
fvm flutter doctor -v
[✓] Flutter (Channel unknown, 1.21.0-9.2.pre, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.21.0-9.2.pre at /Users/KG/fvm/versions/1.21.0-9.2.pre
    • Framework revision 81a45ec2e5 (3 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215
```

**Comment by leoafarias** [comment]
@KevinTheGray Once you you type `R` you can press enter to send the command. Will take a look how to improve this

**Comment by KevinTheGray** [comment]
I see, that works!  This solution works for me so I'll close this issue out.  Thanks.

**Comment by orestesgaolin** [comment]
I also noticed that when running from the command line. It's not a big issue, but it would be amazing to have some solution. @leoafarias do you have some ideas how to handle this? Maybe the fvm should enter the some kind of "interactive" mode when detecting `run`?

**Comment by leoafarias** [comment]
Version 1.3.0-dev-0 has these tweaks
`pub global activate fvm 1.3.0-dev.0` version still WIP
