### ISSUE TITLE
[BUG] fvm can't use after switch global

### ISSUE THREAD

**Issue by tbm98** [leoafarias/fvm#126]
**Describe the bug**
fvm crash after I switch to other version as global

**To Reproduce**
1. fvm use stable --global
2. fvm use beta --global
3. fvm ...  (fvm crash)

**Comment by leoafarias** [comment]
@tbm98 I need some more info. Can you tell me fvm version, operating system and also run the command with the --verbose flag in the end, and add the output here?

**Comment by tbm98** [comment]
1. fvm sersion: 1.2.3
2. macOS 10.15.6
3. 
<img width="652" alt="Screen Shot 2020-09-02 at 15 05 08" src="https://user-images.githubusercontent.com/52562340/91955649-b8534e80-ed2d-11ea-8024-592d52ec165e.png">

```
tbm98 at ~ 👉 fvm list
Versions path:  /Users/tbm98/fvm/versions
beta (global)
dev
stable
tbm98 at ~ 👉 fvm use stable --global
The global Flutter version is now stable
Make sure sure to add /Users/tbm98/fvm/default/bin to your PATH environment variable
tbm98 at ~ 👉 fvm
Can't load Kernel binary: Invalid kernel binary format version.
/Users/tbm98/.pub-cache/bin/fvm: line 15: pub: command not found
tbm98 at ~ 👉 fvm --verbose
Can't load Kernel binary: Invalid kernel binary format version.
/Users/tbm98/.pub-cache/bin/fvm: line 15: pub: command not found
tbm98 at ~ 👉
```

**Comment by leoafarias** [comment]
@tbm98 will improve this error message. 

One thing is the only time I have encountered this error message was when fvm was setup using 'flutter pub global activate fvm' instead of 'pub global activate fvm' was that the case?

**Comment by tbm98** [comment]
I have not setup dart sdk so i only can run with flutter

**Comment by leoafarias** [comment]
@tbm98 that is most likely the issue. I will take a look to see if there is a workaround, but would suggest setting it up with `pub global activate fvm`

**Comment by leoafarias** [comment]
@tbm98 https://dart.dev/get-dart

**Comment by tbm98** [comment]
Yep. I also think when i change flutter sdk, that broken fvm. I will try with dart sdk and feedback soon

**Comment by leoafarias** [comment]
@tbm98 this can be a bit confusing, but when you switch Flutter you are actually switching tooling around fvm... is like using `fvm` to change the version of what runs `fvm` ;) I am going to be doing some exploration on that front to see if there are some improvements

**Comment by tbm98** [comment]
Worked well after use dart sdk instead. Thanks!
