### ISSUE TITLE
fvm commands crash terminal window[BUG] 

### ISSUE THREAD

**Issue by tonydavidx** [leoafarias/fvm#128]
when i run fvm help or any other fvm commands the terminal window closes automatically. 

 - OS: [windows 10]
 - FVM Version [1.1.9]

**Comment by leoafarias** [comment]
@tonydavidx can you update to the latest version and make sure you are running as administrator

**Comment by tonydavidx** [comment]
new version also causes cmd to close, i tried running cmd as admin no changes

**Comment by leoafarias** [comment]
@tonydavidx could you run the command that is crashing with `--verbose`, and provide the output. Is looking like I will have to install windows on an extra mac I have. The windows CI, passes the tests, and the VM, I cannot replicate some of these errors.

**Comment by leoafarias** [comment]
@tonydavidx finally have a windows dev environment setup, and was not able to replicate the error. Will take a look further once I have the verbose.

Another question is if you are using the new powershell. I noticed that if you are you have to reinstall dart-sdk because of the paths.

**Comment by tonydavidx** [comment]
@leoafarias  the issue is not occurring when using PowerShell. previously i was using windows command prompt. 

thank you for you help.

**Comment by pdivita** [comment]
It crashes in Android Studio terminal (it uses classic Windows terminal (cmd)) but doesn't crash using PowerShell.
Tested on Windows 10 Pro (1909)

**Comment by leoafarias** [comment]
> It crashes in Android Studio terminal (it uses classic Windows terminal (cmd)) but doesn't crash using PowerShell.
> 
> Tested on Windows 10 Pro (1909)

@pdivita can you provide some logs? '--verbose'. Also this seems the exact opposite of the other error.

**Comment by pdivita** [comment]
I can't because terminal crashes and disappear

Scarica Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by leoafarias** [comment]
@pdivita I have not been able to replicate this.

**Comment by urusai88** [comment]
Same problem. If i try to use fvm in android studio terminal, terminal instant getting closed.

**Comment by leoafarias** [comment]
@urusai88 a few questions:
- Did you install fvm using `flutter pub..` or the suggested `pub` command?
- Where does the ENV var flutter points to?
- Does it crash when running any FVM command like `fvm version` or when running flutter through `fvm`?

**Comment by pdivita** [comment]
- I've installed with the `pub global activate fvm` command
- flutter.bat is `c:\dev\flutter\bin\`
- It crashes whenever I run fvm (with or without parameters)

Tried also specifying the path directly `(C:\Users\p.divita\AppData\Roaming\Pub\Cache\bin\fvm.bat)`

- works on PS (get 1.2.3 version)
- crashes on cmd

For the record, I've also a fvm.bat on my main installation flutter directory (`C:\dev\flutter\.pub-cache\bin`) but it doesn't work neither on cmd or PS. It gives me `Can't load Kernel binary: Invalid SDK hash.` error on both (no crash)

**Comment by urusai88** [comment]
> @urusai88 a few questions:
> Does it crash when running any FVM command like `fvm version` or when running flutter through `fvm`?
Yes, fvm crash cmd with only "fvm" command. Not event need something more, like "fvm version".
In PowerShell "fvm" works well

**Comment by leoafarias** [comment]
My guess it probably has something to do with pub itself which is what is responsible for the fvm path. 
Can you try to run `pub cache repair`, close the terminal, and reopen and try again?

**Comment by pdivita** [comment]
It can't compile both devtools and fvm (strangely they are the only 2 packages I've in `C:\dev\flutter\.pub-cache\bin` as "duplicates" of the ones I've in `C:\Users\p.divita\AppData\Roaming\Pub\Cache\bin\`):

`Reactivating devtools 0.1.13...
Precompiling executables...
Failed to precompile devtools:devtools:
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:97:8: Error: The method 'MultiHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:699:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:129:8: Error: The method 'MultiHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:708:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
Failed to reactivate devtools 0.1.13: Failed to precompile devtools:devtools:
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:97:8: Error: The method 'MultiHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:699:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:129:8: Error: The method 'MultiHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:708:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
Reactivating fvm 1.2.3...
Precompiling executables...
Failed to precompile fvm:main:
Error: Could not resolve the package 'fvm' in 'package:fvm/fvm.dart'.
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:1:8: Error: Not found: 'package:fvm/fvm.dart'
import 'package:fvm/fvm.dart';
       ^
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9: Error: Method not found: 'fvmRunner'.
  await fvmRunner(arguments);
        ^^^^^^^^^
Failed to reactivate fvm 1.2.3: Failed to precompile fvm:main:
Error: Could not resolve the package 'fvm' in 'package:fvm/fvm.dart'.
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:1:8: Error: Not found: 'package:fvm/fvm.dart'
import 'package:fvm/fvm.dart';
       ^
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9: Error: Method not found: 'fvmRunner'.
  await fvmRunner(arguments);
        ^^^^^^^^^
Binstubs exist for non-activated packages:
  From devtools: devtools
  From fvm: fvm
Failed to reactivate 2 packages:
- devtools
- fvm`

**Comment by leoafarias** [comment]
If possible please test the following prerelease version and report any issues
https://pub.dev/packages/fvm/versions/1.3.0-dev.0
`pub global activate fvm 1.3.0-dev.0`

**Comment by urusai88** [comment]
> If possible please test the following prerelease version and report any issues
> https://pub.dev/packages/fvm/versions/1.3.0-dev.0
> `pub global activate fvm 1.3.0-dev.0`

Issue still exists

**Comment by leoafarias** [comment]
@urusai88 I was able to replicate the issue I think. It happens when you do not have the dart-sdk installed at least for me. Could you do `pub --version`. If you install the dart-sdk I believe it should work fine.
https://dart.dev/get-dart#install

If that works for you, I will have to dig in. I am working on native compile for the CLI. Hopefully this takes care of this clunkyness on windows

**Comment by leoafarias** [comment]
closed in favor of #142

**Comment by dipakbari4** [comment]
> @leoafarias the issue is not occurring when using PowerShell. previously i was using windows command prompt.
> 
> thank you for you help.

Yeah, It's not crashing in PowerShell

**Comment by mohamad97-alhomsi** [comment]
> @tonydavidx could you run the command that is crashing with `--verbose`, and provide the output. Is looking like I will have to install windows on an extra mac I have. The windows CI, passes the tests, and the VM, I cannot replicate some of these errors.

i tried to run fvm with --verbose nothing changed it still crashing the cmd

**Comment by tonydavidx** [comment]
instead of CMD run fvm commands with powershell. i was able to run all
commands with powershell without crashing
