### ISSUE TITLE
[BUG] fvm flutter upgrade causes ProcessException: No such file or directory

### ISSUE THREAD

**Issue by zoechi** [leoafarias/fvm#129]
**Describe the bug**

⚠️  ProcessException: No such file or directory
  Command: /home/user/fvm/versions/bin/flutter upgrade

**Reproduction**

```sh
pub global activate fvm
fvm install dev
fvm install stable
# original report
# export PATH=$PATH:$HOME/fvm/versions/
# correction
export PATH=$PATH:$HOME/fvm/default/bin
dev/    stable/ 
fvm use dev --global
fvm use stable
fvm flutter upgrade
⚠️  ProcessException: No such file or directory
  Command: /home/user/fvm/versions/bin/flutter upgrade
la /home/user/fvm/versions/
dev/    stable/ 
```

**Desktop (please complete the following information):**
 - OS: `Linux Dev 4.19.132-1.pvops.qubes.x86_64 #1 SMP Tue Jul 14 03:42:21 UTC 2020 x86_64 GNU/Linux`
 - FVM Version: `1.2.3`

**Comment by leoafarias** [comment]
@zoechi Why are you doing a path export? Also can you give me the exact like that you are adding on that export, as the formatting seems confusing on here.

**Comment by leoafarias** [comment]
@zoechi I was only able to replicate this when fvm is not configured in the project. Can you check if the `.fvm` folder has been created within the project?

**Comment by zoechi** [comment]
Thanks a lot for checking. Yes, the `.fvm` folder is created.

> Why are you doing a path export?

AFAIR think `fvm` told me that I should.

I also just found in the README.md

> ** Do not activate fvm using flutter pub global activate** if you plan on using the --global flag.

which is exactly what I'm doing (see initial post).

Does `--global` even make sense without `pub global activate`?
I'm confused.

**Comment by leoafarias** [comment]
You should not use the `flutter pub` the reason why, because it caches the pub dependency as part of the flutter cache directory. It is like you are now moving around the cache which fvm is in. By using the `pub` without Flutter it means that fvm is cached outside of it, and that that is the best practice for non Flutter projects.

`pub global activate` only allows you to use `fvm` globally within the terminal. 
The `--global` flags allows you to set a default global flutter version.

Let me know if that makes more sense.

**Comment by zoechi** [comment]
I see. Yes, that makes sense. 
It is not about `global activate`, it's about `flutter`.
I'm not doing that.

**Comment by leoafarias** [comment]
@zoechi seems the issue based on your logs has to do with that path export you are doing. Is there a reason for that?

**Comment by zoechi** [comment]
It seems I made a mistake when I created the original post

Now I get
```
fvm use dev --global
The global Flutter version is now dev
Make sure sure to add /home/user/fvm/default/bin to your PATH environment variable
```
This is the path I actually added.
I removed this and now it seems the error is gone.

**Comment by leoafarias** [comment]
Great, I will be closing this. Let me know if you need anything else.

**Comment by zoechi** [comment]
Why does fvm suggest to add this path if doing it breaks it?

**Comment by leoafarias** [comment]
This sets a default redirect so you can use a global version. This does not break. However the example you provided seems different from the path. Also you should set that as a path variable and not just export on the terminal.

**Comment by zoechi** [comment]
Uh, I missed your reply.

What does this mean

> However the example you provided seems different from the path

even after I updated the initial post?

> Also you should set that as a path variable and not just export on the terminal.

I did that, but if I'm only reproducing in the same terminal window, `export` should be enough.
