### ISSUE TITLE
Can't Build & Run App through Android Studio

### ISSUE THREAD

**Issue by NiceboyWiseboy** [leoafarias/fvm#130]
Hello,

First of all, thanks for this great tool you have built.
I've successfully installed and configured fvm. The issue I'm facing is that I can't Build & Run App through Android Studio. But I can Build and Run App through Terminal. I followed the instructions for Android Studio given on official pub.dev documentation.

Thanks again,
Best Regards

**Comment by leoafarias** [comment]
@NiceboyWiseboy do you have any logs or information that gets displayed?

**Comment by NiceboyWiseboy** [comment]
Nope

**Comment by NiceboyWiseboy** [comment]
But now I'm facing another issue. I can't add support for building on macOS in existing project using fvm installed SDK.
I've followed the steps as described. Also the macOS shows in the Debug Devices in Android Studio.

Here's the image for the same:

![image](https://user-images.githubusercontent.com/40816700/92690922-66c74700-f35f-11ea-99d1-fbf91d3d1482.png)

**Comment by leoafarias** [comment]
Did you run the confit on flutter side? If so can you see a macOS folder within the project? Not sure if this is an fvm issue..
Make sure you are running the dev channel

**Comment by NiceboyWiseboy** [comment]
yes, I'm running the dev channel.

**Comment by NiceboyWiseboy** [comment]
I guess there was issue with the default Flutter SDK. Android Studio was somehow connecting to the default Flutter SDK even if I removed the path from bash file and path to the Flutter SDK in Android Studio. Removed that completely, and now fvm is working fine.

Thanks for your help and providing this great tool.

**Comment by leoafarias** [comment]
I think it needs an android studio restarts to make sure the changes are applied. I will go ahead and add this to the docs
