### ISSUE TITLE
[BUG] fvm flutter does'nt work

### ISSUE THREAD

**Issue by tbm98** [leoafarias/fvm#136]
<img width="651" alt="Screen Shot 2020-09-18 at 17 33 27" src="https://user-images.githubusercontent.com/52562340/93588259-581f0680-f9d5-11ea-9e09-8920f62b3c8e.png">

macOS 15.6
fvm version: 1.2.3

**Comment by vicenterusso** [comment]
You have to "use" first and you should run inside your project folder

**Comment by tbm98** [comment]
> You have to "use" first and you should run inside your project folder

But I just want to upgrade flutter :/

**Comment by leoafarias** [comment]
@tbm98 this seems to be related to https://github.com/leoafarias/fvm/issues/129

Can you provide the global path that you configured?

**Comment by tbm98** [comment]
the global path is
/Users/tbm98/fvm/default/bin/flutter

**Comment by tbm98** [comment]
in ~/fvm/versions don't have /bin folder

**Comment by leoafarias** [comment]
Default is a symlink.. can you tell me which flutter version the /default/ folder points to?

**Comment by leoafarias** [comment]
Versions should have the cached versions. If there is nothing there  it means no flutter version was installed through fvm

**Comment by tbm98** [comment]
> Default is a symlink.. can you tell me which flutter version the /default/ folder points to?
> […](#)
> On Sep 18, 2020, 9:37 AM -0600, tbm98 ***@***.***>, wrote: the global path is /Users/tbm98/fvm/default/bin/flutter — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

it is tbm98/fvm/versions/beta

**Comment by tbm98** [comment]
> Versions should have the cached versions. If there is nothing there  it means no flutter version was installed through fvm
> […](#)
> On Sep 18, 2020, 9:40 AM -0600, tbm98 ***@***.***>, wrote: in ~/fvm/versions don't have /bin folder — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes. I just use fvm to use global, never try install to flutter project before.

**Comment by leoafarias** [comment]
@tbm98 please test the latest prerelease version https://pub.dev/packages/fvm/versions/1.3.0-dev.0
`pub global activate fvm 1.3.0-dev.0`

**Comment by leoafarias** [comment]
I believe the release provides better information on what is going on. I will go ahead and close this issue. But please let me know if the issue persists and I will reopen it.

**Comment by tbm98** [comment]
Thank you! It worked well :D
