### ISSUE TITLE
[BUG] fvm macOS app stuck at upgrading

### ISSUE THREAD

**Issue by tbm98** [leoafarias/fvm#137]
macOS 10.15.6
version app: newest
version fvm: 1.2.3
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/52562340/93599565-85c17b00-f9e8-11ea-988b-990a1e011a14.gif)

**Comment by leoafarias** [comment]
Thanks @tbm98 will take a look.

**Comment by leoafarias** [comment]
@tbm98 fixed on the latest alpha.

**Comment by tbm98** [comment]
It worked ! :D
