### ISSUE TITLE
Help - Create new Project Web

### ISSUE THREAD

**Issue by kholyphoenix1** [leoafarias/fvm#139]
Hello, 
I added these paths to the Windows 10 path.
And I executed these commands, when you create a VSCode project it is created as Mobile.
Can anybody help me?

```
C:\Users\Windows\AppData\Local\Android\Sdk\platform-tools
C:\Users\Windows\AppData\Local\Pub
C:\Users\Windows\fvm\versions\
C:\Users\Windows\fvm\versions\stable
C:\Users\Windows\fvm\versions\beta
```

```
fvm flutter doctor --android-licenses
fvm flutter install beta
fvm flutter use beta --global
fvm flutter channel beta
fvm flutter upgrade
fvm flutter config --enable-web
```

**Comment by leoafarias** [comment]
@kholyphoenix1 I suggest reading the docs again. It seems you are mixing different commands between flutter and fvm and also adding multiple paths which I am not sure if it's needed.

You can sue fvm without adding it to the path by using how is documented.

Let me know what part is not clear and I can improve upon.

**Comment by leoafarias** [comment]
@kholyphoenix1 I will go ahead and close this. Let me know if I can help you any further
