### ISSUE TITLE
CLI: Windows Issues

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/fvm#142]
I am proactively looking into ways to better support Windows. But before opening up a Windows issue please be aware of some known behavior that can cause issues.

**Possible Errors**
- Invalid Kernel binary 
- Crash when using `Command Prompt` not `Powershell`
- When running `fvm use <version>` you get the following: `Sorry could not link PATH` or `Could not save config changes`.

These issues center around 2 important requirements for running on Windows.
1. On Windows make sure you are running in developer mode [Instructions Here](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development) or as an administrator
2. If you get errors with messages `invalid kernel binary` or `invalid sdk hash` it means you activated `fvm` using `flutter pub global activate fvm`. Make sure you install dart-sdk. After dart-sdk is installed. Follow [Instructions Here](https://github.com/leoafarias/fvm#usage). Activate `fvm` using `pub global activate fvm`.

**I will be updating this document, and looking for ways to improve. Please drop a comment or reaction if these instructions solve your problem. If they have not solved your problem please open up a new issue.**

**Comment by devkarim** [comment]
Just wanted to note out that when I used ```pub global run fvm:main use``` instead of ```fvm use``` it worked totally fine without facing issues like ```Can't load Kernel binary: Invalid kernel binary format version.```, could be useful for you.

**Comment by leoafarias** [comment]
@devkarim, thanks for that information. I am just not sure if it should be the correct behavior based on pub docs. There might be an issue with Pub itself, but I am glad there is a workaround.

**Comment by ben-xx** [comment]
Just leaving some additional information in case it's useful.

I also see the error:
`Can't load Kernel binary: Invalid SDK hash.`
using any fvm command, even though the command works fine.

And I double checked that I activated using:
`pub global activate fvm` and not `flutter pub global activate fvm`.
And that I run my Powershell as Administrator.  (I did not activate Developer Mode for Windows.)

I'm not sure if there's a problem with using the Dart SDK that is installed with flutter that causes the error message for me.  I didn't install another Dart SDK prior to activation since flutter installs the full SDK now and they recommend you don't need to install Dart separately.  I did have the Dart SDK in my PATH env var, pointing to Flutter's cached full dart-sdk version (for me `C:\src\flutter\bin\cache\dart-sdk\bin`), so `pub` was able to run from anywhere via Powershell.

Interestingly, the (Administrator) Powershell window that I used to activate fvm and to install the flutter SDKs, does not show this error each time I run a fvm command.  Only new (Administrator) Powershell windows show the `Can't load Kernel binary: Invalid SDK hash.` error.

@devkarim 's solution about using `pub global run fvm:main <command>` also works for me, eliminating the error.  I'm unsure why this works or how this is different than just using `fvm <command>`

Anyways, just wanted to leave this info in case it's of any use.

Thanks for creating a great tool.  This is a huge help.

**Comment by nicks101** [comment]
`fvm <command>` is only running on Powershell, it's crashing on cmd.

Error after running `fvm install stable`

```
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (6 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
Internal Error: Could not finish setting up Flutter sdk
```

Error after running `fvm use stable`

```
Exception: Could not save config changes
```

**Comment by nicks101** [comment]
> @nicks101 could you confirm that you are running on administrator or developer mode?
> 
> `On Windows make sure you are running in developer mode Instructions Here or as an administrator`

Now getting a differI upgraded dart and followed the fvm setup from scratch. 

1. First system variables were updated.
```
C:\Users\LENOVO\AppData\Roaming\Pub\Cache\bin
C:\src\flutter\bin
C:\tools\dart-sdk\bin
C:\Users\LENOVO\AppData\Local\Pub\Cache\bin
```

2. In cmd (running as administrator), fvm was activated using `pub global activate fvm`. It was installed successfully.
3. Installed and used a flutter channel in one of the projects. It's working as expected.

The issue I'm getting now is `Can't load Kernel binary: Invalid kernel binary format version.`, every time I use any of the `fvm <command>` or simply run `fvm`, even on running cmd as an administrator.

**Comment by leoafarias** [comment]
@nicks101 can you do a `pub cache repair`?

**Comment by nicks101** [comment]
I ran the below commands on cmd as an administrator.

1. Running `pub cache repair`

```
Downloading xdg_directories 0.1.2...
Downloading web_socket_channel 1.2.0...
Downloading vm_service 5.5.0...
Downloading vm_service 6.1.0+1...
Downloading webkit_inspection_protocol 0.7.4...
Downloading webkit_inspection_protocol 0.7.5...
Downloading win32 1.7.4+1...
Downloading vm_snapshot_analysis 0.5.5...
Downloading webdriver 2.1.2...
Downloading watcher 0.9.7+15...
Downloading xml 4.5.1...
Downloading yaml 2.2.1...
Downloading version 1.3.1...
Downloading uuid 2.2.2...
Downloading vector_math 2.0.8...
Downloading vector_math 2.1.0...
Downloading url_launcher_web 0.1.5+3...
Downloading usage 3.4.2...
Downloading url_launcher_platform_interface 1.0.9...
Downloading url_launcher_windows 0.0.1+3...
Downloading url_launcher_macos 0.0.1+9...
Downloading url_launcher_linux 0.0.1+4...
Downloading typed_data 1.2.0...
Downloading typed_data 1.3.0...
Downloading url_launcher 5.7.10...
Downloading timing 0.1.1+3...
Downloading time 1.4.0...
Downloading test_core 0.3.12...
Downloading test_api 0.2.19...
Downloading term_glyph 1.1.0...
Downloading term_glyph 1.2.0...
Downloading synchronized 2.2.0+2...
Downloading synchronized 3.0.0...
Downloading test 1.16.0...
Downloading sync_http 0.2.0...
Downloading string_scanner 1.0.5...
Downloading string_scanner 1.1.0...
Downloading stream_transform 1.2.0...
Downloading storage_path 0.2.0...
Downloading stack_trace 1.9.6...
Downloading stack_trace 1.10.0...
Downloading stream_channel 2.0.0...
Downloading stream_channel 2.1.0...
Downloading source_span 1.7.0...
Downloading source_span 1.8.0...
Downloading source_span 1.8.1...
Downloading source_maps 0.10.10...
Downloading sum_types 0.2.1+2...
Downloading source_gen 0.9.10+3...
Downloading shelf_web_socket 0.2.3...
Downloading shelf_web_socket 0.2.4+1...
Downloading shelf_static 0.2.9+1...
Downloading shelf_static 0.2.9+2...
Downloading shelf_proxy 0.1.0+7...
Downloading sse 3.6.0...
Downloading sse 3.8.1...
Downloading shelf_packages_handler 2.0.0...
Downloading source_map_stack_trace 2.1.0...
Downloading shelf 0.7.5...
Downloading shelf 0.7.9...
Downloading shared_preferences_windows 0.0.2+3...
Downloading shared_preferences_platform_interface 1.0.4...
Downloading shared_preferences_web 0.1.2+7...
Downloading shared_preferences_macos 0.0.1+11...
Downloading shared_preferences_linux 0.0.2+4...
Downloading shared_preferences 0.5.12+4...
Downloading share 0.6.5+4...
Downloading rxdart 0.22.6...
Downloading rating_dialog 1.0.0...
Downloading quiver 2.1.5...
Downloading quick_actions 0.4.0+10...
Downloading qr 1.3.0...
Downloading pubspec_yaml 2.0.1+1...
Downloading pubspec_parse 0.1.7...
Downloading pubspec_parse 0.1.8...
Downloading pub_semver 1.4.4...
Downloading pub_api_client 1.0.9...
Downloading process 3.0.13...
Downloading process 4.0.0...
Downloading process_run 0.10.12+3...
Downloading process_run 0.11.2+8...
Downloading provider 4.3.3...
Downloading pretty_json 1.1.0...
Downloading pool 1.4.0...
Downloading pool 1.5.0...
Downloading plugin_platform_interface 1.0.3...
Downloading platform 2.2.1...
Downloading platform 3.0.0...
Downloading plain_optional 0.1.3...
Downloading photofilters 2.0.1...
Downloading petitparser 3.1.0...
Downloading permission 0.1.7...
Downloading pedantic 1.9.2...
Downloading pedantic 1.10.0...
Downloading pedantic 1.11.0...
Downloading pdf_viewer_plugin 1.1.1...
Downloading pdf 1.13.0...
Downloading path_provider_windows 0.0.4+3...
Downloading path_provider_platform_interface 1.0.4...
Downloading path_provider_macos 0.0.4+8...
Downloading path_provider_linux 0.0.1+2...
Downloading path_provider 1.6.27...
Downloading path_parsing 0.1.4...
Downloading path_drawing 0.4.1+1...
Downloading path 1.7.0...
Downloading path 1.8.0...
Downloading page_transition 1.1.7+6...
Downloading package_config 1.9.3...
Downloading open_file 2.1.1...
Downloading node_preamble 1.4.12...
Downloading node_io 1.1.1...
Downloading node_io 1.2.0...
Downloading node_interop 1.2.1...
Downloading nested 0.0.4...
Downloading mustache_template 1.0.0+1...
Downloading multicast_dns 0.2.2...
Downloading mockito 4.1.1...
Downloading mime 0.9.7...
Downloading mime 1.0.0...
Downloading matcher 0.12.10...
Downloading meta 1.2.4...
Downloading meta 1.3.0...
Downloading native_stack_traces 0.3.7...
Downloading logging 0.11.4...
Downloading lint 1.5.3...
Downloading json_rpc_2 2.2.2...
Downloading json2yaml 1.0.1+1...
Downloading io 0.3.4...
Downloading io 0.3.5...
Downloading js 0.6.3...
Downloading introduction_screen 1.0.9...
Downloading intl 0.15.8...
Downloading intl 0.16.1...
Downloading intl 0.17.0...
Downloading image_picker_platform_interface 1.1.6...
Downloading image_picker 0.6.7+22...
Downloading image_cropper 1.3.1...
Downloading http_parser 3.1.4...
Downloading image 2.1.19...
Downloading json_annotation 3.1.1...
Downloading http_multi_server 2.2.0...
Downloading http 0.12.2...
Downloading html 0.14.0+4...
Downloading hive_generator 0.8.2...
Downloading hive 1.4.4+1...
Downloading graphs 0.2.0...
Downloading glob 1.2.0...
Downloading fvm 1.3.0-dev.0...
Downloading fvm 1.3.7...
Downloading functional_data 0.3.0...
Downloading freezed_annotation 0.12.0...
Downloading folder_picker 0.3.0...
Downloading flutter_template_images 1.0.1...
Downloading flutter_svg 0.19.3...
Downloading hive_flutter 0.3.1...
Downloading flutter_slidable 0.5.7...
Downloading flutter_share 1.0.5...
Downloading flutter_plugin_android_lifecycle 1.0.11...
Downloading flutter_full_pdf_viewer 1.0.6...
Downloading fixnum 0.10.11...
Downloading filex 0.2.2...
Downloading filesize 1.0.4...
Downloading file_testing 2.1.0...
Downloading file 5.2.1...
Downloading file 6.0.0...
Downloading ffi 0.1.3...
Downloading fake_async 1.2.0...
Downloading esys_flutter_share 1.0.2...
Downloading dwds 7.1.1...
Downloading ext_storage 1.0.3...
Downloading dots_indicator 1.2.0...
Downloading devtools_shared 0.9.6...
Downloading devtools_shared 0.9.6+3...
Downloading devtools_shared 2.0.0...
Downloading devtools_server 0.9.6...
Downloading devtools_server 0.9.6+3...
Downloading devtools_server 2.0.0...
Downloading dds 1.7.3...
Downloading date_format 1.0.9...
Downloading dartx 0.5.0...
Downloading dart_console 0.6.2...
Downloading dart_style 1.3.12...
Downloading devtools 0.9.6...
Downloading devtools 0.9.6+3...
Downloading devtools 2.0.0...
Downloading cupertino_icons 0.1.3...
Downloading csslib 0.16.2...
Downloading crypto 2.1.5...
Downloading coverage 0.14.2...
Downloading console 3.1.0...
Downloading completion 0.2.3...
Downloading collection 1.14.13...
Downloading collection 1.15.0...
Downloading code_builder 3.6.0...
Downloading clock 1.1.0...
Downloading cli_util 0.2.0...
Downloading cli_dialog 0.3.3...
Downloading cli_dialog 0.4.0...
Downloading checked_yaml 1.0.4...
Downloading convert 2.1.1...
Downloading convert 3.0.0...
Downloading charcode 1.1.3...
Downloading charcode 1.2.0...
Downloading characters 1.1.0...
Downloading built_value 7.1.0...
Downloading built_collection 4.3.2...
Downloading build_runner_core 6.1.7...
Downloading build_runner 1.11.1...
Downloading build_resolvers 1.5.3...
Downloading build_daemon 2.1.7...
Downloading build_config 0.4.5...
Downloading build 1.6.2...
Downloading browser_launcher 0.1.8...
Downloading boolean_selector 2.1.0...
Downloading barcode 1.17.1...
Downloading async 2.4.2...
Downloading async 2.5.0...
Downloading archive 2.0.13...
Downloading args 1.6.0...
Downloading animated_splash_screen 1.0.1+2...
Downloading analyzer 0.40.6...
Downloading analyzer 0.41.2...
Downloading _fe_analyzer_shared 12.0.0...
Downloading _fe_analyzer_shared 14.0.0...
Reinstalled 224 packages.
Binstubs exist for non-activated packages:
  From devtools: devtools
  From fvm: fvm
```

2. Running fvm.

```
C:\Windows\system32>fvm
No active package fvm.
```

3. Running `pub global list` : empty 


Should I activate fvm again?

**Comment by leoafarias** [comment]
@nicks101 yes go ahead

**Comment by Aquib17** [comment]
@leoafarias - Switching the "developer mode" on Windows 10 fixed the _Exception: Could not save config changes_ issue I was facing. Thanks!

**Comment by TheSunilVarma** [comment]
I tried all the mention solution but unfortunately i'm still getting Error : Can't load Kernel binary: Invalid kernel binary format version.

1. Tried with/without flutter ( pub global activate fvm )
2. With/without Administration | Developer Mode
3. CMD and PowerShell ( Admin/without )
4. Tried to manually delete flutter .cache-pub and pub cache repair

But no luck :(

**Comment by leoafarias** [comment]
@TheSunilVarma this is not an fvm issue and happens when the dart sdk changes the snapshot.

Go ahead and do a "pub cache repair"

**Comment by ArinFaraj** [comment]
I was having this issue in the latest stable version `1.3.8`.
And I tried it with `pub global run fvm:main` but it was giving the same error message,
Also tried `pub cache repair` but no luck there.

Then I switched to dev version `2.0.0-dev.6` and it **fixed** my problem.
Just wanted to let you all know.

``` dart
PS C:\Users\arin> fvm list --verbose
Can't load Kernel binary: Invalid SDK hash.
Unhandled exception:
NoSuchMethodError: The method 'cast' was called on null.
Receiver: null
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      new Settings.fromMap (package:fvm/src/utils/settings.dart:33:61)
#2      new Settings.fromJson (package:fvm/src/utils/settings.dart:26:21)
#3      Settings.readSync (package:fvm/src/utils/settings.dart:65:23)
#4      kVersionsDir (package:fvm/constants.dart:39:29)
#5      LocalVersionRepo.getAll (package:fvm/src/local_versions/local_version.repo.dart:32:12)
#6      ListCommand.run (package:fvm/src/commands/list_command.dart:25:44)
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#8      FvmCommandRunner.runCommand (package:fvm/src/runner.dart:80:18)
#9      FvmCommandRunner.run (package:fvm/src/runner.dart:60:20)
#10     main (file:///C:/Users/arin/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-1.3.8/bin/main.dart:4:28)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by leoafarias** [comment]
Have updated the docs, and I believe Windows is much more stable. Also we currently have a chocolatey version that further simplifies things. 

Will go ahead and close this issue.

**Comment by Prajun2010** [comment]
Although I have activated developer mode, I'm still getting "Exception: On Windows FVM requires to run in developer mode or as an administrator" while running fvm use.
After running fvm use <version>, it switches to the required version but still throws that error.

![Screenshot 2021-06-04 193011](https://user-images.githubusercontent.com/42827734/120811045-4e413180-c56b-11eb-8e9f-09ef5381b019.jpg)
![Screenshot 2021-06-04 193101](https://user-images.githubusercontent.com/42827734/120811209-74ff6800-c56b-11eb-9c71-b22d99249797.jpg)

**Comment by leoafarias** [comment]
@Prajun2010 Can you open a new issue please
