### ISSUE TITLE
[Feature Request] Add option to only show projects who have fvm enabled.

### ISSUE THREAD

**Issue by vanlooverenkoen** [leoafarias/fvm#152]
**Is your feature request related to a problem? Please describe.**
For some of our projects we have sub flutter packages. for these once we will use fvm of the root package. 

**Describe the solution you'd like**
It would be nice to have an option in the GUI to hide the projects who did not enable fvm

**Comment by leoafarias** [comment]
Good suggestion. This should be an easy win.
