### ISSUE TITLE
How to upgrade particular flutter e.g beta, master or stable

### ISSUE THREAD

**Issue by waqasakram117** [leoafarias/fvm#153]
How can I upgrade master or beta when my global has been set to the stable I can only upgrade stable through fvm flutter upgrade.

**Comment by leoafarias** [comment]
@waqasakram117 You would have to switch into the master or beta and run `fvm flutter upgrade`.

**Comment by waqasakram117** [comment]
I don't want to use "use" command to switch between flutter versions I am in my main terminal not in the project. Is there any way how can I upgrade channel from the terminal when my global has been set to stable and I want to upgrade my master or beta chennel?

**Comment by leoafarias** [comment]
To be honest this is a fairly simple request however this feature has been avoided on purpose. This is part of the decision to try not to mix flutter cli core functionality into fvm. Here are a few considerations:
- If you are trying to upgrade the channel I assume you will want to `use` it. What is the case for upgrading without needing to use it?
- You are currently able to do that with the GUI.

To be honest, all the functionality is there, is just exposing on a command like `fvm upgrade beta`, but I have been avoiding that for the reasons stated.

**Comment by waqasakram117** [comment]
I am closing this issue because to a satisfactory answer but please make a short article about how to install GUI though in its beta but It will help newbies.
