### ISSUE TITLE
How to remove fvm?[Feature Request]

### ISSUE THREAD

**Issue by gaozm0509** [leoafarias/fvm#157]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leoafarias** [comment]
If you used pub to install. ‘pub global deactivate fvm’.
https://dart.dev/tools/pub/cmd/pub-global#deactivating-a-package

**Comment by mwawrusch** [comment]
Adding to this, I did the above but flutter is still linked to 
/Users/.../fvm/default/bin/flutter
