### ISSUE TITLE
[Feature Request] Search projects

### ISSUE THREAD

**Issue by itsJoKr** [leoafarias/fvm#158]
**Is your feature request related to a problem? Please describe.**
I have a lot of projects and inside the projects tab, it becomes really hard to navigate.

**Describe the solution you'd like**
Search option. Extra would be if I can just start typing right away since that's how VsCode/Studio usually work.

**Comment by leoafarias** [comment]
@itsJoKr The search functionality does allow you to search projects as described.

**Comment by itsJoKr** [comment]
👍
