### ISSUE TITLE
How to modify the storage location of flutter sdk.

### ISSUE THREAD

**Issue by CaiJingLong** [leoafarias/fvm#16]
For example, I want to save sdk data on a mounted external disk.

**Comment by CaiJingLong** [comment]
Use environment variables as the location to specify this directory?

I think using a configuration file is a good choice, as `flutter config`.

For other configuration options that may exist in the future, you can also continue to maintain this configuration file instead of using a new environment variable for each configuration option.

**Comment by leoafarias** [comment]
@all-contributors please add @CaiJingLong for code

**Comment by leoafarias** [comment]
Merged into master
