### ISSUE TITLE
[BUG] RangeError (index): Invalid value: Valid value range is empty: 0 when installing pinned version

### ISSUE THREAD

**Issue by mx1up** [leoafarias/fvm#161]
**Describe the bug**
running fvm install without arguments throws an error and fails

**To Reproduce**
1. pin version in .fvm/fvm_config.json
2. fvm install

**Expected behavior**
install version if not installed yet

**Logs**
output:
RangeError (index): Invalid value: Valid value range is empty: 0

**Desktop (please complete the following information):**
 - OS: linux/windows
 - FVM Version 1.3.0
 - If Windows: not using powershell

**Comment by Clean-Cole** [comment]
@mx1up @leoafarias I can see this commit is in 1.3.0 tag, but I'm still getting the value range error after taking the update.  Is there anything else we need to do to get the fix?

**Comment by mx1up** [comment]
@Clean-Cole I think @leoafarias **re**released 1.3.0 so that might explain the problem if you already installed 1.3.0 before. I suggest reinstalling or maybe repairing pub cache: `pub cache repair`

**Comment by leoafarias** [comment]
Sorry the versions tagged are incorrect. I have fixed it, will release version 1.3.1 with the fix soon
