### ISSUE TITLE
[BUG]After setting FVM_HOME, the GUI download path remains unchanged

### ISSUE THREAD

**Issue by qcdys** [leoafarias/fvm#164]
Did I do something wrong?

**Comment by leoafarias** [comment]
@qcdys The GUI does not respect the env vars. Not sure why. However, it should respect the cache-path
https://github.com/leoafarias/fvm#set-cache-path

Please let me know if that works.

**Comment by qcdys** [comment]
> @qcdys The GUI does not respect the env vars. Not sure why. However, it should respect the cache-path
> https://github.com/leoafarias/fvm#set-cache-path
> 
> Please let me know if that works.

I tried set Cache-Path, but it didn't work. I wanted the GUI to customize the download path, which is important for OCD. Thank you, brother.

**Comment by leoafarias** [comment]
@qcdys ok, I will go ahead and add this to the backlog for the next version of the GUI.

**Comment by leoafarias** [comment]
@qcdys Was just going to work on this but I think I know what is the problem. You have to close the app and open it again after changing cache-path through the CLI.
