### ISSUE TITLE
cli_pkg breaking changes incoming

### ISSUE THREAD

**Issue by nex3** [leoafarias/fvm#165]
Hey folks! I noticed you're using `cli_pkg`, so I wanted to give you a heads-up about a breaking change coming in https://github.com/google/dart_cli_pkg/pull/57. We're changing the configuration variables from plain Dart properties to instances of a new `ConfigVariable` class, which allows users to set variable values as callbacks so that expensive and fallible operations like parsing files don't have to happen for unrelated Grinder tasks. All you need to do to become compatible with the new version is change `pkg.variable = ...` into `pkg.variable.value = ...`.

Unfortunately, since we're still in the pre-release versioning stage, we don't have a clean way of designating this new breaking change with a major version bump. Instead, I'm filing issues against downstream packages to make sure they're aware of the change in advance and have time to update.

To minimize breakage, I'm planning to land https://github.com/google/dart_cli_pkg/pull/57 and tag it on git for a period of time before I release it on pub. This will allow you to add a temporary dependency override on the Git version with the new API:

```yaml
dependency_overrides:
  dart_cli_pkg:
    git:
      url: git://github.com/google/dart_cli_pkg
      ref: 1.0.0-beta.10
```

Once all the downstream dependencies have updated, I'll release `1.0.0-beta.10` for real and you can remove this override.

Sorry for the trouble! I hope to release a proper stable version once https://github.com/google/dart_cli_pkg/pull/56 is resolved and Chocolatey support is online again.

**Comment by leoafarias** [comment]
@nex3 Thank you for taking the time to do this!

**Comment by nex3** [comment]
The PR has landed and the tag has been pushed. Please let me know when you've updated so I can release it on pub.

**Comment by nex3** [comment]
Okay, *now* you should be good to go.
