### ISSUE TITLE
[BUG] Flutter command does not exit when run through Fastlane

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/fvm#169]
When running `fvm flutter ....` command does not exit when running through a fastlane lane.

```
lane :fvmtest do
    Dir.chdir ".." do
      sh("fvm flutter doctor")
    end
  end
```

**Comment by mx1up** [comment]
thanks, v1.3.4 also fixes running fvm from git bash on windows (before it hung at the end of execution)

**Comment by kuhnroyal** [comment]
Works on my machine now with fastlane, thanks. Still gotta try the SSH session on CI.

**Comment by kuhnroyal** [comment]
This also solved the SSH problems on my CI server. 👍
