### ISSUE TITLE
Fastlane stopped running when fvm was outdated

### ISSUE THREAD

**Issue by vanlooverenkoen** [leoafarias/fvm#172]
I just have been figuring out why fastlane would "hang" and stop doing anything at random times. 

Turns out it had something to do with fvm being outdated.

I had 1.3.3
After updating to 1.3.4 the issue was resolved. (Mac) 
Do you have any idea what the reason for this could be?

**Comment by leoafarias** [comment]
Here is the issue that was closed https://github.com/leoafarias/fvm/issues/169. It had to do with the sharedStdin not being called in a conditional.
