### ISSUE TITLE
[BUG] fvm install no longer creates symlink

### ISSUE THREAD

**Issue by mx1up** [leoafarias/fvm#173]
**Describe the bug**
when running `fvm install` with a `.fvm/fvm_config.json` available, it used to "use" the specified version automatically. It does not seem to do that anymore.

**To Reproduce**
1. `.fvm/fvm_config.json` with contents = `{"flutterSdkVersion":"beta"}`
2. Run `fvm install`

**Expected behavior**
flutter_sdk symlink should be created

**Logs**
```
$ fvm --verbose install
Version: beta - already installed.
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (6 days ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
```

**Desktop (please complete the following information):**
 - OS: linux, from bash terminal
 - FVM Version: 1.3.4

**Comment by leoafarias** [comment]
`pub global activate fvm 1.3.5-dev` has this fix.
