### ISSUE TITLE
[Feature Request] Should recreate .fvm/flutter_sdk automatically

### ISSUE THREAD

**Issue by ened** [leoafarias/fvm#177]
**Is your feature request related to a problem? Please describe.**

We will use `fvm` in our team, so the absolute link to the flutter sdk within `.fvm` is a problem:

```
$ ls -la .fvm 
total 8
drwxr-xr-x   4 ened  admin   128 Oct 24 12:36 ./
drwxr-xr-x  36 ened  admin  1152 Oct 24 13:34 ../
lrwxr-xr-x   1 ened  admin    31 Oct 24 12:36 flutter_sdk@ -> /Users/ened/fvm/versions/1.20.4
-rw-r--r--   1 ened  admin    35 Oct 24 12:36 fvm_config.json
```

The `flutter_sdk` link is correct, but only on my own machine. It will be different for other developers.

**Describe the solution you'd like**

1. fvm should inform the user to add `.fvm/flutter_sdk` to `.gitignore`.
2. fvm should re-create (or update!) `.fvm/flutter_sdk` every time its run

**Describe alternatives you've considered**

Perhaps pushing the flutter_sdk folder to something like `.fvm/$USER/flutter_sdk`.
Or, depending on the platform, use relative links, like `~/fvm/version/1.20.4`.
This is however very fragile.

**Comment by leoafarias** [comment]
@ened You should not version the symlink when working as a team. Once the team members use the project they can run 'fvm install' this will create the link correctly within their machine.

**Comment by leoafarias** [comment]
Also make sure you are on the latest fvm version because there is was a bug on this command for the symlink on a previous one

**Comment by ened** [comment]
@leoafarias thank you for answering - so essentially only item 1 remains, `fvm` should inform users upon first usage. 

I will extend our project readme with a section on `fvm install`. :)

**Comment by vanlooverenkoen** [comment]
as @leoafarias already said you don't want to commit symlinks because they contain info of you personal development machine. When a new dev start with a project that uses fvm he needs to install the fvm version. and use that specific fvm version. For that we wrote a dart tool that does all these things for us.

```
import 'dart:convert';
import 'dart:io';

main() {
  final file = File('.fvm/fvm_config.json');
  final jsonObject = json.decode(file.readAsStringSync());
  final version = jsonObject['flutterSdkVersion'];

  executeCommand('rm', ['.fvm/flutter_sdk']);
  executeCommand('fvm', ['version']);
  executeCommand('fvm', ['install', version]);
  if (version == 'stable' || version == 'beta' || version == 'dev' || version == 'master') {
    executeCommand('fvm', ['flutter', 'upgrade', version]);
  }
  executeCommand('fvm', ['use', version]);
  executeCommand('fvm', ['flutter', 'doctor', '-v']);
}

void executeCommand(String cmd, List<String> params) {
  final fullCommand = '$cmd ${params.join(' ')}';
  try {
    printMessage('\nExecuting command:\n$fullCommand');
    final result = Process.runSync(cmd, params);
    final output = result.stdout;
    if (output.toString().isNotEmpty) {
      printMessage('$output');
    }
  } catch (e) {
    printMessage('\nFailed to execute command: $fullCommand\n$e');
    exit(-1);
  }
}

void printMessage(Object message) {
  // ignore: avoid_print
  print(message);
}
```

**Comment by leoafarias** [comment]
@vanlooverenkoen The `fvm install` now does the following:
- Grabs fvm config version
- Checks if the version is installed if not install it
- Create symlink

Based on what I am seeing the only thing it does not do is run the upgrade...
Let me know if this works for you

```dart
main() {
  final file = File('.fvm/fvm_config.json');
  final jsonObject = json.decode(file.readAsStringSync());
  final version = jsonObject['flutterSdkVersion'];

  executeCommand('fvm', ['version']);
  executeCommand('fvm', ['install']);
  if (version == 'stable' || version == 'beta' || version == 'dev' || version == 'master') {
    executeCommand('fvm', ['flutter', 'upgrade', version]);
  }
  executeCommand('fvm', ['use', version]);
  executeCommand('fvm', ['flutter', 'doctor', '-v']);
}
```

**Comment by leoafarias** [comment]
Updated readme with instructions to add .gitignore

**Comment by ened** [comment]
@leoafarias has this behavior changed in 2.X? The symlink is not created anymore, it seems?

**Comment by kuhnroyal** [comment]
I think something has changed, I needed to run `fvm use ...` again manually.

**Comment by ened** [comment]
@kuhnroyal what are your exact recovery steps?

**Comment by leoafarias** [comment]
@ened is the version that you want to link already installed when running `fvm install`? Looking at the code, if the version is cached already it returns before updating the link.

**Comment by ened** [comment]
@leoafarias yes, that definitely breaks and causes the symlink folder not to appear.

**Comment by leoafarias** [comment]
@ened deploy version `2.0.2-dev.0` to confirm it resolves the issue

**Comment by kuhnroyal** [comment]
My Flutter version was already installed and the project config contains `"flutterSdkVersion": "2.0.5"`.
I manually ran `fvm use 2.0.5` and it created the link.

**Comment by leoafarias** [comment]
Just published 2.0.2-dev.0 please confirm the issue is solved and I will bump the final version

**Comment by kuhnroyal** [comment]
Seems to work on my end, thanks for the quick reaction!

**Comment by ened** [comment]
I can confirm this as well. Thank you @leoafarias

**Comment by leoafarias** [comment]
Thanks ok deploying the final version. https://github.com/leoafarias/fvm/actions/runs/809823464
