### ISSUE TITLE
Recursively look up fvm file.

### ISSUE THREAD

**Issue by CaiJingLong** [leoafarias/fvm#18]
I think we should recursively look up the parent directory and find the most recent fvm file.
To support nested projects, you can just put fvm in the root directory.

**Comment by CaiJingLong** [comment]
such as
`$  flutter create -t plugin plugin_example`

![image](https://user-images.githubusercontent.com/14145407/66808214-5941eb00-ef5d-11e9-886d-b69b262a9b7f.png)

**Comment by leoafarias** [comment]
@CaiJingLong This is a good idea. Let me know if you want to tackle this, if not I can put it in my backlog

**Comment by CaiJingLong** [comment]
I think I can open PR to solve it.

**Comment by amitkot** [comment]
This does not work for me in 1.1.3:
```bash
$ pwd
/Users/a/proj

$ ls -da .fvm
.fvm

$ fvm flutter devices
1 connected device:
...

$ cd packages/foo
$ fvm flutter devices
⚠️  No such file or directory
```
