### ISSUE TITLE
Want to point out that at the moment `fvm` is hard to use for modular Flutter projects.

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/fvm#180]
Want to point out that at the moment `fvm` is hard to use for modular Flutter projects. 

For example, even in a quite simple case (with not that many modules) like the one below, calling `fvm flutter --version` inside the project root and `client_app` would result in different versions being printed since none of the sub-projects have their own `.fvm` directory. The first one will print a proper project-level flutter version while the second one will print the global default flutter version.

A real-life example of a (somewhat) modular project structure (none of the sub-projects have .fvm directory):
![image](https://user-images.githubusercontent.com/5076429/97372967-7f62d080-18bd-11eb-8c6f-df325131aa5c.png)

I believe that it won't be hard to make `fvm` look for the `./fvm/flutter_sdk` not only within the current directory but also within some N levels of parent directories.

This would allow for a neat *flutter version scoping* that, in turn, will make both the issue's case and modular project cases work well.

@leoafarias Do you see any caveats in the algorithm explained above?

_Originally posted by @s0nerik in https://github.com/leoafarias/fvm/issues/151#issuecomment-717599482_

**Comment by s0nerik** [comment]
Thanks a lot! Works like a charm!
