### ISSUE TITLE
Doc Clarification on setting a global version

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [leoafarias/fvm#183]
The docs say 

** Do not activate fvm using flutter pub global activate** if you plan on using the --global flag.
But the only instructions we have for installing this is:
## Usage

1. [Install Dart](https://www.dartlang.org/install).
2. Activate Fvm:

```bash
> pub global activate fvm
```

The warning command includes the word "flutter" in i , but I'm not sure if this is a typo or that if we run just `pub global activate` and we want to use the active fvm version globally, it's fine.
If it's a typo and you meant not to run `pub global activate fvm`, then what should we use instead? It would help if you specified the correct way to run this right after the warning

**Comment by leoafarias** [comment]
@ThinkDigitalSoftware I updated the doc to make it a bit clearer. You should not use the `pub` version that comes with flutter to install fvm. 

The reason for that is that you will be switching the Flutter SDK and that will impact the pub cache.

**Doc updated**
Do not activate fvm using `flutter pub global activate` if you plan on using the --global flag. Only activate fvm using `pub global activate`.

**Comment by ThinkDigitalSoftware** [comment]
Thanks. Now where do we find fvm's dart installation so I can add it to the path?

**Comment by leoafarias** [comment]
@ThinkDigitalSoftware you have to install dart as per the instructions.

https://dart.dev/get-dart

After that everything is the same.

**Comment by ThinkDigitalSoftware** [comment]
Oh, OK. I'll just point to the old installation that was installed along-side flutter. Will that work?

**Comment by leoafarias** [comment]
Not sure I understand. It's important that flutter pub is not used to install fvm... since fvm will be used to change the flutter version.

1. Install dart sdk 
2. Pub global activate fvm

And you should be ready to go.

**Comment by ThinkDigitalSoftware** [comment]
The issue is that I came from a regular flutter installation to fvm, so I'm trying to avoid having to delete the existing installation. Currently, the dart from my old flutter installation is the one used when calling `dart` with no parameters. When I update Flutter using fvm, will FVM attempt to update the  dart version as well if there is an update that comes with it?

**Comment by leoafarias** [comment]
If you use fvm to change the main version when you call `flutter` on the terminal, most likely this will cause conflicts. That is why I suggest installing the standalone dart version.
With fvm you can use `flutter` as global but you can just use per project. The issue with using `flutter pub` as the way to install fvm , is that you have almost a cyclic conflict where you have flutter being used to install fvm, and fvm being used to install flutter.

Let me know if that makes sense. Maybe I am not explaining this that well.

**Comment by NestorDevs** [comment]
My experience with fvm has been a bit tedious and it would guide me to receive advice ... I use linux ... and I had a regular flutter installation according to the documentation ... then I deleted that installation ... I installed dart standalone then fvm ... my doubt here it is: do i still need to install flutter sdk apart from fvm? I say it because the flutter commands do not work for me .. and when I try to create an app using fvm it gives me the following error ...

Usage Error: Flutter version null is not installed

**Comment by leoafarias** [comment]
@NestorDevs thanks for the feedback. The way I personally use is with the Flutter sdk installed and that becomes my global default version.

Then I use fvm for project specific.

I plan on releasing the brew version soon and that will make things much simpler.

**Comment by NestorDevs** [comment]
you mean i need flutter sdk for fvm to work?

**Comment by leoafarias** [comment]
You do not. I understand your problem after chatting. Let me know any other suggestions to improve the docs.

**Comment by NestorDevs** [comment]
Closed
