### ISSUE TITLE
[Doc] Clarify install procedure for Flutter users

### ISSUE THREAD

**Issue by awhitford** [leoafarias/fvm#184]
As a Flutter developer, I already have Flutter installed -- and Dart is installed and managed by the Flutter install.  (When I `flutter upgrade`, Dart is upgraded.)

I am a little confused about how to install `fvm` because the instructions seem to start with installing `dart` first, then installing `fvm`.  However, the `dart` version changes depending on the `flutter` version, so how do all of these dart & flutter versions co-exist?

**Is it required or recommended to uninstall `flutter` before installing `fvm`?**

**Comment by leoafarias** [comment]
@awhitford Based on your PR, are things clearer now? I am working on a brew native compiled install to avoid some of these issues.

**Comment by leoafarias** [comment]
I will close this issue as it seems to be a copy of #183

**Comment by awhitford** [comment]
I was able to get `fvm` installed, and I did _uninstall_ `flutter` first.
I then set the `stable` as the `--global` version.
So far, so good.

However, I raised this issue to improve the documentation to help others in the future.

And I imagine that the Dart I installed to install FVM won't get upgraded, while the embedded Dart's under each Flutter versions will.

**Comment by leoafarias** [comment]
You can continue to update the dart sdk. One thing to keep in mind is that the dart sem is actually ahead of Flutter sdk... 

Hopefully the native binary solves this problem.
