### ISSUE TITLE
[BUG] Create dmg for mac os

### ISSUE THREAD

**Issue by Tiska** [leoafarias/fvm#187]
Hi, first thanks for your tool cli, it's an amazing tool with features flutter cli should have.

I tried to build the mac os GUI, i got this error : 

execution error: Finder got an error: Can’t set item "fvm.app" of disk "FVM Installer" to {260, 250}. (-10006)
Failed running AppleScript
"disk2" ejected.

Do you know what it could be ?

**Comment by leoafarias** [comment]
@Tiska are you using the standard build command? 

The installer script is just to build a nice looking app installer you don't need it to build the Mac.

**Comment by Tiska** [comment]
Ok I did not tried the standard command, I guess it's something like flutter build macos?

**Comment by leoafarias** [comment]
Correct, you can find more info in the docs here
https://flutter.dev/desktop#build-a-release-app

**Comment by Tiska** [comment]
which flutter version du you use ? i tried with 1.24.0-7.0.pre from dev but I can't resolve the pubspec wit h that version

**Comment by leoafarias** [comment]
@Tiska Master was not building because of a conflict. Which I just resolved. 
However, the version is tagged here.
https://github.com/leoafarias/fvm/tree/App-1.0.0-alpha.1
