### ISSUE TITLE
[BUG] fvm version 1.3.6 broken

### ISSUE THREAD

**Issue by maks** [leoafarias/fvm#188]
steps to reproduce:
* run fvm, get told:
```
FVM Update Available 1.2.3 → 1.3.6 
Changelog: https://github.com/leoafarias/fvm/releases/tag/1.3.6
Run pub global activate fvm to update
```
* run `flutter pub global activate fvm` as per instructions
* fvm successfully updated: 
```
fvm version
1.3.6
```
* try running `fvm list`:
```
fvm list
FormatException: Not a properly formatted version string
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 1.20.0, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.51.1)
[✓] Connected device (4 available)
```

**Comment by leoafarias** [comment]
@maks Could you provide me the versions that are installed and would be returning on the list?

**Comment by maks** [comment]
Sure thing. I originally had (working prior to version update):
```
fvm list
Versions path:  /home/maks/fvm/versions
beta (global)
dev
dev-real
master
stable
```

And I suspected that it was `dev-real` causing the problem, but even after I changed to:
```
ls ~/fvm/versions/
beta  dev  devreal  master  stable
```

I still get the same error.

**Comment by leoafarias** [comment]
@maks The issue is that FVM is looking for channels or valid version numbers. There is a lot of validation in regards to these things. The error is that devreal is not a properly formatted version, since its not a channel, it falls under a version. 

I could fix this but think there could be changes to support custom versions which might be a bit more work. 

Can you tell me a bit about your specific use case?

**Comment by maks** [comment]
Thanks for looking into this so quickly @leoafarias !
My use case is that currently I'm working on a project that needs to use a SDK "pinned" at a specific git commit rather than a channel or release tag. I'm aware that's not a good practice, I just am not in a position to change that at the moment.

So because fvm also didn't support having a specific commit, I used the workaround of using dev channel and then myself just manually checking out to the specific commit I needed.

So I know it's not something most people should do, but sometimes it is necessary to be on a specific commit rather than a channel or release tag, so could fvm have support added for that?

**Comment by leoafarias** [comment]
Hmmm that could be done. I would have to think about it. For now I would suggest opening that flutter sdk, there should be a “version” file in its root. I would open it and use  that version as the directory name if there is one.

If not I would just create a custom one like 2.0.0+custom

**Comment by maks** [comment]
Ah brillant, thanks @leoafarias ! I didn't realise that something like `2.0.0+custom` would parse ok with fvm, with `+` being the key thing. So that solves my immediate problem, so happy to close this.
