### ISSUE TITLE
[BUG] POP_OS Clone error

### ISSUE THREAD

**Issue by OrlandoEduardo101** [leoafarias/fvm#192]
**Describe the bug**
Internal Error: Could not install

**Screenshots**
![image](https://user-images.githubusercontent.com/37966182/101367626-1b9cd180-3885-11eb-8c01-b2cbc8fa2c36.png)

I didn't find any report of this error on the internet, does anyone know what it could be? I already gave "pub cache repair", reinstalled Dart and FVM several times.
I'm using POP! _OS 20.10

Thank you!

**Comment by leoafarias** [comment]
@OrlandoEduardo101what version of FVM are you using? I believe the last version should give a better output for this error.

**Comment by OrlandoEduardo101** [comment]
> @OrlandoEduardo101what version of FVM are you using? I believe the last version should give a better output for this error.

i'm use 1.3.6

**Comment by leoafarias** [comment]
@OrlandoEduardo101 could you try to do a git clone if that flutter branch in that directory using the git command in your terminal?

**Comment by OrlandoEduardo101** [comment]
he starts cloning, stops nowhere and doesn't clone.

![image](https://user-images.githubusercontent.com/37966182/101669826-2c8a4600-3a31-11eb-86d2-beadf28cedb6.png)

**Comment by leoafarias** [comment]
Can you do a --verbose?

**Comment by OrlandoEduardo101** [comment]
yes, i already did it with verbose (-v) in the image.

**Comment by leoafarias** [comment]
@OrlandoEduardo101 seems this is not related to FVM. I found this link here which might give a clue
https://bbs.archlinux.org/viewtopic.php?id=225649

**Comment by OrlandoEduardo101** [comment]
Okay, thanks, look at the link and search for more.
I will close the issue.
