### ISSUE TITLE
[BUG] Long switching time on macOS

### ISSUE THREAD

**Issue by orestesgaolin** [leoafarias/fvm#195]
**Describe the bug**
When calling `fvm use stable` or `fvm use any-other-version` it takes several long seconds (10+) to finish switching

![CleanShot 2020-12-17 at 22 23 17](https://user-images.githubusercontent.com/16854239/102545440-8a183580-40b6-11eb-8dd9-6d5e1a5a9198.gif)

**To Reproduce**
1. Go to terminal..
2. Run `fvm use stable`...
3. Wait 10+ seconds
4. Version is switched

**Expected behavior**
It used to happen immediately

**Logs**
Nothing is printed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - FVM Version: 1.3.6
 - using zsh, default configuration of fvm, installed via `pub`

**Additional context**

**Comment by leoafarias** [comment]
Not sure why this started happening but the runner seems to not exit right away anymore. Will release a fix later today.
