### ISSUE TITLE
[Feature Request] Proxy command for Dart

### ISSUE THREAD

**Issue by isanimu** [leoafarias/fvm#197]
**Is your feature request related to a problem? Please describe.**
As of Flutter 1.21, the Flutter SDK includes the full Dart SDK. FVM doesn't have proxy command for Dart yet.

**Describe the solution you'd like**
Need to be able call Dart CLI when using FVM.
```zsh
fvm dart --version
```

**Describe alternatives you've considered**
None

**Additional context**
If Dart isn't available from the SDK, then show error message like Dart isn't available, it might be the SDK didn't bundle Dart.

**Comment by leoafarias** [comment]
@isanimu can you describe the use case for this, some of the dart commands already are proxied through flutter like `flutter pub`

**Comment by isanimu** [comment]
@leoafarias I didn't know that. OK, close this. Thanks.
