### ISSUE TITLE
[BUG] fvm use <version> --global mode doesn't work.

### ISSUE THREAD

**Issue by bytes-stack** [leoafarias/fvm#198]
**Describe the bug**
It seems that `global mode` doesn't work. I use `fvm` in windows git bash.

**To Reproduce**
1. Run `fvm.bat use 1.24.0-10.2.pre`
2. Run `fvm.bat use 1.17.1 --global`
3. Run `fvm.bat flutter run`
4. The project still runs in 1.17.1, not my global SDK version

![image](https://user-images.githubusercontent.com/76029935/102757986-08bded00-43ad-11eb-8619-e9ec7d093bbf.png)
![image](https://user-images.githubusercontent.com/76029935/102758128-3dca3f80-43ad-11eb-8b69-ff49a7bf3120.png)
As the two pictures show: first, I `fvm.bat use 1.24.0-10.2.pre` then `fvm.bat use 1.17.1 --global`, but when I run the app, it prints dart version is 2.12, which means it still on the 1.17(use dart 2.8)

**Desktop (please complete the following information):**
 - OS: Windows
 - FVM Version 1.3.6
 - If Windows: Which Powershell are you using? git bash

**Comment by leoafarias** [comment]
Did you set the global env car path also?

**Comment by bytes-stack** [comment]
> Did you set the global env vat path also?

Yes, I add `C:\Users\username\fvm\default\bin` to PATH

**Comment by leoafarias** [comment]
@bytes-stack One more question for clarification. FVM will prioritize the version configured within the project over the global version. Could you just make sure that `.fvm` folder is removed from the project when you ran the test?

**Comment by bytes-stack** [comment]
> @bytes-stack One more question for clarification. FVM will prioritize the version configured within the project over the global version. Could you just make sure that `.fvm` folder is removed from the project when you

**Comment by bytes-stack** [comment]
> @bytes-stack One more question for clarification. FVM will prioritize the version configured within the project over the global version. Could you just make sure that `.fvm` folder is removed from the project when you ran the test?

**Comment by leoafarias** [comment]
@bytes-stack why are you using fvm.bat instead of `fvm`?

**Comment by leoafarias** [comment]
@bytes-stack sorry for the delay on this. I am in the middle of a global refactor 2.0 and will close this since I did not have more info.
