### ISSUE TITLE
flutter desktop 

### ISSUE THREAD

**Issue by gedw99** [leoafarias/fvm#2]
Hey @leoafarias 
I was about to write something like this to speed up doing flutter projects. Thanks for this.

Check this out too !
https://github.com/go-flutter-desktop/go-flutter/blob/master/example/simpleDemo/engineDownloader.go

It allows downloading the Flutter dependencies for Desktop.

How about also incorporating this ?

**Comment by leoafarias** [comment]
Thanks, @gedw99 do you mind sharing a bit more about what you have in mind

**Comment by leoafarias** [comment]
Will close this until I hear back
