### ISSUE TITLE
[a bit BUG] About VSCode setting for dynamic switching of flutter SDK version

### ISSUE THREAD

**Issue by sgr-ksmt** [leoafarias/fvm#201]
**Is your feature request related to a problem? Please describe.**
I tried to configure the IDE setting for VSCode to switch the flutter SDK version dynamically according to [README](https://github.com/leoafarias/fvm#you-can-also-add-the-version-symlink-for-dynamic-switch) like that.

```js
{
  "dart.flutterSdkPaths": [".fvm/flutter_sdk"]
}
```

However, It didn't work well. 
After all, I had to click on the flutter version displayed in the bottom right corner of VSCode to switch it myself.
And then the following line was automatically added by VSCode.

```diff
{
  "dart.flutterSdkPaths": [".fvm/flutter_sdk"],
+  "dart.flutterSdkPath": "/User/user/path/to/project/.fvm/flutter_sdk",
}
```

I don't think it's smart.

**Describe the solution you'd like**

I found a solution to solve this problem completely.
Dynamic switching is now enabled by rewriting the following:

```js
{
  "dart.flutterSdkPaths": [
    "${fileWorkspaceFolder}/.fvm/flutter_sdk"
  ],
}
```

By adding `${fileWorkspaceFolder}/` in front of `.fvm/flutter_sdk`, VSCode seems to expand the absolute path of the current project.

ref: [VSCode - Variables Reference](https://code.visualstudio.com/docs/editor/variables-reference)

So, Could you confirm it and please update README If the idea I've suggested is true?

**Comment by leoafarias** [comment]
@sgr-ksmt sorry for the delay on the response. First thing is that its important that the configuration here

```
{
  "dart.flutterSdkPaths": [".fvm/flutter_sdk"]
}
```

is added within the vscode settings of a project, and not in the global settings. This will provide a relative path.

**Comment by leoafarias** [comment]
Will close this issue please reopen if there is any issue
