### ISSUE TITLE
[Feature Request] Add a command to get the version of flutter being used

### ISSUE THREAD

**Issue by mehcode** [leoafarias/fvm#203]
**Is your feature request related to a problem? Please describe.**

`fvm flutter --version` takes ~5 seconds to run on my Mac. However `fvm --verbose flutter --version` prints the flutter version within 0.06s.

**Describe the solution you'd like**

A command like `fvm version flutter` that would print _just_ the version for flutter.

I want to add support for fvm in a module for https://starship.rs/

**Describe alternatives you've considered**
 
N/A

**Additional context**

N/A

**Comment by leoafarias** [comment]
@mehcode I was not able to replicate this. There was a similar issue that was fixed on 1.3.7 but it was in regards to the `use` command, causing a delay when exiting.

Could you provide any further information?

**Comment by mehcode** [comment]
On. Sorry for not being clear. On my iMac, _any_ flutter command (proxied through fvm or not) takes several seconds to show any output. 

There are a few issues in the flutter repo about this. 

Good news is fvm runs instantly. So I was hoping for a workaround to use in the shell prompt that is quick.

**Comment by leoafarias** [comment]
@mehcode it might be best to have that version within Flutter which is actually the source of truth. Let me know if this has been resolved, or if you have the link to their issues so I can track them.  I will go ahead and close this issue for now.
