### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mengxy936** [leoafarias/fvm#204]
**Describe the bug**
fvm use command doesn't work

**Logs**
PS D:\app_merchant\app_merchant> fvm use 1.17.5
Project now uses Flutter: 1.17.5
Unhandled exception:
Exception: Sorry could not link C:\Users\ke'j'f'l'da'j'h'l'f'\fvm\versions\1.17.5
#0      createLink (package:fvm/utils/helpers.dart:43:5)
#1      updateFlutterSdkBinLink (package:fvm/utils/project_config.dart:29:3)
#2      setAsProjectVersion (package:fvm/utils/project_config.dart:23:3)
#3      UseCommand.run (package:fvm/commands/use.dart:77:7)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#6      new Future.sync (dart:async/future.dart:224:31)
#7      CommandRunner.run (package:args/command_runner.dart:112:14)
#8      fvmRunner (package:fvm/fvm.dart:27:23)
#9      main (file:///C:/Users/ke'j'f'l'da'j'h'l'f'/AppData/Roaming/Pub/Cache/hosted/pub.flutter-io.cn/fvm-1.2.3/bin/main.dart:4:9)        
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Desktop (please complete the following information):**
 - FVM Version [e.g. 22]
 - If Windows: Which Powershell are you using?
win10 gitbash

**Comment by leoafarias** [comment]
@mengxy936 are you running with admin privileges or in developer mode? Please check the readme about windows troubleshooting
