### ISSUE TITLE
[Feature Request] Docker image for CI/CD

### ISSUE THREAD

**Issue by andreadelfante** [leoafarias/fvm#205]
**Is your feature request related to a problem? Please describe.**
Many CI/CDs use docker to run pipelines.

**Describe the solution you'd like**
It'd be nice to have a ready-to-use docker image to use in a CI/CD environment, to install a specific version of Flutter and to execute some unit/integration tests, using **fvm**.

**Comment by kuhnroyal** [comment]
Good point, I am currently trying to move some CI step from the Mac server to a linux server and started building an image. There are a couple images out there in the Docker registry to start with.

**Comment by andreadelfante** [comment]
I can create a new PR to set up an initial Dockerfile with the latest fvm version.
This would be a great starting point to standardize CI with flutter and fvm!

**Comment by leoafarias** [comment]
Not sure 100% of the use case, I believe it seems to be a custom CI setup, but would not mind reviewing a PR if you guys think its valuable.
