### ISSUE TITLE
[Feature Request] Automatic linking

### ISSUE THREAD

**Issue by kuhnroyal** [leoafarias/fvm#207]
**Is your feature request related to a problem? Please describe.**
I am still running into cases of the wrong SDK being used when switching between branches in my projects that use different Flutter SDK versions. I have the config file committed to VCS and switching a branch also changes the config file.

**Describe the solution you'd like**
I would expect that after a checkout of a different config file and executing an fvm command, I would see either a warning that the wrong SDK is being used or ideally fvm would link and use the correct SDK automatically.

**Comment by leoafarias** [comment]
@kuhnroyal sorry for the delay, catching up on these issues. 
- You switched the config to an sdk version that is not installed
- when you ran `fvm flutter` it ran on a different flutter

The step above is the test workflow?

**Comment by kuhnroyal** [comment]
No worries, just tested this again.
* I have 2 branches, one uses stable channel and one uses beta.
* Both Flutter versions are already installed.

After switching between the branches the correct SDK is used when run via `fvm flutter ...` but the linked SDK in `.fvm/flutter_sdk` remains the previous version unless I manually run `fvm install`. When I forget to run `fvm install` it leads to all kinds of IDE failures as the SDK in the IDE points to `.fvm/flutter_sdk`.

It would be great if FVM can automatically update the linked SDK path.

**Comment by leoafarias** [comment]
Hmmm yes it makes sense... I will trigger a check and ask if you want to to install to avoid a needless download
