### ISSUE TITLE
Error: no flutter version matched 1.22.0 

### ISSUE THREAD

**Issue by haibowen** [leoafarias/fvm#209]
When I execute the installation command, the following error is prompted

fvm install 1.22.0

Error: no flutter version matched 1.22.0 !!

OS: Mac OS bigSu 11.1
fvm version :1.1.5

**Comment by leoafarias** [comment]
Can you update to latest version of fvm and try again?

**Comment by haibowen** [comment]
> Can you update to latest version of fvm and try again?
thanks  thanks
