### ISSUE TITLE
[BUG] RPC fail

### ISSUE THREAD

**Issue by tank777** [leoafarias/fvm#213]
```
Installing version: master
Cloning into '/Users/c140/fvm/versions/master'...
remote: Enumerating objects: 34, done.        
remote: Counting objects: 100% (34/34), done.        
remote: Compressing objects: 100% (28/28), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Internal Error: Could not install <master>
```
Is there any way that we can pass the git depth command?
Reference  : [https://stackoverflow.com/a/62079208/11714501](https://stackoverflow.com/a/62079208/11714501)

**Comment by GiovanniSM20** [comment]
This probably happened because as described in the StackOverflow problem you are trying to clone a rather large repository. I tried to repeat your problem and it only happens on slower connections running: ```fvm install master```. Have you tried running ```fvm install stable``` ?

**Comment by tank777** [comment]
@GiovanniSM20  Yes you are right, It only happens on slower connections. I am able to install both versions after a proper connection.

**Comment by leoafarias** [comment]
We are not able to set the depth on fvm for issues referenced on the PR. This causes issues with flutter tooling.

https://github.com/flutter/flutter/issues/32684
