### ISSUE TITLE
[BUG] flutter --version does not match with fvm list

### ISSUE THREAD

**Issue by stoneshower** [leoafarias/fvm#219]
I would like to confirm which flutter version I am using, as the title says there's a gap of output between the commands.

When I ran `flutter --version`, it shows

```
Flutter 1.20.3 • channel unknown • unknown source
Framework • revision 216dee60c0 (5 months ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

but when I ran `fvm list` it shows

```
1.26.0-17.3.pre ✔
```

As for 1.20.3 which shows by `flutter --version`, I used `flutter version 1.20.3` command not fvm.

**Comment by leoafarias** [comment]
@stoneshower did you run the flutter version change from within an fvm version? That will not cause it to urdiste the directory name.

There is a "version" file within that flutter version directory. Let me know what that version number is

**Comment by stoneshower** [comment]
@leoafarias 
Thanks for your response.

I ran `flutter version` before using fvm. I just started to use fvm and installed 1.26.0* with fvm use command.

In the file of .fvm > flutter_sdk > version, it has `1.26.0-17.3.pre`.

**Comment by stoneshower** [comment]
However, when I ran `flutter doctor`, it shows different version from fvm version.
```
[✓] Flutter (Channel unknown, 1.20.3, on macOS 11.2 20D64, locale ja-JP)
```

**Comment by leoafarias** [comment]
I think I understand the problem. The `flutter` command will run the flutter version you have configured in your environment, or `global` version. While the `fvm flutter` will look for a version configured on your project or a parent directory

**Comment by stoneshower** [comment]
I see. I'm wondering which version is actually used in this case? global one or fvm one?

**Comment by aquilarafa** [comment]
Same here. 
Inside a project configured for `1.24.0-10.2.pre` when I run `fvm list` gives me this:
```
Versions path:  /Users/aquila/fvm/versions
1.24.0-10.2.pre ✔
1.22.6 (global)
```
Any `flutter ...` command runs using the global one.
But if i use `fvm flutter ...` it runs using the project version.

The only way I found for running `flutter` without `fvm` inside a project is to not set any global version using fvm but install separately.

**Comment by leoafarias** [comment]
@aquilarafa might worth checking out https://github.com/leoafarias/fvm#use-a-sdk-version, there is a section about setting a global version, which allows you to set the PATH to that version so you can still switch within FVM.
