### ISSUE TITLE
fvm folder in the user directory is annoying

### ISSUE THREAD

**Issue by yurianxdev** [leoafarias/fvm#221]
Wouldn't be better to use a folder like `~/.fvm` instead of `fvm`, for me is really annoying having that folder unhidden

**Comment by leoafarias** [comment]
This was done by design so the user is aware of fvm, and that there could be versions installed in that directory. Follows the same as default flutter documentation suggest for flutter itself so this is just duplicated

**Comment by yurianxdev** [comment]
But you can export the flutter bin wherever you want. With the dart-tool this is difficult

**Comment by kuhnroyal** [comment]
Isn't `FVM_HOME` env variable meant to configure that?

**Comment by yurianxdev** [comment]
I've just tested it. It worked fine, thanks!
