### ISSUE TITLE
How can I change the specific version of channel by fvm

### ISSUE THREAD

**Issue by panchalAlpit** [leoafarias/fvm#224]
I want to switch the beta version 1.20.2. so I did install the version(1.20.2). but when I see the flutter details so the channel is unknown. So I want to know the this is an issue or it will work perfectly. because after this I don't know which channel(beta, stable) is used.

Thanks
 
![Screenshot 2021-02-20 at 4 16 31 PM](https://user-images.githubusercontent.com/48007084/108593189-5bf5f100-7398-11eb-838b-182af7b18de6.png)

**Comment by leoafarias** [comment]
@panchalAlpit This should work just fine. Normally I would compare this with the `flutter version` command however they have deprecated it.  This piece is very straightforward. I will go ahead and close this issue because I am doing some clean-up. but feel free to reopen in case you see any issues.
