### ISSUE TITLE
Vscode not shown fvm sdk installed

### ISSUE THREAD

**Issue by tazik561** [leoafarias/fvm#225]
I installed FVM on windows 10. After installing specific version of flutter sdk :
```
 fvm list
Versions path:  C:\Users\tazik\fvm\versions
stable ✔ (global)
1.24.0-10.2.pre
```
On vs code I added :
`"dart.flutterSdkPaths": [".fvm/flutter_sdk"],`

inside **setting.json**. I run` fvm use stable` in my flutter project and **.fvm folder** created inside project. But When I want to select specific **sdk(stable)** by **vscode** an run ` Dart:Change SDK` , none of fvm sdk not showing in the vscode list???

```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```
https://pasteboard.co/JPkrmSR.png

**Comment by lsalehar** [comment]
I have followed the official docs on how to set up Visual Studio Code to use fvm however, I can't seem to get it working. I only have fvm installed and no standalone flutter versions

Output `fvm list`
```
stable
1.26.0-17.1.pre
1.26.0-1.0.pre
1.25.0-4.0.pre
```

**Comment by leoafarias** [comment]
@tazik561 The path, if you want to display all the versions, should be the path to the versions directory within fvm. 

According to this section https://github.com/leoafarias/fvm#list-all-versions-installed-by-fvm, let me know if you suggest any improvements.

@lsalehar If you followed the instructions above I suggest after doing the configuration for you to close the IDE an open it again

**Comment by lsalehar** [comment]
@leoafarias Hey thank you for the advice, I did that, but it didn't work. Somehow, I managed to get it working, but I don't know what I did. I was in a hurry and didn't write things down. 🙂
