### ISSUE TITLE
Unable to Install Flutter Version

### ISSUE THREAD

**Issue by searchy2** [leoafarias/fvm#23]
Hi @leoafarias,

Thank you so much for making this tool! I am spending a lot of time switching Dart versions and testing for compatibility so this tool will make that much simpler.

Unfortunately, I am unable to instal a flutter version. I've tried `fvm install 1.7.8+hotfix.4` but it said it could not find the version. I also tried `fvm install v1.7.8+hotfix.4` which didn't work either.

Here's the error log:
```
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: git ls-remote --tags https://github.com/flutter/flutter.git
#0      flutterListAllSdks (package:fvm/utils/flutter_tools.dart:104:7)
<asynchronous suspension>
#1      isValidFlutterVersion (package:fvm/utils/helpers.dart:8:17)
<asynchronous suspension>
#2      flutterVersionClone (package:fvm/utils/flutter_tools.dart:51:14)
<asynchronous suspension>
#3      InstallCommand.run (package:fvm/commands/install.dart:27:15)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#6      new Future.sync (dart:async/future.dart:224:31)
#7      CommandRunner.run (package:args/command_runner.dart:112:14)
#8      fvmRunner (package:fvm/fvm.dart:34:23)
<asynchronous suspension>
#9      main (file:///C:/Users/Laptop/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-0.6.1/bin/main.dart:4:9)
<asynchronous suspension>
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Downloading 1.7.8+hotfix.4...
CreateProcessW failed 2
⚠️  The system cannot find the file specified.
```

**Comment by leoafarias** [comment]
@searchy2 The command seems to be working just fine. What OS and version are you running it on?

**Comment by searchy2** [comment]
I'm running FVM on Windows 10. Perhaps that's the issue? 

Thanks for taking a look!

**Comment by leoafarias** [comment]
I think I might know what the issue is. Will just have to figure out how to test.

**Comment by searchy2** [comment]
![MaxthonSnap20191017115645](https://user-images.githubusercontent.com/19896174/67030559-45b99000-f0d5-11e9-864e-cf03ea658d9d.png)
Let me try testing with a later build of Flutter and report back.

**Comment by leoafarias** [comment]
@searchy2 I wonder if it has something to do with the following issue https://github.com/flutter/flutter/pull/37906

**Comment by searchy2** [comment]
I switched to a supported Dart version and the original issue now appears. 

For your linked issue, I am using Add to app but with Android at the moment.

**Comment by leoafarias** [comment]
@searchy2 was able to replicate the issue. It seems you don't have `git` installed. I have added better error handling and a link to install it.

**Comment by yaowei103** [comment]
I want to change the flutter version from 3.19.2 to 3.24.0,  win10, run fvm list, error log below: 

PS E:\Demos\demo> fvm list
Can't load Kernel binary: Invalid kernel binary format version.
Building package executable... (2.7s)
Failed to build fvm:main:
/C:/Users/ActionPower/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/win32-5.5.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/ActionPower/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/win32-5.5.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/ActionPower/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/win32-5.5.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(guid));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/ActionPower/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/win32-5.5.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
  factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/ActionPower/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/win32-5.5.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
