### ISSUE TITLE
[BUG] "build macos" is not currently supported.

### ISSUE THREAD

**Issue by Bazni** [leoafarias/fvm#230]
**Describe the bug**
Hi,

I try to run the fvm gui on Macos, I downloaded the fvm source and tried to run a "flutter build macos and I get the error "build macos" is not currently supported".

I got the same problem with the 1.3.7 release.

Is there a way to get the gui mac os ?

**To Reproduce**
1. Download fvm source
2. go to packages/app/
3. run `flutter pub get`
4. run `flutter build macos`

**Logs**
(don't know how to share readable log)
<details>
<summary> 
$ fvm flutter build macos -->
"build macos" is not currently supported.
</summary>
`
$ fvm flutter build macos --verbose
Can't load Kernel binary: Invalid kernel binary format version.
[  +73 ms] executing: [/Users/gwendalbazin/fvm/versions/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[        ] executing: [/Users/gwendalbazin/fvm/versions/stable/] git tag --points-at 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[  +17 ms] Exit code 0 from: git tag --points-at 60bd88df915880d23877bfc1602e8ddcf4c4dd2a
[        ] 2.0.0
[  +43 ms] executing: [/Users/gwendalbazin/fvm/versions/stable/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/gwendalbazin/fvm/versions/stable/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/Users/gwendalbazin/fvm/versions/stable/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +5 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +13 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.3
[        ] executing: sw_vers -buildVersion
[  +13 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20E5186d
[   +6 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[  +40 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +53 ms] Skipping pub get: version match.
[  +13 ms] Found plugin window_size at /Users/gwendalbazin/.pub-cache/git/flutter-desktop-embedding-7812516a5c1fc8ef379e244106953a2b534432b9/plugins/window_size/
[  +41 ms] Found plugin file_chooser at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/file_chooser-0.1.6/
[  +29 ms] Found plugin path_provider at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[   +1 ms] Found plugin path_provider_linux at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[   +1 ms] Found plugin path_provider_windows at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[  +14 ms] Found plugin sqflite at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+4/
[   +6 ms] Found plugin url_launcher at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[        ] Found plugin url_launcher_linux at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[        ] Found plugin url_launcher_macos at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +1 ms] Found plugin url_launcher_web at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[   +1 ms] Found plugin url_launcher_windows at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[  +73 ms] Found plugin window_size at /Users/gwendalbazin/.pub-cache/git/flutter-desktop-embedding-7812516a5c1fc8ef379e244106953a2b534432b9/plugins/window_size/
[  +19 ms] Found plugin file_chooser at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/file_chooser-0.1.6/
[  +16 ms] Found plugin path_provider at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.27/
[        ] Found plugin path_provider_linux at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-0.0.1+2/
[        ] Found plugin path_provider_macos at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4+8/
[        ] Found plugin path_provider_windows at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-0.0.4+3/
[   +7 ms] Found plugin sqflite at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/sqflite-1.3.2+4/
[   +5 ms] Found plugin url_launcher at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.7.10/
[        ] Found plugin url_launcher_linux at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-0.0.1+4/
[        ] Found plugin url_launcher_macos at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+9/
[   +1 ms] Found plugin url_launcher_web at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.5+3/
[        ] Found plugin url_launcher_windows at /Users/gwendalbazin/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-0.0.1+3/
[  +16 ms] Generating /Users/gwendalbazin/fvm/fvm/packages/app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +26 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +111 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.4
           Build version 12D4e
[  +61 ms] "flutter macos" took 579ms.
[   +3 ms] "build macos" is not currently supported.
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:45:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>

[ +136 ms] ensureAnalyticsSent: 135ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
`
</details>

**Desktop (please complete the following information):**
 - OS: MacOs Big Sur version beta 11.3 (20E5186d)
 - FVM Version 1.3.7

**Additional context**
I use #211 issue to fix `flutter pub get` errors

**Comment by Bazni** [comment]
For those who are wondering how to get the GUI without building from project sources just go here: https://github.com/leoafarias/fvm/releases/tag/App-1.0.0-alpha.1

**Comment by leoafarias** [comment]
@Bazni make sure you are using flutter sdk version that does support desktop and you have enabled it on the config
