### ISSUE TITLE
[BUG] Can't pass args through flutter pub

### ISSUE THREAD

**Issue by Ascenio** [leoafarias/fvm#232]
**Describe the bug**
Can't check if a project has dependencies to migrate to null-safety through fvm.
```sh
$ fvm pub outdated --mode=null-safety
Could not find an option named "mode".

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Set configuration for FVM
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.
```

**To Reproduce**
1. Open a project workspace
2. Run `fvm use stable`
3. Run `fvm flutter upgrade` (such that you get to 1.22)
3. Run `fvm pub outdated --mode=null-safety`

**Expected behavior**
I expected to see something like this:
![](https://dart.dev/null-safety/pub-outdated-output.png)

**Logs**
[ +119 ms] Could not find an option named "mode".

[  +12 ms] Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
[   +6 ms] executing: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 128 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fatal: not a git repository (or any parent up to mount point /)
           Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[   +1 ms] executing: git tag --points-at HEAD
[   +6 ms] Exit code 128 from: git tag --points-at HEAD
[        ] fatal: not a git repository (or any parent up to mount point /)
           Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[   +2 ms] executing: git describe --match *.*.* --first-parent --long --tags
[   +5 ms] Exit code 128 from: git describe --match *.*.* --first-parent --long --tags
[        ] fatal: not a git repository (or any parent up to mount point /)
           Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[   +4 ms] Could not interpret results of "git describe":
[   +1 ms] executing: git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 128 from: git rev-parse --abbrev-ref HEAD
[        ] fatal: not a git repository (or any parent up to mount point /)
           Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[   +2 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +4 ms] exiting with code 64

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - FVM Version: 1.3.7

**Comment by leoafarias** [comment]
@Ascenio the command `fvm pub` does not exist. You want to runt `fvm flutter pub`

**Comment by Ascenio** [comment]
Oh, initially I thought it was a typo and I meant to say `fvm flutter pub`, but then I tested it again to make sure it wasn't working but It is. Life is strange sometimes. Thanks.

**Comment by leoafarias** [comment]
@Ascenio that is the life we chose ;)
