### ISSUE TITLE
fvm support switch dart version 

### ISSUE THREAD

**Issue by oncealong** [leoafarias/fvm#234]
`fvm flutter` is a good job, as it `Proxies Flutter Commands`.
Can you supplay a new command `fvm dart`, which `Proxies Dart Commands`.  

as I use `fvm use 2.0.0`, I also want to use corresponding dart version

**Comment by leoafarias** [comment]
@oncealong can you provide some examples of the commands you need?

**Comment by Kavantix** [comment]
Examples are:
```sh
#dart and flutter
dart migrate
dart fix —apply
#for command line tools
dart run
dart create
dart analyze
dart test
```

**Comment by leoafarias** [comment]
I will focus more on the use cases for flutter, as FVM use for managing dart would fall outside of the scope. I will go ahead and add this to the backlog so I can revisit it soon.

**Comment by leoafarias** [comment]
@Kavantix yes, just make sure you do the PR from the `next` branch
