### ISSUE TITLE
ADD support for project specific .flutter_settings files 

### ISSUE THREAD

**Issue by allanlaal** [leoafarias/fvm#235]
currently **all** flutter projects share ~/.flutter_settings

fvm flutter config should read/write to project_dir/.fvm/.flutter_settings and use only that file

**Comment by leoafarias** [comment]
I will go ahead and close this based on the response from the Flutter core team.

**Comment by allanlaal** [comment]
@leoafarias since this was denied in flutter core, would it be useful to add this to fvm instead? (being the more multi-project approach to developing flutter)

my original proposal:
-------------------------------
currently `flutter config` writes its settings to a globally shared ~/.flutter_settings file

## Use case

I have Flutter projects A, B,... 
all of them have different platforms supported (some platforms are disabled for various reasons) 

`flutter create --platforms=android,ios project_A` 
`flutter create --platforms=web,linux project_B`
`flutter config --no-enable-web`

and now if I cd into project_B and run `flutter build web` I get:
`"build web" is not currently supported.`
even though it was enabled for project_B on creation and it has its project_B/web folder



## Proposal

`$HOME/.flutter_settings` should continue being the default source for settings if they are not overridden by command line flags. 
`flutter create` should make a `$PROJECT_DIR/.flutter_settings` file based on flutter create (in this case `project_A/.flutter_settings` and ` project_B/.flutter_settings`)
..and all following flutter commands should use `$PROJECT_DIR/.flutter_settings` (falling back to `$HOME/.flutter_settings`)

`flutter config` changes ran in a $PROJECT_DIR should be saved to $PROJECT_DIR/.flutter_settings
`flutter config` changes ran outside of project dirs should be saved to `$HOME/.flutter_settings` (with a warning that the changes are global)

**Comment by leoafarias** [comment]
@allanlaal thank you for the detailed proposal. I am not sure if this should be solved with fvm. Seems this is a critical part of the tooling. 

I will do a bit of research on the settings however I haven't really stumbled upon this problem. I don't use web heavily mostly desktop and mobile. 

Will leave it open also to take a look at the source code for flutter_tools maybe there is a simple pull request to achieve this.

**Comment by leoafarias** [comment]
@allanlaal I did a bit of research and it seems that this is simple to implement but might have an impact on tooling as probably this is where the flutter team will keep track of feature flags.

I think in your case the correct behavior would be to have all platforms enabled, and after you create a project you can just remove the platforms you don't want. The flutter team made the same suggestion, as I think the flag only impacts the `create` command and it does not impact any other if you delete the platform directory.

Sorry about that, but seems a bit tricky to tackle this as it is part of the core Flutter tooling and normally I like to avoid those.

**Comment by leoafarias** [comment]
I will go ahead close this. Feel free to open it again if you feel like something is missing.

**Comment by allanlaal** [comment]
while I understand Flutter core teams reluctance, fvm is a tool that extends Flutter development to support multiple projects (apparently an edge case 🤣)

fvm proxies all flutter commands anyway, why not add a file change listener to that `~/.flutter_settings`  file when executing (any or config changing) commands.

if a local `.fvm/.flutter_settings `is missing, it will copy it from the general `~/.flutter_settings`  file

if `~/.flutter_settings` changes in the meanwhile, the next execution of fvm will add missing config options, but will never override existing local config options from from global.

**Comment by leoafarias** [comment]
@allanlaal I understand, I feel however that this falls outside of the scope of managing Flutter versions, and I think it adds a lot of complexity to FVM... not sure.

However... Sidekick https://github.com/leoafarias/sidekick currently has a function to view the Flutter settings and edit them. Triggering this on create might not be difficult, but maybe that is the best place for that.
