### ISSUE TITLE
Info for IDE config

### ISSUE THREAD

**Issue by blondie63** [leoafarias/fvm#236]
I think that informations to configure IDE are unclear
Some help?

**Comment by blondie63** [comment]
I read this: https://pub.dev/packages/fvm#configure-your-ide
but i don't understand which entry i've to add to VSCode/settings.json to use fvm cmds from IDE (VSCODE in my case)

**Comment by leoafarias** [comment]
@blondie63 when you run `fvm list` it will display the path to the versions directory. This is the path that you will use for this configuration

**Comment by joaovirgilicw** [comment]
> @blondie63 when you run `fvm list` it will display the path to the versions directory. This is the path that you will use for this configuration

Nice! I was in trouble too, it worked for me
