### ISSUE TITLE
Call for contributors

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/fvm#238]
Hi everyone,

It has been great to see FVM become a must-have tool for Flutter developers. Due to the limited time, I have been able to focus on addressing high-priority items. Still, I would like to focus more on the quality of experience improvements and a stable GUI version that I plan to separate from this repo. You can follow the progress of this work here #237

Ideally, I would like to have a maintainer to focus on specific platforms. I believe Windows is the most used OS for Flutter development, and the announcement from Ubuntu puts Linux front and center. Even though dart does an amazing job with cross platforms, sometimes user-specific setups and OS can cause different behaviors.

I am looking for maintainers that can help with the following.
- Improving documentation
- Responding to platform-specific issues
- Development and DevX improvements
- Work on GUI for platform-specific functionality.
- Distribute native binaries for all platforms (homebrew, chocolatey, etc.) (In Progress)

I don't think there is a lot of work that needs to be done; it's more about focus and providing the attention to each platform it deserves.

If you are interested in becoming a maintainer and helping with the project, please leave a comment below and which areas you think you could help.

Thank you again for everyone's help and support.

**Comment by jascodes** [comment]
I might chip in maintaining homebrew or chocolatey...

**Comment by SebastianKlaiber** [comment]
Development

**Comment by eliasreis54** [comment]
i could help in development and responding some issues.

**Comment by lParanhos** [comment]
Development

**Comment by Albert221** [comment]
Did you maybe consider setting up GitHub Sponsors, Open Collective account or something similar that could enable you to spend your valuable time on fvm? :)

**Comment by awhitford** [comment]
Is Google interested in folding this into the Flutter dev stack?  Because it seems like something valuable to them.

**Comment by leoafarias** [comment]
Update for everyone. I have tagged the issues that I might need some assistance with. These are issues that I have had difficulty debugging or might be happening on other platforms. 
`Go here to filter these issues`
https://github.com/leoafarias/fvm/labels/help%20wanted

Also, I have moved the App to a different repo. https://github.com/leoafarias/sidekick, so if you want to help out on that project, you can create an issue there. I am looking for people that can help on the automation for Linux and Windows especially.

**Comment by leoafarias** [comment]
In case anyone is wondering. FVM is more active than e we. Just want to make sure all platforms are getting the same amount of love.
