### ISSUE TITLE
How I can install a previous version from channel dev?

### ISSUE THREAD

**Issue by jamescardona11** [leoafarias/fvm#241]
Hi, everyone.

I want to install a previous version of DEV Channel, how I can do that ?

For example this: 1.26.0-1.0.pre in dev channel

thanks.

**Comment by leoafarias** [comment]
@jamescardona11 the best way is to pin the version directly `fvm install 1.26.0-1.0.pre`. Flutter has a downgrade command also that you could use within a channel like `fvm flutter downgrade`
