### ISSUE TITLE
How to set correct path for FVM

### ISSUE THREAD

**Issue by nik-v-hax** [leoafarias/fvm#243]
Hey not a bug but not a feature request either ...

fvm gave me this warning:

Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/niklasvonhaxthausen/fvm/versions/1.17.0
  previous reference  : /Users/niklasvonhaxthausen/Desktop/dev/SDK/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

have you got any straight forward solution to make it manage the flutter sdk rather than existing inside home directory?

**Comment by leoafarias** [comment]
@nik-v-hax Sorry I am not sure I understand your question. This is a notification warning when the path of Flutter changes as more of "FYI". I am not sure I understanding your question.

**Comment by nik-v-hax** [comment]
Hey sorry if I was unclear but this does not change the Flutter SDK with which I am running
<img width="525" alt="Screenshot 2021-03-24 at 13 35 24" src="https://user-images.githubusercontent.com/42723242/112311244-cbb41000-8ca5-11eb-9692-d1f185d11e69.png">

**Comment by nik-v-hax** [comment]
Means whatever I set within fvm does not have an affect when running a Flutter app - it just picks up 2.0.3 up again instead of the installed ones (1.22.5, 1.17.0)

**Comment by leoafarias** [comment]
@nik-v-hax The `flutter` command uses the PATH variable. There is a way to change that to allow for fvm to change versions. You can look at it on this link https://github.com/leoafarias/fvm#use-a-sdk-version.

However, you can also just do `fvm flutter ....` that will run the flutter version that has been pinned within the project. Let me know if that clarifies

**Comment by leoafarias** [comment]
Will go ahead and close this issue. Let me know if there are any other questions.
