### ISSUE TITLE
[BUG] New global command

### ISSUE THREAD

**Issue by davidmartos96** [leoafarias/fvm#248]
@leoafarias Hello! I'm trying out the new prerelease version for fvm on Linux, in particular the new `global` command.
I think I have the PATH correctly configured but fvm it's giving me the new warning:

![image](https://user-images.githubusercontent.com/22084723/113017493-c9f3bc00-917f-11eb-9904-caa81641476f.png)

Maybe the issue is that `which` is taking into account the binary name?
Something like changing the equals to:  
```dart
path.join(kGlobalFlutterPath, 'flutter') == await which('flutter') 
```  

```dart
  static Future<bool> isGlobalConfigured() async {
    /// Return false if link does not exist
    if (!await kGlobalFlutterLink.exists()) return false;
    return kGlobalFlutterPath == await which('flutter');
  }
```

**Comment by leoafarias** [comment]
@davidmartos96 You are right. Let me know if you want to do a PR with that fix, or I can do it later.

**Comment by leoafarias** [comment]
@davidmartos96 thank you!
