### ISSUE TITLE
Alpine container image for fvm

### ISSUE THREAD

**Issue by taras** [leoafarias/fvm#251]
Related https://github.com/dart-lang/dart_docker/issues/50

**Is your feature request related to a problem? Please describe.**

`google/dart` container images have a shocking number of [CVEs](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures). I generated a [report](https://gist.github.com/taras/0fc12a37bd23bd7d4572fd140b61cb39) using [trivy](https://github.com/aquasecurity/trivy) on `leoafarias/fvm` and trivy reported `3 CRITICAL` and `38 HIGH`. 

**Describe the solution you'd like**

Alpine images tend to have fewer CVEs. An Alpine image using FVM to install Flutter would be 👌 

**Describe alternatives you've considered**

There is a [container image for Flutter by CirrusCI](https://github.com/cirruslabs/docker-images-flutter/blob/master/sdk/Dockerfile) but it installs Dart as part of Flutter installation. All instructions for installing Dart expect a Debian distribution with `apt-get`. I can't seem to find how to install Dart on Alpine.

**Additional context**

Our IT blocks images that have HIGH and CRITICAL CVEs older than 30 days.

**Comment by leoafarias** [comment]
@taras The container example from CirrusCI you provided does not seem to be installing Dart, but uses the dart version configured within Flutter. This seems like it would do the trick as you don't need to install Dart separately.

**Comment by leoafarias** [comment]
@andreadelfante Do you want to give this a try?

Starting with version 2.0 which is in dev, we will make an executable available.

https://github.com/leoafarias/fvm/releases/download/2.0.0-dev.3/fvm-2.0.0-dev.3-linux-x64.tar.gz

In theory, we could do something like:

```docker
ADD https://github.com/leoafarias/fvm/releases/download/${FVM_VERSION}/fvm-${FVM_VERSION}-linux-x64.tar.gz destination
```

**Comment by taras** [comment]
@leoafarias did you mean @taras?

**Comment by leoafarias** [comment]
@andreadelfante was the person that created the docker file

**Comment by taras** [comment]
@leoafarias I tried it and it worked :)

```dockerfile
FROM alpine:3.13

ARG FLUTTER_VERSION=1.22.6
LABEL VERSION=1.22.6

# source: https://github.com/mindrunner/docker-android-sdk/blob/master/alpine/standalone/Dockerfile
USER root

ARG GLIBC_VERSION="2.28-r0"

ENV ANDROID_SDK_HOME /opt/android-sdk-linux
ENV ANDROID_SDK_ROOT /opt/android-sdk-linux
ENV ANDROID_HOME /opt/android-sdk-linux
ENV ANDROID_SDK /opt/android-sdk-linux
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk

# Install Required Tools
RUN apk -U update && apk -U add \
  bash \
  ca-certificates \
  curl \
  expect \
  fontconfig \
  git \
  make \
  libstdc++ \
  libgcc \
  mesa-dev \
  nodejs \
  npm \
  openjdk8 \
  pulseaudio-dev \
  su-exec \
  ncurses \
  unzip \
  wget \
  zlib \
  && wget https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -O /etc/apk/keys/sgerrand.rsa.pub \
	&& wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk -O /tmp/glibc.apk \
	&& wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk -O /tmp/glibc-bin.apk \
	&& apk add /tmp/glibc.apk /tmp/glibc-bin.apk \
  && rm -rf /tmp/* \
	&& rm -rf /var/cache/apk/*

# Create android User
RUN mkdir -p /opt/android-sdk-linux \
  && addgroup android \
  && adduser android -D -G android -h /opt/android-sdk-linux -u 1001

# Copy Tools
COPY docker-android-sdk/tools /opt/tools

# Copy Licenses
COPY docker-android-sdk/licenses /opt/licenses

# Working Directory
WORKDIR /opt/android-sdk-linux

RUN /opt/tools/entrypoint.sh built-in

RUN wget https://github.com/leoafarias/fvm/releases/download/2.0.0-dev.3/fvm-2.0.0-dev.3-linux-x64.tar.gz \
  && tar -xf fvm-2.0.0-dev.3-linux-x64.tar.gz

ENV PATH="${ANDROID_SDK_HOME}/fvm:/root/fvm/default/bin:/root/.pub-cache/bin:${PATH}"

RUN fvm install ${FLUTTER_VERSION} \
  && fvm global ${FLUTTER_VERSION} \
  && flutter pub global activate dartdoc \
  && dartdoc --version
```

This is what I'm using, but the following should work as well.

```dockerfile
FROM cirrusci/android-sdk:30

USER root

ARG FLUTTER_VERSION=1.22.6

RUN wget https://github.com/leoafarias/fvm/releases/download/2.0.0-dev.3/fvm-2.0.0-dev.3-linux-x64.tar.gz \
  && tar -xf fvm-2.0.0-dev.3-linux-x64.tar.gz

ENV PATH="${ANDROID_SDK_HOME}/fvm:/root/fvm/default/bin:/root/.pub-cache/bin:${PATH}"

RUN fvm install ${FLUTTER_VERSION} \
  && fvm global ${FLUTTER_VERSION} \
  && flutter pub global activate dartdoc \
  && dartdoc --version
```

**Comment by andreadelfante** [comment]
@taras This looks like good for me! Actually the current Dockerfile downloads Flutter sdk every time, and this isn't so efficient. 
Maybe we can parametrized your Dockerfile to build multiple image to push to Docker Hub.

@leoafarias  To achieve this, we should adapt the current CI/CD to build and push different Docker images.

**Comment by taras** [comment]
@andreadelfante I'm still working out the best way to configure this image for CI. The challenge is that `.fvm` directory comes from mounted workspace. I need to change `FVM_HOME` to that mounted directory so `fvm` will know where to retrieve config from. 

I believe NVM looks up `.nvm` config by traversing the parent directories which makes it a little easier.

**Comment by andreadelfante** [comment]
@taras `fvm config --cache-path <CACHE_PATH>` is the command you're looking for!

**Comment by taras** [comment]
Here is the smallest alpine image that I was able to create

```dockerfile
FROM ceresacr.azurecr.io/alpine:3.13

USER root

ARG FVM_VERSION="2.0.0-dev.6"
ARG GLIBC_VERSION="2.28-r0"

# Install Required Tools
RUN apk -U update && apk -U add \
  bash \
  ca-certificates \
  curl \
  git \
  make \
  libstdc++ \
  libgcc \
  mesa-dev \
  unzip \
  wget \
  zlib \
  && wget https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub -O /etc/apk/keys/sgerrand.rsa.pub \
	&& wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk -O /tmp/glibc.apk \
	&& wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk -O /tmp/glibc-bin.apk \
	&& apk add /tmp/glibc.apk /tmp/glibc-bin.apk \
  && rm -rf /tmp/* \
	&& rm -rf /var/cache/apk/*

WORKDIR /opt/flutter

ENV PATH=/opt/flutter/fvm:${PATH}

RUN wget https://github.com/leoafarias/fvm/releases/download/${FVM_VERSION}/fvm-${FVM_VERSION}-linux-x64.tar.gz \
  && tar -xf fvm-${FVM_VERSION}-linux-x64.tar.gz \
  && rm fvm-${FVM_VERSION}-linux-x64.tar.gz

RUN fvm --version
```

**Comment by leoafarias** [comment]
@taras Can you open a PR with this docker image?

**Comment by taras** [comment]
Sure. Do you want it to replace the current or add another one?

**Comment by leoafarias** [comment]
Add another one
