### ISSUE TITLE
[Feature Request] Support unofficial flutter version

### ISSUE THREAD

**Issue by franticn** [leoafarias/fvm#256]
First of all, thank you for providing such a convenient tool to help us to switch flutter env.We encountered the following problem during use `fvm`, because some reason, we use a internal flutter version, and connected to our internal flutter folder through a soft link under the `fvm/versions`folder,then we can use command `fvm list` to find our internal in flutter versions result;
```bash
$ fvm list
2.0.3 (global)
1.22.6
1.22.0-custom
```
But when i use command `fvm use 1.22.0-custom global`, it warning `1.22.0-custom is not a valid Flutter channel or release`,so could you please to add command like `fvm use 1.22.0-custom global --force` or `fvm use 1.22.0-custom global --unstable` , which will be skip valid flutter channel check?

**Comment by leoafarias** [comment]
@franticn is this a flutter fork? I will look a bit into this as adding flag is simple however just want to make sure there won’t be side effects on validation

**Comment by franticn** [comment]
> @franticn is this a flutter fork? I will look a bit into this as adding flag is simple however just want to make sure there won’t be side effects on validation

Yes, it's just a flutter fork

**Comment by leoafarias** [comment]
This has been merged for 2.0

**Comment by franticn** [comment]
@leoafarias Thanks!
