### ISSUE TITLE
fvm command not found in windows[BUG]

### ISSUE THREAD

**Issue by youssriaboelseod** [leoafarias/fvm#257]
hi leoafarias
thanks for your greate backage

i have this problem

fvm command not found 

i install pachage here
![image](https://user-images.githubusercontent.com/40850682/113477289-1a6d6100-9481-11eb-98af-76b13815e553.png)

and add it to path
![image](https://user-images.githubusercontent.com/40850682/113477314-35d86c00-9481-11eb-8d19-4d8ce37d4c16.png)

but its not work

notes : i run my vcod as adminstrator

**Comment by leoafarias** [comment]
@youssriaboelseod this seems to be a pub configuration. Did you restart the use and terminal after the config? Try running on a new shell

**Comment by leoafarias** [comment]
@youssriaboelseod I will go ahead and close this issue, since it’s configuration problem on pub and not fvm. But feel free to reopen if you think I am missing something.
