### ISSUE TITLE
Can I move the folder 'fvm' from my C: directory to D: directory

### ISSUE THREAD

**Issue by shantanugodbole** [leoafarias/fvm#261]
**Problem Point**
I am using FVM for the first time since I'm working on a couple of flutter projects which require different flutter versions.
On my device, I have very little space on my C: drive (the default download directory where FVM stores all the different flutter versions used) and I unable to shift the FVM file into another directory and then update its path in the environment paths.

![image](https://user-images.githubusercontent.com/46984743/113753551-da7dd680-972b-11eb-98fd-d52b5df6fbbc.png)

**Desired Update**
Is it possible that I can change the directory of the FVM folder so that in case I install around 10 different flutter versions, I can move it into a directory with more available space?

**Comment by leoafarias** [comment]
@shantanugodbole There are currently 2 ways of doing that and you can read about them here. https://github.com/leoafarias/fvm#change-fvm-cache-directory

**Comment by shantanugodbole** [comment]
Tried it, getting the following error message

![image](https://user-images.githubusercontent.com/46984743/113810603-3b3afc80-9788-11eb-8313-d1439bbd6dcd.png)

**Comment by shantanugodbole** [comment]
![image](https://user-images.githubusercontent.com/46984743/113812124-26ac3380-978b-11eb-9187-afe424730904.png)
another snapshot for reference

**Comment by leoafarias** [comment]
@shantanugodbole make sure you are running as administrator. If you are let me know as this might be a duplicate of this issue
https://github.com/leoafarias/fvm/issues/262

**Comment by shantanugodbole** [comment]
Hi Leo, yes I am running it as administrator

**Comment by leoafarias** [comment]
Follow the instruction on the thread mentioned aboce and install the latest dev version please

**Comment by shantanugodbole** [comment]
Tried that, issue still persists, which verbose command do you need?

**Comment by leoafarias** [comment]
`fvm use <version> --verbose`

**Comment by shantanugodbole** [comment]
Deleted all fvm files and activated fvm version 2.0.0-dev.4, working now 👍
