### ISSUE TITLE
[BUG]  On Windows FVM requires to run in developer mode or as an administrator

### ISSUE THREAD

**Issue by Nabouste** [leoafarias/fvm#262]
I ran fvm use stable on my root project but the terminal show me to run on administrator.

when i run in administrator (cmd) it still give the same error

![image](https://user-images.githubusercontent.com/29367624/113804145-29f1f000-9788-11eb-976a-5e7df7dd39ae.png)
![image](https://user-images.githubusercontent.com/29367624/113804181-3e35ed00-9788-11eb-884f-3cca8137c6fe.png)

**Comment by leoafarias** [comment]
@Nabouste please download the latest version I think that is fixed there. 

pub global activate fvm 2.0.0-dev.4

If the issue remains please run with the --verbose flag and give me the output

**Comment by leoafarias** [comment]
Closing this issue, feel free to reopen if the issue persists on the latest version

**Comment by vrajraj** [comment]
hey , i am error in latest version 2.13.0 while installing sdk  as: 

Installing version: 2.17.0...
Cloning into 'C:\Users\vrajrajsinh.gohil\fvm\versions\2.17.0'...
fatal: Remote branch 2.17.0 not found in upstream origin

Could not install 2.17.0
can you help me , what happening?

**Comment by leoafarias** [comment]
@vrajraj the error mentions version 2.17.0, but I checked the releases and version 2.17.0 and 2.13.0 do not seem to exist. Also this error is not related to this issue, if it persists please open a new issue

**Comment by ashurocks** [comment]
PS C:\Users\anant\StudioProjects\hsl_flutter-master_version_3_open_api> fvm install 2.10.4 --verbose
[     0.032s] Version: 2.10.4 - already installed.
[     0.109s] FileSystemException: Cannot create link to target 'C:\Users\anant\fvm\versions\2.10.4', path = 'C:\Users\anant\StudioProjects\hsl_flutter-master_version_3_open_api\.fvm\f
lutter_sdk' (OS Error: A required privilege is not held by the client.
, errno = 1314)
[     0.112s] Usage Exception: Seems you don't have the required permissions on C:\Users\anant\fvm On Windows FVM requires to run as an administrator or turn on developer mode: https:/
/bit.ly/3vxRr2M

Could not install 2.10.4

Please run command with  --verbose if you want more information


How do i solve this the url provided is broken.

**Comment by tcai2000** [comment]
@ashurocks You can watch this video https://www.youtube.com/watch?v=ayo4pefuYAY to enable dev mode on windows. 
I fixed successfully. Hope you too.
