### ISSUE TITLE
[BUG] fvm list throw FormatException

### ISSUE THREAD

**Issue by liaovq** [leoafarias/fvm#263]
Bug Describe: 
> fvm list
```
Unhandled exception:
FormatException: Not a properly formatted version string
#0      Version.parse (package:version/version.dart:172:7)
#1      _assignVersionWeight (package:fvm/src/local_versions/local_version.model.dart:47:18)
#2      LocalVersion.compareTo (package:fvm/src/local_versions/local_version.model.dart:16:26)
#3      LocalVersionRepo.getAll.<anonymous closure> (package:fvm/src/local_versions/local_version.repo.dart:48:42)
#4      Sort._insertionSort (dart:_internal/sort.dart:69:36)
#5      Sort._doSort (dart:_internal/sort.dart:58:7)
#6      Sort.sort (dart:_internal/sort.dart:33:5)
#7      ListMixin.sort (dart:collection/list.dart:355:10)
#8      LocalVersionRepo.getAll (package:fvm/src/local_versions/local_version.repo.dart:48:25)
<asynchronous suspension>
#9      ListCommand.run (package:fvm/src/commands/list_command.dart:25:21)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#11     FvmCommandRunner.run (package:fvm/src/runner.dart:60:14)
<asynchronous suspension>
#12     main (file:///Users/liao-dw/.pub-cache/hosted/http%2558%2547%254710.176.51.5%25588000/fvm-1.3.8/bin/main.dart:4:3)
<asynchronous suspension>
```

background: 
- OS: mac os 11.2.3
- FVM Version: 1.3.8
- zsh: 5.8
- i aready installed fvm using `pub global activate fvm` and It has been in normal use for some time
- `fvm flutter --version` can be used normally
```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (3 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```
- run `pub cache repair` get  this
```
Reactivating fvm 1.3.8...
Precompiling executables...
Failed to precompile fvm:main:
Error: Could not resolve the package 'fvm' in 'package:fvm/fvm.dart'.
.pub-cache/hosted/http%2558%2547%254710.176.51.5%25588000/fvm-1.3.8/bin/main.dart:1:8: Error: Not found: 'package:fvm/fvm.dart'
import 'package:fvm/fvm.dart';
       ^
.pub-cache/hosted/http%2558%2547%254710.176.51.5%25588000/fvm-1.3.8/bin/main.dart:4:9: Error: Method not found: 'FvmCommandRunner'.
  await FvmCommandRunner().run(args);
        ^^^^^^^^^^^^^^^^
Failed to reactivate fvm 1.3.8: Failed to precompile fvm:main:
Error: Could not resolve the package 'fvm' in 'package:fvm/fvm.dart'.
.pub-cache/hosted/http%2558%2547%254710.176.51.5%25588000/fvm-1.3.8/bin/main.dart:1:8: Error: Not found: 'package:fvm/fvm.dart'
import 'package:fvm/fvm.dart';
       ^
.pub-cache/hosted/http%2558%2547%254710.176.51.5%25588000/fvm-1.3.8/bin/main.dart:4:9: Error: Method not found: 'FvmCommandRunner'.
  await FvmCommandRunner().run(args);
        ^^^^^^^^^^^^^^^^
Binstubs exist for non-activated packages:
  From fvm: fvm
Failed to reactivate 1 package:
- fvm
```
- There are these files under my path `~/fvm/versions`
> 1.22.6
> 2.0.2
> stable

- `fvm use xxx` It works well in my project, So it does not affect the normal use of my local SDK
- and I don't know what I did that caused the problem

**Comment by leoafarias** [comment]
@liaovq I installed these versions and was not able to replicate the problem. The only way I have been able to replicate the problem, is if any of the versions has an space before or after...

**Comment by liaovq** [comment]
- Does the space you mentioned mean that the folder name under my ~/fvm/versions directory contains spaces
  - I checked all the names in the versions directory, none of them contain spaces
- Through your prompt, I tried to `fvm remove` all my local skd -> doesn't work
- Now I only have version 2.0.4 installed locally, `fvm list` will still run out of exception
- I try to `pub global deactivate fvm` and `pub global activate fvm` -> doesn't work
- I try to delete `fvm-1.3.8` in .pub-cache manually, Then install again -> doesn't work

**Comment by leoafarias** [comment]
A few questions:
- Are you using an FVM version globally? Meaning the "flutter" command points to a version within FVM?
- You mentioned using `pub global...` so you are not using `flutter pub global...` 
- Can you provide me the logs from the command `pub global activate fvm`?
- Can you provide me the configuration of your PATH for Flutter, pub and dart?

**Comment by liaovq** [comment]
I don't have an flutter sdk locally, I'm on a new computer [Install Dart](https://dart.dev/get-dart), then `pub global activate fvm` and use it
So I don't have a `flutter xxx` command

- PATH configuration Related to the Flutter, pub and dart
```
export PATH="$PATH":"$HOME/.pub-cache/bin"
export PUB_HOSTED_URL='my private library address'
# export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
```
- `pub global activate fvm --verbose` logs are too long, so I only intercepted the last part, I don't know if they're useful
```
IO  : Finished /usr/local/Cellar/dart/2.12.1/libexec/bin/dart. Exit code 0.
    | stdout:
    | | Info: Compiling without sound null safety
    | Nothing output on stderr.
MSG : Precompiled fvm:main.
FINE: Precompiling executables finished (2.689s).
IO  : Writing 592 characters to text file /Users/liao-dw/.pub-cache/bin/fvm.
FINE: Contents:
    | #!/usr/bin/env sh
    | # This file was created by pub v2.12.1.
    | # Package: fvm
    | # Version: 1.3.8
    | # Executable: fvm
    | # Script: main
    | if [ -f /Users/liao-dw/.pub-cache/global_packages/fvm/bin/main.dart-2.12.1.snapshot ]; then
    |   dart "/Users/liao-dw/.pub-cache/global_packages/fvm/bin/main.dart-2.12.1.snapshot" "$@"
    |   # The VM exits with code 253 if the snapshot version is out-of-date.
    |   # If it is, we need to delete it and run "pub global" manually.
    |   exit_code=$?
    |   if [ $exit_code != 253 ]; then
    |     exit $exit_code
    |   fi
    |   pub global run fvm:main "$@"
    | else
    |   pub global run fvm:main "$@"
    | fi
    |
MSG : Installed executable fvm.
IO  : Spawning "command -v fvm" in /Users/liao-dw/.
IO  : Finished command. Exit code 0.
    | stdout:
    | | /Users/liao-dw/.pub-cache/bin/fvm
    | Nothing output on stderr.
MSG : Activated fvm 1.3.8.
```

**Comment by leoafarias** [comment]
There are 2 possible problems. 
- There is an issue with the dependency you are getting from your hosted pub. I would suggest removing that and trying the official one directly. If the issue persist I think I can try to see what could be happening.
- The version check on FVM does rely on `FLUTTER_STORAGE_BASE_URL` so I wonder if some data there is coming from there is not correct.

**Comment by liaovq** [comment]
- I commented out all the `PUB_HOSTED_URL` and `FLUTTER_STORAGE_BASE_URL` in my .zshrc (use official)
- `fvm remove` all sdk
- `rm rf ~/fvm`
- `pub global deactivate fvm`
- restart iTerm2
- `pub global activate fvm`
- `fvm install 2.0.4`
- `fvm list`
- 🎉 It worked 🎉
- Thank you very much
- Thank you for such a great tool
