### ISSUE TITLE
[Question] How do i run dartdoc 

### ISSUE THREAD

**Issue by iampato** [leoafarias/fvm#264]
keeping in mind the above commands need flutter tools

**Comment by leoafarias** [comment]
You should be able to use `dartdoc` on your terminal assuming you installed through `pub global activate fvm`. Let me know a bit about your setup

**Comment by iampato** [comment]
Steps done: 
1. ran `pub global activate fvm`
    The output
    ```
    Package fvm is currently active at version 1.3.8.
    Resolving dependencies... (8.7s)
   The package fvm is already activated at newest available version.
   To recompile executables, first run `global decativate fvm`.
   Installed executable fvm.
   Activated fvm 1.3.8.
    ```
2. ran `dartdoc`
    The output
 ```
   Documenting sip_native...

dartdoc failed: Top level package requires Flutter but FLUTTER_ROOT environment variable not set.
#0      PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:52:9)
#1      Dartdoc.generateDocsBase (package:dartdoc/dartdoc.dart:182:41)
#2      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:223:34)
#3      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:15)
#4      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:499:7)
#5      _rootRun (dart:async/zone.dart:1354:13)
#6      _CustomZone.run (dart:async/zone.dart:1258:19)
#7      _runZoned (dart:async/zone.dart:1788:10)
#8      runZonedGuarded (dart:async/zone.dart:1776:12)
#9      Dartdoc.executeGuarded (package:dartdoc/dartdoc.dart:498:5)
#10     main (file:///tmp/tmpTqI70l/dart-2.12.2/dart/third_party/pkg/dartdoc/bin/dartdoc.dart:26:11)
<asynchronous suspension>

```

**Comment by iampato** [comment]
@leoafarias  is there something i missed?

**Comment by leoafarias** [comment]
@iampato yes I believe you still should set a version of Flutter in the global path, so these commands can run. You can read it here. https://flutter.dev/docs/get-started/install/macos#update-your-path

**Comment by iampato** [comment]
I use Linux but thanks,
the issue will come if I want to `dartdoc` with a different flutter version I will need to update my global path
Anywau its okay

**Comment by abhaysood** [comment]
I ran into this issue too. When someone wants to use `dartdoc` it breaks a promise of `fvm`.
- It makes the user manage the global flutter versions when working in a project.
- Can lead to an inconsistency in the version used by `dartdoc`.

Is there a way to route this (& potentially similar) command via `fvm`? @leoafarias

**Comment by leoafarias** [comment]
All the dart commands are under `fvm dart` if dartdoc has its own separate command you would have to set Flutter as a global in the PATH env

**Comment by abhaysood** [comment]
Yeah I think there is not much FVM can do here. But this problem increases the number of steps needed to get things up and running on developer machines. I might evaluate using Makefile to wrap all the common commands up to take care of these details at some point.

Thanks for the quick replies!

**Comment by abhaysood** [comment]
Found a potential workaround for this to run via fvm. I'm not 100% sure if this is actually using fvm config or not. 
`fvm flutter pub global run dartdoc`

**Comment by leoafarias** [comment]
Yes anything that you add `fvm` will go through the fvm routing. You can read more about the order here.
https://fvm.app/docs/guides/running_flutter#routing
