### ISSUE TITLE
Could not find a command named "config"

### ISSUE THREAD

**Issue by helloworld10010** [leoafarias/fvm#265]
**Before creating a bug report please make check the following**
- You have installed fvm using `pub global activate fvm` not `flutter pub...`
- If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions when using the `fvm use <version>` command.

**Describe the bug**
 Could not find a command named "config".

**To Reproduce**
1. Go to terminal..
2. Run `fvm config`...
3. Check...

**Expected behavior**
config list.

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - FVM Version 1.2.3
 - If Windows: Which Powershell are you using?  YES

**Additional context**
I want to change the default directory of fvm

**Comment by leoafarias** [comment]
@helloworld10010 please update your version and let me know if the issue persists

**Comment by msarkrish** [comment]
@leoafarias I already installed FVM 1.2.3. How to upgrade to the latest version?

**Comment by leoafarias** [comment]
`pub global activate fvm`

**Comment by msarkrish** [comment]
@leoafarias Not updating to latest version.
![fvm](https://user-images.githubusercontent.com/45334931/114974330-ce1e1a00-9e9f-11eb-83fa-a78d28006415.PNG)

**Comment by kuhnroyal** [comment]
You are probably running an old Dart version, update your Dart installation and then this should find a newer, compatible version.
