### ISSUE TITLE
[Feature Request] Installation of fvm is different if Flutter is installed as a snap package

### ISSUE THREAD

**Issue by Atalanttore** [leoafarias/fvm#267]
If Flutter is installed as a [snap package](https://snapcraft.io/flutter), the installation of `Flutter Version Management` is different from what is described in the [README.md](https://github.com/leoafarias/fvm/blob/master/README.md) file, because the direct invocation of `pub` is not supported in the snap.

**Describe the solution you'd like**
Users of Flutter's snap package must add the following lines to `~/.bashrc` so that `pub global activate fvm` can be used.
```
alias pub='dart pub'
export PATH=$PATH:$HOME/.pub-cache/bin
```

**Credits**
_Many thanks to @MarcusTomlinson for his troubleshooting, see [here](https://github.com/canonical/flutter-snap/issues/42)._

**Comment by leoafarias** [comment]
I have updated the new docs to explicit call out `dart pub global activate fvm`. I believe this would close the issue.
