### ISSUE TITLE
fvm use doesnot work for version that is shown by fvm list 

### ISSUE THREAD

**Issue by kcprabase** [leoafarias/fvm#269]
Hi,
I have two stable flutter versions installed 1.22.5 and 2.0.5
It is even listed when I run >fvm list
Currently, I am on 2.0.5. But when I run > fvm use 1.22.5, it says could not install <1.22.5>
![image](https://user-images.githubusercontent.com/33727948/115152965-3b45d100-a093-11eb-812d-58436457dc30.png)

Am I doing something wrong?

Thanks

**Comment by leoafarias** [comment]
Can you run with —verbose. You have to make sure you run in administrator mode or turn on developer mode on windows.

**Comment by kcprabase** [comment]
I am on Developer mode. And I am now running CLI as Administrator.
>fvm use 1.22.5 --verbose gives me the following logs
![image](https://user-images.githubusercontent.com/33727948/115153719-20755b80-a097-11eb-8c42-5d82f1e52d8e.png)

**Comment by leoafarias** [comment]
I am not sure but it seems that the cli does not have write access to the projects directory

**Comment by leoafarias** [comment]
@kcprabase I will go ahead and close this issue. please let me know if there is anything else I can be of assistance
