### ISSUE TITLE
NoSuchMethodError: The method 'cast' was called on null. Receiver: null Tried calling: cast() while using all fvm commands

### ISSUE THREAD

**Issue by msarkrish** [leoafarias/fvm#270]
**Before creating a bug report please make check the following**
- You have installed fvm using `pub global activate fvm` not `flutter pub...`
      Yes I have installed fvm using `pub global activate fvm`

- If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions when using the `fvm use <version>` command.
   This command also not working.

**Describe the bug**

All fvm commands giving this error

NoSuchMethodError: The method 'cast' was called on null.
Receiver: null
Tried calling: cast<String>()

**To Reproduce**
1. Go to terminal..
2. Run `fvm use stable`...
3. Check...

**Expected behavior**
Stable version selected message shown

**Logs**
NoSuchMethodError: The method 'cast' was called on null.
Receiver: null
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new Settings.fromMap (package:fvm/src/utils/settings.dart:33:61)
#2      new Settings.fromJson (package:fvm/src/utils/settings.dart:26:21)
#3      Settings.readSync (package:fvm/src/utils/settings.dart:65:23)
#4      kVersionsDir (package:fvm/constants.dart:39:29)
#5      LocalVersionRepo.isInstalled (package:fvm/src/local_versions/local_versi
on.repo.dart:66:39)
#6      UseCommand.run (package:fvm/src/commands/use_command.dart:72:55)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
112:25)
#9      new Future.sync (dart:async/future.dart:223:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     fvmRunner (package:fvm/src/runner.dart:35:18)
#12     main (file:///C:/Users/OM/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.
org/fvm-1.3.7/bin/main.dart:6:9)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:168:12)

Unhandled exception:
NoSuchMethodError: The method 'cast' was called on null.
Receiver: null
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new Settings.fromMap (package:fvm/src/utils/settings.dart:33:61)
#2      new Settings.fromJson (package:fvm/src/utils/settings.dart:26:21)
#3      Settings.readSync (package:fvm/src/utils/settings.dart:65:23)
#4      kVersionsDir (package:fvm/constants.dart:39:29)
#5      LocalVersionRepo.isInstalled (package:fvm/src/local_versions/local_versi
on.repo.dart:66:39)
#6      UseCommand.run (package:fvm/src/commands/use_command.dart:72:55)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
112:25)
#9      new Future.sync (dart:async/future.dart:223:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     fvmRunner (package:fvm/src/runner.dart:35:18)
#12     main (file:///C:/Users/OM/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.
org/fvm-1.3.7/bin/main.dart:6:9)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:168:12)
NoSuchMethodError: The method 'cast' was called on null.
Receiver: null
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new Settings.fromMap (package:fvm/src/utils/settings.dart:33:61)
#2      new Settings.fromJson (package:fvm/src/utils/settings.dart:26:21)
#3      Settings.readSync (package:fvm/src/utils/settings.dart:65:23)
#4      kVersionsDir (package:fvm/constants.dart:39:29)
#5      LocalVersionRepo.isInstalled (package:fvm/src/local_versions/local_versi
on.repo.dart:66:39)
#6      UseCommand.run (package:fvm/src/commands/use_command.dart:72:55)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
112:25)
#9      new Future.sync (dart:async/future.dart:223:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     fvmRunner (package:fvm/src/runner.dart:35:18)
#12     main (file:///C:/Users/OM/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.
org/fvm-1.3.7/bin/main.dart:6:9)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:168:12)

Unhandled exception:
NoSuchMethodError: The method 'cast' was called on null.
Receiver: null
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new Settings.fromMap (package:fvm/src/utils/settings.dart:33:61)
#2      new Settings.fromJson (package:fvm/src/utils/settings.dart:26:21)
#3      Settings.readSync (package:fvm/src/utils/settings.dart:65:23)
#4      kVersionsDir (package:fvm/constants.dart:39:29)
#5      LocalVersionRepo.isInstalled (package:fvm/src/local_versions/local_versi
on.repo.dart:66:39)
#6      UseCommand.run (package:fvm/src/commands/use_command.dart:72:55)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
112:25)
#9      new Future.sync (dart:async/future.dart:223:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     fvmRunner (package:fvm/src/runner.dart:35:18)
#12     main (file:///C:/Users/OM/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.
org/fvm-1.3.7/bin/main.dart:6:9)
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:299:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:168:12)

**Screenshots**
![image](https://user-images.githubusercontent.com/45334931/115219970-a5a75180-a125-11eb-8fe1-3026b447ed8a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - FVM Version: 1.3.7
 - If Windows: Which Powershell are you using?
       I tried with cmd

**Comment by msarkrish** [comment]
I can't upload settings file, so pasted the content of the settings file.
{
  "cachePath": null,
  "skipSetup": false,
  "gitCache": false
}

**Comment by msarkrish** [comment]
@leoafarias I have an old version of dart SDK, I will update dart SDK tomorrow and I will update the FVM to dev. Then I will update the Issue.

**Comment by leoafarias** [comment]
Thank you in the mean time @msarkrish remove the `cachePath` key from your settigns and that should do the trick.
```
{
"cachePath": null,
"skipSetup": false,
"gitCache": false
}
```

I believe this was a conflict between sidekick and fvm, because the new version of sidekick sets this.. so using the latest on dev will solve the problem
