### ISSUE TITLE
[Feature Request] Specify flutter commit on master channel

### ISSUE THREAD

**Issue by acoutts** [leoafarias/fvm#275]
**Is your feature request related to a problem? Please describe.**
Sometimes you need to lock your flutter version to a specific commit on master where there's no tag yet.

**Describe the solution you'd like**
We should be able to specify a commit hash as our flutter version.

**Describe alternatives you've considered**
There is no way to do this currently.

**Additional context**
N/A.

**Comment by leoafarias** [comment]
@acoutts this is your lucky day. It was just merged yesterday. ;)

I have made an adjustment to support regular and short hashes.

https://github.com/leoafarias/fvm/pull/268

**Comment by acoutts** [comment]
Fantastic!! It works.
