### ISSUE TITLE
[BUG] fvm list

### ISSUE THREAD

**Issue by tegarkurniawan** [leoafarias/fvm#279]
i write in terminal fvm list see error FormatException: Not a properly formatted version string only fvm list, fvm version 1.3.7

**Comment by leoafarias** [comment]
@tegarkurniawan The only time I have seen this was when a version within the list had a " " (space) in the version name. If the error persists please open the place where the versions are cached to see if there are any weird characters in the cache folder

**Comment by tegarkurniawan** [comment]
![image](https://user-images.githubusercontent.com/8655617/116499621-d2522a80-a8d6-11eb-8399-fd86003bf989.png)

my version has no spaces

**Comment by tegarkurniawan** [comment]
#SOLVED 

i set cache folder to folder version fvm fvm config --cache-path /Users/nameuser/fvm/versions
