### ISSUE TITLE
[BUG] I already have flutter installed and fvm list says no sdks installed

### ISSUE THREAD

**Issue by shriharip** [leoafarias/fvm#28]
**Describe the bug**
fvm list does not recognize the installed flutter version

I think this has to do with some env variables or PATH etc.

**To Reproduce**
1. Install flutter using the standard way mentioned on flutter.dev
2. install fvm following the installation guide
3. run fvm list
4. Returns ==> No SDKs have been installed yet.

flutter version 1.9 installed on the machine (Mac OS: Mojave)
flutter --version results in right version

fvm list --verbose : No detailed logs only outputs No SDKs installed

**Expected behavior**
Expect to see the installed version
Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (4 weeks ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  MacOS Mojave
 - FVM Version [e.g. 22] fvm 0.6.4

**Additional context**

**Comment by leoafarias** [comment]
@shriharip thanks for the detailed bug report. This is related to #21. Will take a more detailed look at it soon.

**Comment by leoafarias** [comment]
I added a more descriptive message. However would like to avoid touching the Flutter SDK as much as possible.
