### ISSUE TITLE
[BUG] fvm flutter run behavior change in 2.x

### ISSUE THREAD

**Issue by ened** [leoafarias/fvm#285]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.

**Describe the bug**

We used to successfully run `fvm flutter pub global run melos run test:unit:flutter` to run some unit tests via a melos pipeline, however the same invocation now fails with the `flutter` command not being available anymore. Instead things now fail like this:

```
fvm: running version "1.22.6"

melos run test:unit:flutter
   └> melos exec -c 5 --fail-fast --dir-exists=test --ignore="*example*" --ignore="*web*" -- \  "mkdir -p test-results && flutter test --machine > test-results/flutter-test.json && exit 0"
       └> RUNNING

$ melos exec
   └> mkdir -p test-results && flutter test --machine > test-results/flutter-test.json && exit 0
       └> RUNNING (in 6 packages)

--------------------------------------------------------------------------------
[connect]: /bin/sh: line 1: flutter: command not found
[mnc_support]: /bin/sh: line 1: flutter: command not found
--------------------------------------------------------------------------------
```

The relevant bit in `melos.yaml` is:

```
  test:unit:flutter: >
    melos exec -c 5 --fail-fast --dir-exists=test --ignore="*example*" --ignore="*web*" -- \
      "mkdir -p test-results && flutter test --machine > test-results/flutter-test.json && exit 0"
```

- OS: mac
- FVM Version 2.0.2

**Comment by leoafarias** [comment]
@ened thanks for reporting this https://github.com/leoafarias/fvm/actions/runs/810010048

**Comment by ened** [comment]
@leoafarias you are a superstar
