### ISSUE TITLE
[BUG] Unable to change the location of the fvm folder from /home/user to any other.

### ISSUE THREAD

**Issue by JohnPinto** [leoafarias/fvm#290]
Hi, I've been trying to change the location of the fvm folder from my home directory to a new directory, but when I use the `fvm config --cache-path <new-path> ` and then use the `fvm flutter doctor` inside my project, the fvm folder inside my home is recreated, and the new location is not used, have I done something wrong, or do I need a second config command that I'm not aware of?

**Comment by leoafarias** [comment]
@JohnPinto This is the correct behavior, once FVM runs it needs to know where to get the config from. So you will continue to have the main FVM directory on your home, but the version cache will be where you set it.

However, if you set the env var `FVM_HOME`, it will move the whole fvm home directory and you will probably get the result you want.

**Comment by JohnPinto** [comment]
Hi @leoafarias I've added the `FVM_HOME` variable with my desired path, but when I run fvm config the command still shows the FVM Settings at the old location

**Comment by leoafarias** [comment]
@JohnPinto make sure you close your terminal and open again, also with this there is no need to set a cachePath anymore

**Comment by JohnPinto** [comment]
Thanks for the feeback!
