### ISSUE TITLE
[Question] Running `fvm flutter --version` reports unknown channel

### ISSUE THREAD

**Issue by abhaysood** [leoafarias/fvm#291]
I have setup FVM using the instructions in the documentation. The contents of `fvm_config.json` file are:

```
{
  "flutterSdkVersion": "2.0.6",
  "flavors": {}
}
```

Running `fvm flutter --version` gives the following output:
```
➜ fvm flutter --version
Flutter 2.0.6 • channel unknown • unknown source
Framework • revision 1d9032c7e1 (12 days ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```

Notice that the channel/source are reported as unknown. If I install 2.0.6 version without using `fvm` the output gives the channel and source correctly.

**Comment by leoafarias** [comment]
@abhaysood this question comes up every so often and I believe there has been change in behavior, which it does not impact.

but if you don’t kind me asking how are you is taking the standalone version 2.0.6?

**Comment by abhaysood** [comment]
I simply ran `fvm install 2.0.6`:
``` 
~ fvm install 2.0.6
fvm global Flutter 2.0.6 • channel unknown • unknown source
Framework • revision 1d9032c7e1 (2 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```

**Comment by leoafarias** [comment]
@abhaysood you mentioned that it’s different if you install 2.0.6 without fvm, how did you do that?

**Comment by abhaysood** [comment]
```
flutter upgrade 2.0.6
Flutter is already up to date on channel stable
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (2 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```

**Comment by leoafarias** [comment]
Ok, that is why… you are upgrading the channel.  Fvm pulls the tag version directly. 

Also flutter versions can repeat across channels, so the information is correct.
