### ISSUE TITLE
[Question] How to setup FVM for a project with a package and demo app

### ISSUE THREAD

**Issue by abhaysood** [leoafarias/fvm#293]
I have a use-case where a repository hosts a flutter package and a host application in it. The directory structure looks like the following. 
```
├── my_repository
    ├── package
        ├── lib
        ├── pubspec.lock
        ├── pubspec.yaml
    ├── example_app
        ├── android
        ├── build
        ├── ios
        ├── lib
        ├── pubspec.lock
        └── pubspec.yaml
```

What is the recommended way to setup FVM for such a project? Should I set `.fvm` in both `package` and `example_app` or is it possible to have a single `fvm` config for both.

**Comment by abhaysood** [comment]
I think I got the answer myself. Looking at the [documentation](https://fvm.app/docs/guides/running_flutter#routing) it seems it is possible to have a `.fvm` config at the root of the repo and then running `fvm flutter <any_command>` inside the `package` or `example_app` leads _fvm_ to pick the config from the ancestor directory.

IMO adding this explicitly in the documentation would help. It is quite hidden right now. 

P.S. Thanks for building this lean tool. :)

**Comment by leoafarias** [comment]
Thanks for the feedback, I have added that information on the FAQ of the documentation

**Comment by Wes1324** [comment]
@leoafarias Can you direct me to this documentation that you added please? It seems to have moved in the years since you added it.
