### ISSUE TITLE
[Question] Clarification on using stable channel

### ISSUE THREAD

**Issue by abhaysood** [leoafarias/fvm#294]
The FAQ mentions the following under "Upgrade Flutter Channel":
> As described in our Principles FVM does not override standard Flutter behavior. Therefore to upgrade a channel you will have to use standard flutter upgrade. You can find more about it in the Running Flutter section.

Does this mean if I use the following `fvm_config.json`, it would not update Flutter to the latest stable version when `fvm install` is run on the project?
```
{
  "flutterSdkVersion": "stable"
}
```

**Comment by leoafarias** [comment]
It does not update the channel automatically. It's the same behavior as Flutter CLI. However, I believe Flutter itself does warn you there is a newer version in that channel.

You can do `fvm flutter upgrade` to upgrade.

**Comment by abhaysood** [comment]
Got it. Thanks for the clarification :+1:
