### ISSUE TITLE
CI and CD for FLutter

### ISSUE THREAD

**Issue by gedw99** [leoafarias/fvm#3]
Support golang tooling for  https://codemagic.io/

How about supporting this ? You can do your building for IOS and Android without needing all the android and ios stuff on your laptop. SO you can basically deploy IOS apps WITHOUT needing to hae a mac.

ALso they have an app that you can put on your mobile that will download the build output.
https://blog.codemagic.io/introducing-testmagic-beta/

Its basically fastlane and many others reengineered.

I have been using it for 3 months. Its the easiest CI and CD i have found for FLutter.

**Comment by leoafarias** [comment]
Let me know a bit about the workflow that you are trying to accomplish to see how an integration might make sense

**Comment by leoafarias** [comment]
Will close this until I hear back

**Comment by gedw99** [comment]
hey @leoafarias 

1. All Desktops. 
- we need to fix hardcoded stuff.
For example here:
https://github.com/leoafarias/fvm/blob/master/lib/fluttertools/fluttertools.go#L111
Should be more like here: 
https://github.com/go-flutter-desktop/go-flutter/blob/master/example/simpleDemo/engineDownloader.go#L328

2. Boot strap a devs workstation with flutter ( which you do now ) and flutter desktop
flutter/blob/master/example/simpleDemo/engineDownloader.go

3. Use codes away on their flutter app
...

4. Users wants to get a build done
a. user commits to git
b. user goes to dashboard and setsup account at https://codemagic.io/settings
c. User adds github
d. User downloads the Android or Ios app loaders at:https://blog.codemagic.io/introducing-testmagic-beta/

Any thats it.

**Comment by leoafarias** [comment]
Thanks, @gedw99 I will explore a bit more in detail later.

Regarding your comment of hard-coded, FVM will actually respect what is set on .bash_profile, but it does set the default to be the usr/local/bin, to make sure they can use the flutter command from the terminal without having to set the flutter path on .bash_profile.

I think it might make sense to add the cache versions to the working directory, but if I set the default flutter to the working directory the user will still need to set flutter path.

**Comment by leoafarias** [comment]
@gesw99 I believe this workflow is better made for a proper CI/CD solution. Within the company we have been using bitrise and ir does auto code signing and deployment to wherever you want. I suggest taking a look

**Comment by joeblew99** [comment]
hey @leoafarias 
thanks for the feedback
Yeah there are a few options - I also used bitrise in the past.
I recently found the semi official one from the Flutter team here: https://github.com/mmcc007/fledge
He seems to be on the team.

The issue i have with Bitrise is that it can run on your servers i believe. Is that true ?

**Comment by leoafarias** [comment]
Bitrise does have a cli to run locally on your machine. https://app.bitrise.io/cli
