### ISSUE TITLE
$FVM_HOME not working in tmux?

### ISSUE THREAD

**Issue by X-Wei** [leoafarias/fvm#301]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
`FVM_HOME` is picked up in a normal (fish) shell, but not in tmux.

**To Reproduce**

1. in a bare fish shell, I get fvm working correctly:

```
$ fvm doctor

No FVM config found:
/home/<user>
Fvm will run the version in your PATH env: /home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Dart:
/home/<user>/Dotfiles/local/bin/flutter/bin/dart

FVM_HOME:
/home/<user>/.local/fvm  # 👈 this is what I've configured for ✅️
```

2. However when I run it in tmux, FVM_HOME is not found:

```
$ tmux
$ echo $FVM_HOME # Note: in tmux I see that the FVM_HOME env variable is set
/home/<user>/.local/fvm 

$ fvm doctor

No FVM config found:
/home/<user>
Fvm will run the version in your PATH env: /home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Dart:
/home/<user>/Dotfiles/local/bin/flutter/bin/dart

FVM_HOME:
not set # 👈👈 as a result it's using "/home/<user>/fvm/versions" as fvm cache dir, not "/home/<user>/.local/fvm/versions"❌️

```

**Expected behavior**
fvm should always use "/home/<user>/.local/fvm/versions" as cache dir.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- FVM Version: 2.0.5

**Additional context**

**Comment by leoafarias** [comment]
@X-Wei i don't think this is an fvm issue. I don't know much about tmux but is there a different way to set env vars for it?

**Comment by X-Wei** [comment]
I'm not aware how tmux set env vars differently... I also don't have env vars problems for other binaries.

The thing is in tmux I can see the env variable **is** set:
```
# inside a tmux-fish session
$ echo $FVM_HOME
/home/<user>/.local/fvm 
```

**Comment by leoafarias** [comment]
@X-Wei I wonder if dart is not reading the env.  Can you try setting this in tmux to see if the behavior is different? https://dart.dev/tools/pub/environment-variables Because I can see what they are doing differently.

**Comment by X-Wei** [comment]
hmm interesting, setting the variable with `set` (for fish) doesn't work, but **with `export` it works**:

```sh
$ set FVM_HOME /home/<user>/.local/fvm; fvm doctor

No FVM config found:
/home/<user>
Fvm will run the version in your PATH env: /home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Dart:
/home/<user>/Dotfiles/local/bin/flutter/bin/dart

FVM_HOME:
not set

$ export FVM_HOME=/home/<user>/.local/fvm; fvm doctor

No FVM config found:
/home/<user>
Fvm will run the version in your PATH env: /home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/home/<user>/Dotfiles/local/bin/flutter/bin/flutter

Dart:
/home/<user>/Dotfiles/local/bin/flutter/bin/dart

FVM_HOME:
/home/<user>/.local/fvm
```

So in my `config.fish`, instead of doing `set FVM_HOME "$HOME/.local/fvm"`, I change to `export FVM_HOME="$HOME/.local/fvm"` and now seems it's correctly picked up by tmux!
