### ISSUE TITLE
Can you make a docker file using the fvm?

### ISSUE THREAD

**Issue by Katekko** [leoafarias/fvm#303]
I'm a not expert in docker so I need some help to make a docker file that can work with the last version of the package.
I was using the last version that you can use the global flag and was working like a charm but without the global flag I'm not able to make a docker file that work.

```DOCKERFILE
#Stage 1 - Install dependencies and build the app
FROM debian:latest AS build-env

# Install dart/flutter dependencies
RUN apt-get update 
RUN apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3 gnupg2
RUN apt-get clean

# Install dart
RUN apt-get update
RUN apt-get install apt-transport-https
RUN sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
RUN sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
RUN apt-get update
RUN apt-get install dart

# Set dart path
ENV PATH="/usr/lib/dart/bin:root/.pub-cache/bin:/root/fvm/default/bin:${PATH}"

# Install FVM
RUN pub global activate fvm
RUN fvm help

# Install specific version of Flutter
RUN fvm install "2.2.0"
RUN fvm use "2.2.0" --global

# Run flutter doctor
RUN fvm flutter doctor -v

# Enable flutter web
RUN fvm flutter config --enable-web

# Copy files to container and build
RUN mkdir /app/
COPY . /app/
WORKDIR /app/
RUN flutter doctor
RUN flutter pub get
RUN flutter build web

# Stage 2 - Create the run-time image
FROM nginx
COPY --from=build-env /app/build/web /usr/share/nginx/html
```

**Comment by leoafarias** [comment]
@Katekko dis you take a look at the existing images?

https://github.com/leoafarias/fvm/tree/master/.docker

Also I am not sure if we have deployed an urdistes version but you can reference it.

**Comment by Katekko** [comment]
> @Katekko dis you take a look at the existing images?
> 
> https://github.com/leoafarias/fvm/tree/master/.docker
> 
> Also I am not sure if we have deployed an urdistes version but you can reference it.

Trying to use the existing image give me this message in the final:

```BASH
COPY --from=build-env /app/build/web /usr/share/nginx/html
invalid from flag value build-env: pull access denied for build-env, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

```DOCKERFILE
FROM google/dart:2.13.1

ARG 2.0.5

RUN apt-get update --quiet --yes
RUN apt-get install --quiet --yes \
    unzip \
    apt-utils

RUN pub global activate fvm ${FVM_VERSION}

RUN mkdir /app/
COPY . /app/
WORKDIR /app/

RUN fvm install
RUN fvm flutter doctor -v
RUN fvm flutter config --enable-web

RUN fvm flutter doctor
RUN fvm flutter pub get
RUN fvm flutter build web

FROM nginx
COPY --from=build-env /app/build/web /usr/share/nginx/html
```

Any idea to fix it? I'm trying to build flutter web as you can see

**Comment by Katekko** [comment]
> ```dockerfile
> FROM google/dart:2.13.1
> 
> ARG 2.0.5
> 
> RUN apt-get update --quiet --yes
> RUN apt-get install --quiet --yes \
>     unzip \
>     apt-utils
> 
> RUN pub global activate fvm ${FVM_VERSION}
> 
> RUN mkdir /app/
> COPY . /app/
> WORKDIR /app/
> 
> RUN fvm install
> RUN fvm flutter doctor -v
> RUN fvm flutter config --enable-web
> 
> RUN fvm flutter doctor
> RUN fvm flutter pub get
> RUN fvm flutter build web
> 
> FROM nginx
> COPY --from=build-env /app/build/web /usr/share/nginx/html
> ```

Forgot to add the alias to google image `FROM google/dart:2.13.1 AS build-env`
