### ISSUE TITLE
[BUG] windows: cannot run fvm without admin or dev mode

### ISSUE THREAD

**Issue by mx1up** [leoafarias/fvm#304]
**Describe the bug**
Impossible to run fvm without admin rights or enabling dev mode. 

I prefer not enabling dev mode or running all fvm commands as admin. I only opened an admin terminal when I wanted to created the symlink using `fvm use`. This is usually during the setup phase of a project and changes infrequently. Fvm flutter commands are run frequently and don't need admin rights. Up until recently, this workflow worked fine, but in a recent version the ability to create symlinks is checked, even if no commands are run requiring symlinking. 

Could the symlink check be restricted to commands that need it? i.e. fvm use.

**To Reproduce**

1. Go to terminal..
2. Run `fvm flutter pub get`
3. aborts with error `Seems you don't have the required permissions on C:\dev\fvm_home On Windows FVM requires to run as an administrator or turn on developer mode: https://bit.ly/3vxRr2M`

**Expected behavior**
the flutter command to be run

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- OS: windows
- FVM Version: 2.0.5
- If Windows: command shell

**Additional context**
I can probably provide PR if you agree

**Comment by leoafarias** [comment]
@mx1up that makes sense. I believe we would need to remove the ensureCacheWorkflow from the Flutter cmd, but please send a PR, and I would be happy to review

**Comment by leoafarias** [comment]
@mx1up let me know if the version 2.1.1 solves this problem, I think this should be much better now

**Comment by mx1up** [comment]
@leoafarias  awesome! i can confirm it works again, thanks
