### ISSUE TITLE
[BUG] FVM Cannot List Versions

### ISSUE THREAD

**Issue by chillbrodev** [leoafarias/fvm#306]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions. N/A
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
As of 4:45 PM PDT FVM has become unusable due to an access issue in the Google Storage URL. FVM prints out the following error:

```
fvm flutter
FormatException: Unexpected character (at character 1)
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Mess...
^


Failed to retrieve the Flutter SDK from: https://storage.googleapis.com/flutter_infra/releases/releases_macos.json
Fvm will use the value set on env FLUTTER_STORAGE_BASE_URL to check versions
if you are located in China, please see this page: https://flutter.dev/community/china

#0      fetchFlutterReleases (package:fvm/src/services/releases_service/releases_client.dart:40)
<asynchronous suspension>
#1      FlutterTools.inferValidVersion (package:fvm/src/services/flutter_tools.dart:41)
<asynchronous suspension>
#2      CacheService.getGlobal (package:fvm/src/services/cache_service.dart:115)
<asynchronous suspension>
#3      flutterGlobalCmd (package:fvm/src/utils/commands.dart:63)
<asynchronous suspension>
#4      FlutterCommand.run (package:fvm/src/commands/flutter_command.dart:39)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:196)
<asynchronous suspension>
#6      FvmCommandRunner.run (package:fvm/src/runner.dart:73)
<asynchronous suspension>
#7      main (file:///private/tmp/fvm-20210504-70950-10p65f8/fvm-2.0.2/bin/main.dart:6)
<asynchronous suspension>
```

**To Reproduce**

1. Go to terminal..
2. Run `fvm flutter`...
3. See error

**Expected behavior**
FVM should use the specified Flutter version and output the Flutter commands

**Logs**
```
fvm flutter --verbose
FormatException: Unexpected character (at character 1)
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Mess...
^


Failed to retrieve the Flutter SDK from: https://storage.googleapis.com/flutter_infra/releases/releases_macos.json
Fvm will use the value set on env FLUTTER_STORAGE_BASE_URL to check versions
if you are located in China, please see this page: https://flutter.dev/community/china

#0      fetchFlutterReleases (package:fvm/src/services/releases_service/releases_client.dart:40)
<asynchronous suspension>
#1      FlutterTools.inferValidVersion (package:fvm/src/services/flutter_tools.dart:41)
<asynchronous suspension>
#2      CacheService.getGlobal (package:fvm/src/services/cache_service.dart:115)
<asynchronous suspension>
#3      flutterGlobalCmd (package:fvm/src/utils/commands.dart:63)
<asynchronous suspension>
#4      FlutterCommand.run (package:fvm/src/commands/flutter_command.dart:39)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:196)
<asynchronous suspension>
#6      FvmCommandRunner.run (package:fvm/src/runner.dart:73)
<asynchronous suspension>
#7      main (file:///private/tmp/fvm-20210504-70950-10p65f8/fvm-2.0.2/bin/main.dart:6)
<asynchronous suspension>
```

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.7
- FVM Version: 2.0.2
- If Windows: Which Powershell are you using? N/A

**Additional context**

**Comment by TNorbury** [comment]
per @nicholasspencer: https://github.com/leoafarias/fvm/issues/307#issuecomment-852579874

**Comment by garrettApproachableGeek** [comment]
My shot in the dark is that the source of this is these commits, but I don't know the infrastructure of Flutter's build pipeline
https://github.com/flutter/infra/commit/c2ff7c803968f43143761c49a87f63db58d8b18a
https://github.com/flutter/engine/commit/ad10ab8d695ef7566ece0a2ff27b5eb89a2536f5

**Comment by PandaGeek1024** [comment]
getting the same issue

**Comment by leoafarias** [comment]
Deploying a workaround

**Comment by leoafarias** [comment]
Not my best work https://github.com/leoafarias/fvm/actions/runs/897831054, essentially created a cache of the current release which I am hosting here on Github. Should buy time to see if this is a permanent change.

**Comment by leoafarias** [comment]
It seems the release JSON is back up. I canceled the release. Will create a better fallback

**Comment by TNorbury** [comment]
Can confirm that it's working again for me

**Comment by leoafarias** [comment]
Will go ahead and close this issue. I created a github action cron that backup the release json and will use as a fallback going forward. https://github.com/leoafarias/flutter_flat_data.. PS: Github Flat Data is pretty amazing
