### ISSUE TITLE
[BUG] Failed to retrieve the Flutter SDK from: (url for platform)

### ISSUE THREAD

**Issue by TNorbury** [leoafarias/fvm#307]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
Upon running certain FVM commands, I've tested with `fvm use` and `fvm flutter ...`, the command fails with the following error message:

```
FormatException: Unexpected character (at character 1)
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Mess...
^


Failed to retrieve the Flutter SDK from: https://storage.googleapis.com/flutter_infra/releases/releases_windows.json
Fvm will use the value set on env FLUTTER_STORAGE_BASE_URL to check versions
if you are located in China, please see this page: https://flutter.dev/community/china

#0      fetchFlutterReleases (package:fvm/src/services/releases_service/releases_client.dart:40:5)
<asynchronous suspension>
#1      FlutterTools.inferValidVersion (package:fvm/src/services/flutter_tools.dart:41:22)
<asynchronous suspension>
#2      FlutterCommand.run (package:fvm/src/commands/flutter_command.dart:28:28)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#4      FvmCommandRunner.run (package:fvm/src/runner.dart:73:24)
<asynchronous suspension>
#5      main (file:///D:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/fvm-2.0.5/bin/main.dart:6:8)
<asynchronous suspension>
```

Happens on Mac too, however the url in the error message is https://storage.googleapis.com/flutter_infra/releases/releases_macos.json

**To Reproduce**

1. Go to terminal..
2. Run `fvm use` or `fvm flutter pub get`
3. Check...

**Expected behavior**
I expect the command to work (e.g. fvm flutter pub get would run flutter pub get with the configured fvm version).

**Logs**
N/A using --verbose doesn't provide any additional output

**Desktop (please complete the following information):**

- OS: Windows 10, MacOs 11
- FVM Version: 2.0.5 (Windows), 2.0.1 (Mac)
- If Windows: Not sure

**Additional context**
Linking to the fvm flutter binary directly (i.e. `.\.fvm\flutter_sdk\bin\flutter pub get`) works just fine

**Comment by TNorbury** [comment]
fvm doctor Windows:
```
FVM Version: 2.0.5
___________________________________________________

FVM config found:
___________________________________________________

Project: factory
Directory: D:\vakaros\code\factory
Version: stable
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: D:\tools\fvm\stable
Channel: true
SDK Version: 2.2.0

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: D:\vakaros\code\factory\.fvm\flutter_sdk


Configured env paths:
___________________________________________________

Flutter:
D:\tools\flutter\bin\flutter.bat

Dart:
D:\tools\flutter\bin\dart.bat

FVM_HOME:
not set
```

**Comment by TNorbury** [comment]
fvm doctor MacOS:
```
FVM config found:
___________________________________________________

Project: music_note
Directory: /Users/tnorbury/project
Version: stable
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: /Users/tnorbury/fvm/versions/stable
Channel: true
SDK Version: 2.2.0

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /Users/tnorbury/project/.fvm/flutter_sdk


Configured env paths:
___________________________________________________

Flutter:
/Users/tnorbury/tools/flutter/bin/flutter

Dart:
/Users/tnorbury/tools/flutter/bin/dart
```

**Comment by chillbrodev** [comment]
Duplicate of #306

**Comment by nicholasspencer** [comment]
This seems to be an issue or some changes to the flutter infrastructure https://github.com/flutter/flutter/issues/83746

**Comment by TNorbury** [comment]
@chillbrodev Ah, beat me to it lol
