### ISSUE TITLE
[BUG] Still throw exception while running fvm use <version> command in developer mode [windows] 

### ISSUE THREAD

**Issue by Prajun2010** [leoafarias/fvm#308]
Although I have activated developer mode, I'm still getting "Exception: On Windows FVM requires to run in developer mode or as an administrator" error while running fvm use.
After running fvm use , it switches to the required version but still throws that error.

![Screenshot 2021-06-04 193101](https://user-images.githubusercontent.com/42827734/120814560-ba716480-c56e-11eb-9243-0ae8466892e2.jpg)
![Screenshot 2021-06-04 193011](https://user-images.githubusercontent.com/42827734/120814575-bf361880-c56e-11eb-8c13-1b6b13183587.jpg)

**Comment by leoafarias** [comment]
@Prajun2010 have you resolved this?

**Comment by Prajun2010** [comment]
Not really, but I found that installing fvm using flutter cause this problem ( e.g. flutter pub global activate fvm ) .So, i reinstalled the fvm using pub only and the error was solved. Also, why activating fvm doesn't provide with the latest version, but provide with 1.3.7 version?

**Comment by Prajun2010** [comment]
> @Prajun2010 have you resolved this?

Not really, but I found that installing fvm using flutter cause this problem ( e.g. flutter pub global activate fvm ) .So, i reinstalled the fvm using pub only and the error was solved. Also, why activating fvm doesn't provide with the latest version, but provide with 1.3.7 version?

**Comment by leoafarias** [comment]
You have to update dart to the latest version since the new fvm uses null safety. You can also install using chocolatey that should solve a lot of these problems

**Comment by Prajun2010** [comment]
> You have to update dart to the latest version since the new fvm uses null safety. You can also install using chocolatey that should solve a lot of these problems 

Oh ! , I got that , thank you @leoafarias for the support.
