### ISSUE TITLE
[Feature Request]: Documentation on adding aliases

### ISSUE THREAD

**Issue by prajwal27** [leoafarias/fvm#309]
Currently, the docs suggest a way to add proxy. However, there's no proper guide in this regard.

**Comment by leoafarias** [comment]
@prajwal27 can you tell me a bit more about the issue? Which section of the docs you are referring to, FVM proxies flutter commands through ‘fvm flutter…’ there is no configuration necessary for this

**Comment by prajwal27** [comment]
```
# aliases
f="fvm flutter"
d="fvm dart"

# Now you can use
f run
```
I wasn't able to understand where and how to use this part.

**Comment by leoafarias** [comment]
@prajwal27 If you are using the Mac or Linux you can do something like this.
https://wpbeaches.com/make-an-alias-in-bash-or-zsh-shell-in-macos-with-terminal/

I am not sure how to accomplish this on windows.

**Comment by prajwal27** [comment]
@leoafarias  I'm unfortunately using Windows :P

**Comment by leoafarias** [comment]
Sorry about that, however you dont need this. You can just use `fvm flutter... `

**Comment by prajwal27** [comment]
@leoafarias  I found a way to do this on windows, shall I update the doc and make a MR?

**Comment by leoafarias** [comment]
Yes please
