### ISSUE TITLE
"fvm use" doesn't work

### ISSUE THREAD

**Issue by Giuliano-Stravini** [leoafarias/fvm#31]
Hi! First, i want say thanks for your initiative!

So, when i try run the command "fvm use 1.10.7", i get this exception:

```
PS C:\projetos\vimob\vimobpoc\app> fvm list
1.10.14
1.9.1
beta
PS C:\projetos\vimob\vimobpoc\app> fvm use 1.10.14
Using 1.10.14...
Unhandled exception:
type 'List<Object>' is not a subtype of type 'String'
#0      fvmRunner.<anonymous closure> (package:fvm/fvm.dart:39:45)
#1      _RootZone.runBinary (dart:async/zone.dart:1384:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#5      Future._completeError (dart:async/future_impl.dart:530:5)
#6      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#7      CommandRunner.runCommand (package:args/command_runner.dart)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     fvmRunner (package:fvm/fvm.dart:35:23)
<asynchronous suspension>
#12     main (file:///C:/Users/giuliano.stravini/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-0.6.5/bin/main.dart:4:9)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Using 1.10.14...
Unhandled exception:
type 'List<Object>' is not a subtype of type 'String'
#0      fvmRunner.<anonymous closure> (package:fvm/fvm.dart:39:45)
#1      _RootZone.runBinary (dart:async/zone.dart:1384:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#5      Future._completeError (dart:async/future_impl.dart:530:5)
#6      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#7      CommandRunner.runCommand (package:args/command_runner.dart)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     fvmRunner (package:fvm/fvm.dart:35:23)
<asynchronous suspension>
#12     main (file:///C:/Users/giuliano.stravini/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-0.6.5/bin/main.dart:4:9)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

OS: Windows 10
FVM: 0.6.5.

ps: Any version, i get this error.

I did something wrong? Or it's really a bug?

**Comment by leoafarias** [comment]
@Giuliano-Stravini thanks, I am still working through some of the kinks. I was able to replicate the issue when doing the `use` command on a directory that does not have fvm installed. For some reason, it doesn't fall under the same error logging logic that exists right now.

I see you are running within the app, so I will do further investigation.

**Comment by leoafarias** [comment]
@Giuliano-Stravini Please run version 0.6.6. I just made some updates. I am not sure this will fix your issue however you should get a bit better logs once you get the issue. Do you mind sending it here?

**Comment by Giuliano-Stravini** [comment]
@leoafarias Not solved, but the log changed!

```
PS C:\projetos\vimob\vimobpoc\app> fvm list
1.10.14
1.9.1
beta
dev
PS C:\projetos\vimob\vimobpoc\app> fvm use 1.10.14
Activating 1.10.14...
⚠️  Sorry could not link C:\fvm\1.10.14\bin\flutter
PS C:\projetos\vimob\vimobpoc\app>
```

I already have flutter 1.10.15(dev) installed, this can be a problem?

**Comment by leoafarias** [comment]
@Giuliano-Stravini can you run with the `--verbose` flag, and also have you made any changes to the config?

**Comment by Giuliano-Stravini** [comment]
Yes, i configured the cache path

```
PS C:\projetos\vimob\vimobpoc\app> fvm use 1.10.14 --verbose
[     0.049s] Activating 1.10.14...
[     0.066s] FileSystemException: Cannot create link to target 'C:\fvm\1.10.14\bin\flutter', path = 'C:\projetos\vimob\vimobpoc\app\fvm' (OS Error: O cliente não tem o privilégio necessário.
, errno = 1314)
[     0.068s] ⚠️  Sorry could not link C:\fvm\1.10.14\bin\flutter
#0      linkDir (package:fvm/utils/helpers.dart:35:5)
<asynchronous suspension>
#1      linkProjectFlutterDir (package:fvm/utils/flutter_tools.dart:201:9)
<asynchronous suspension>
#2      UseCommand.run (package:fvm/commands/use.dart:33:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:222:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      fvmRunner (package:fvm/fvm.dart:26:23)
<asynchronous suspension>
#8      main (file:///C:/Users/giuliano.stravini/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-0.6.6/bin/main.dart:4:9)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

ps: "(OS Error: O cliente não tem o privilégio necessário. errno = 1314)" =  "(OS Error: the client does not have the required privilege. errno = 1314)"

**Comment by leoafarias** [comment]
I was able to replicate the issue of saving in my Home directory which on the Windows would be C:/ . That would cause the issue.

If you trying to store on C I believe you can just remove the cache url. I will probably add better validation for this case and will update soon

**Comment by Giuliano-Stravini** [comment]
Oh i got it.

This happens in any path config. I guess i did something wrong haha

**Comment by searchy2** [comment]
Thanks @leoafarias for investigating these issues. I can't wait for FVM to work as it will save me so much time. 

Currently, I'm experiencing the same issue as above. 

My fvm is installed in `C:\Users\Laptop\fvm\versions\master\bin\flutter` and not in the local project folder. From #21, I see that one way for fvm to work from inside the project? How can I set it up to work that way? 

Thanks :)

**Comment by leoafarias** [comment]
@searchy2 I think these are separate issues. The way FVM works is that you can install versions and they are cached globally. When you install the version local it references that global version. 

This is important to avoid the long build processes that can happen with flutter.

Let me konw if that clarifies

**Comment by searchy2** [comment]
@leoafarias I'm sorry that I don't fully understand and need some additional clarification. 
How do you install FVM locally? Right now, I've ran `pub global activate fvm`. Do I need to install it in my project folder somehow? 

Thanks 🥇

**Comment by CaiJingLong** [comment]
> @leoafarias I'm sorry that I don't fully understand and need some additional clarification.
> How do you install FVM locally? Right now, I've ran `pub global activate fvm`. Do I need to install it in my project folder somehow?
> 
> Thanks 🥇

https://dart.dev/tools/pub/cmd/pub-global#running-a-script-from-your-path

**Comment by leoafarias** [comment]
@searchy2 thanks for the delay responding. The SDK versions are installed "globally" This is important because if you have multiple projects using the same version it reuses instead of having them multiple times.  As you probably know they get pretty large.

So the versions are "cached" globally, but they get referenced per project. So a project can reference any of the globally cached versions.

You should be able to install and do everything you need based on the instructions on the readme file. Please let me know if there is anything that is not clear so I can clean up.

**Comment by searchy2** [comment]
@leoafarias Thanks for taking a look! I've followed the steps in the ReadMe and am running into this issue.
![MaxthonSnap20191126101114](https://user-images.githubusercontent.com/19896174/69651127-3b27da00-1035-11ea-9698-487fe99a3e2d.png)
I guess I still don't fully understand how to reference a version "per project". Is this done manually via a config file or through fvm?

**Comment by askarsyzdykov** [comment]
Same issue:

```
➜  ~ fvm list
1.10.3
1.13.0
➜  ~ fvm use   
Please provide a version. fvm use <version>
➜  ~ fvm use 1.13.0
Activating 1.13.0...                    
⚠️  Sorry could not link /Users/askarsyzdykov/fvm/versions/1.13.0/bin/flutter
➜  ~ fvm use 1.10.3
Activating 1.10.3...                    
⚠️  Sorry could not link /Users/askarsyzdykov/fvm/versions/1.10.3/bin/flutter
➜  ~ open  /Users/askarsyzdykov/fvm/versions/ 
```

**Comment by rchavik** [comment]
AFAIK, fvm will create a symlink (or its equivalent) in the directory you ran `fvm use`.  Not sure how it is in windows, but in linux i typically invoke fvm (after `fvm use`) via the following `./fmv <command>`.  Note the `./` to implicitly invoke the fvm file in the current directory.

**Comment by leoafarias** [comment]
@searchy2 I suggest reading the instructions on the readme if you are still having issues. You will have to install the flutter version first. I will be adding a better description and maybe a prompt to install the version

**Comment by humazed** [comment]
I'm having the same issue as @searchy2

**Comment by searchy2** [comment]
Thanks for the suggestion @leoafarias 
Unfortunately, I still run into the link issue.
![MaxthonSnap20200102152737](https://user-images.githubusercontent.com/19896174/71694347-85a71f80-2d74-11ea-8673-f6f6d8fb483e.png)

**Comment by rchavik** [comment]
It's been decades since I've used Windows, but see if this applies: https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links

**Comment by leoafarias** [comment]
@searchy2 version 0.6.7 has some fixes for windows that I think it might address your issue. Would you mind testing with that version?

**Comment by chrisoftech** [comment]
To create a symlink, fvm requires administrative rights. You can open a terminal with administrative rights and cd project-root-directory and run fvm use [flutter version]
