### ISSUE TITLE
[Feature Request] - Configure IDE path on "use" command

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/fvm#310]
## Problem:
Right now the user needs to manually configure their IDE path for VSCode in order to have all IDE tooling running properly. This causes some support issues to be opened, need to view the documentation, and also a less ideal Dev experience.

## Solution:
When the developer does `fvm use <version>` fvm should automatically detect the IDE and configure the version if it has not been configured before.

### VS Code:
- Look for the .vscode folder in the project
- Look for settings `settings.json`
- Look for `dart.flutterSdkPath` or `dart.flutterSdkPaths`
- If exists it should be ignored, if not it should set the path to `<version>`
- Should also configure all remaining settings as described here if they do not exist -> [vscode config](https://fvm.app/docs/getting_started/configuration/#vs-code)

### Android Studio:
- Studio also creates a `.idea` folder however some research needs to be done if this can be created the same way as vscode or needs to be configured within the IDE itself.

**Comment by artificerchris** [comment]
I was actually coming to suggest this, but I just noticed, in the logs for the VSCode flutter extension, the extension looks for a flutter SDK at the root of the workspace in a folder called `.flutter`. I ran `ln -s .fvm/flutter_sdk .flutter` and upon re-opening my project, the editor found the sdk automatically! Maybe we could get an option in fvm use to link the SDK there instead of `.fvm/flutter_sdk`.

**Comment by leoafarias** [comment]
That is a great suggestion. Do you want take a stab at it with a PR, it would be important to maintain both directories, to offer backwards compatibility, and provide a deprecation notice.

**Comment by artificerchris** [comment]
Any strong preference on it being a flag vs just the default behavior with a notice? I don't mind to make a PR, but it'll likely be this weekend if it's more than a simple change.

**Comment by leoafarias** [comment]
Yes I believe that makes sense... I suggest keeping more specific like `flutterProjectSdkPath` since we have the fvm path, and some others which are the cache version.

**Comment by leoafarias** [comment]
This has changed considerably for version 3.0, I believe on Vscode. this already is behaving correctly, but I am not sure what is the best approach to change the PATH on android studio.

**Comment by ManuelRauber** [comment]
@leoafarias I'm trying FVM 3.0 beta 5 and I've noticed, that the structure within the `.fvm` has been changed.

In the [docs of FVM 2.x](https://fvm.app/docs/getting_started/configuration#android-studio) there is:

> Copy the absolute path of fvm symbolic link in your root project directory. Example: `/absolute-project-path/.fvm/flutter_sdk`

As per FVM 3.0, there is no `flutter_sdk` folder anymore, the structure looks like:

```
.fvm
  - version
  - release
  - versions
    - 3.16.0
```

To make it work in Android Studio, I've to point it to an exact version, like `/absolute-project-path/.fvm/versions/3.16.0`.

While FVM still makes it easier to handle multiple Flutter versions, within a project each team member will have to change their paths. 

It looks like that in Android Studio the paths are saved under `.idea/libraries/Dart_SDK.xml` and `.idea/libraries/Dart_Packages.xml`. 

So, there are two possible solutions:

1. When `fvm use` is invoked, change the paths in those files. 
2. Re-introduce a `flutter_sdk` folder that points to whatever version in `.fvmrc`.

**Comment by kuhnroyal** [comment]
Did you check the `.fvm/version` folder?

**Comment by ManuelRauber** [comment]
> Did you check the `.fvm/version` folder?

What exactly do you mean?

`version` is a file.

```
ls -al
total 16
drwxr-xr-x   5 manuelrauber  staff   160 Nov 16 09:39 .
drwxr-xr-x  38 manuelrauber  staff  1216 Nov 16 11:57 ..
-rw-r--r--   1 manuelrauber  staff     6 Nov 16 09:39 release
-rw-r--r--   1 manuelrauber  staff     6 Nov 16 09:39 version
drwxr-xr-x   3 manuelrauber  staff    96 Nov 16 09:39 versions
```

**Comment by kuhnroyal** [comment]
Ah ok, thought this might be the new linked version folder, nvm.

**Comment by leoafarias** [comment]
@ManuelRauber I think adding the symlink to flutter_sdk might make sense, however I had the symlink resolve every time in my android studio setup. Also I am really interessted in changing the android studio path similar to what we are doing with vscode, is that something you can provide more insight, or maybe even do a rough PR that I can take over?

**Comment by ManuelRauber** [comment]
@leoafarias I can try to make a rough sketch if changing the paths in the .idea folder actually works.

**Comment by leoafarias** [comment]
@ManuelRauber looks good, could you make a PR with that change, so I can bring it over before releasing 1.0, also if its not too much to ask, I want to create a page about Android Studio integration, and maybe explain that behavior, so people are aware of these details.

**Comment by ManuelRauber** [comment]
> @ManuelRauber looks good, could you make a PR with that change, so I can bring it over before releasing 1.0, also if its not too much to ask, I want to create a page about Android Studio integration, and maybe explain that behavior, so people are aware of these details.

@leoafarias yes, I can do a PR that includes:

* the SymLink
* Docs
* Maybe a little check in fvm doctor or so that simply outputs if PROJECT_DIR is found in idea settings
