### ISSUE TITLE
Any way to append/prefix fvm 

### ISSUE THREAD

**Issue by utsavDave97** [leoafarias/fvm#311]
Let's say my project is using fvm version 2.0.5.

I open my project in VSCode and go to terminal. 

Inside terminal if I type `flutter --version` it says that I am using `1.22.6`. This `1.22.6` is installed in my mac.

But inside terminal if I type `fvm flutter --version` it says that I am using `2.0.5`.

Is there any way where I can append or add `fvm` prefix to every flutter commands inside VSCode or Android Studio?

Thank you much.

**Comment by leoafarias** [comment]
There are a few ways of doing that but they are manual. I suggest following some of the tips here https://fvm.app/docs/guides/running_flutter and configure an alias

```
# aliases
f="fvm flutter"
d="fvm dart"

# Now you can use
f run
```

**Comment by utsavDave97** [comment]
Thanks for prompt reply.

Would you please be able to guide as to how to edit this aliases thing on MacOS and WindowsOS?

Like do I need to edit `$PATH` on Mac/Windows?

Sorry for this stupid question

**Comment by leoafarias** [comment]
@utsavDave97 I think this should point you at the right direction https://dev.to/stuartcreed/how-to-add-aliases-to-your-terminal-on-mac-os-53dl

**Comment by utsavDave97** [comment]
awesome thanks. appreciate it.
