### ISSUE TITLE
[BUG] : not able to track local changes in Android Studio

### ISSUE THREAD

**Issue by prajwal27** [leoafarias/fvm#313]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
![image](https://user-images.githubusercontent.com/31249460/121156905-bc853d00-c866-11eb-9f6c-3c756da5e0e7.png)
I get this when I check my commit dialog in Android Studio. I have followed the installation steps.

**`fvm doctor`
```
E:\okDone\flutter-main\okdone>fvm doctor

FVM Version: 2.0.6
___________________________________________________

FVM config found:
___________________________________________________

Project: okdone
Directory: E:\okDone\flutter-main\okdone
Version: stable
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: D:\Installs\fvm\stable
Channel: true
SDK Version: 2.2.1

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: E:\okDone\flutter-main\okdone\.fvm\flutter_sdk


Configured env paths:
___________________________________________________

Flutter:
D:\flutter\bin\flutter.bat

Dart:
C:\Program Files\Dart\dart-sdk\bin\dart.exe

FVM_HOME:
not set

```

**Expected behavior**
It should ideally show all the local changes without any warning.

**Desktop (please complete the following information):**

- OS: Windows
- FVM Version: stable
- If Windows: Which Powershell are you using? : command line, but it shouldn't matter here?

**Comment by leoafarias** [comment]
@prajwal27 it seems the symlink is not pointing to an installed version. Can you run the `fvm use <version>` command again?

**Comment by prajwal27** [comment]
@leoafarias  I have tried it, but it still doesn't work. I had to delete `.fvm` folder and retry. I'm not sure if it's a hack or the actual solution.

**Comment by leoafarias** [comment]
I believe the version was removed, so but recreating the link it fixed ir

**Comment by prajwal27** [comment]
Sorry to reopen this issue, but the above method tracks the changes, but the w.r.t. symlink still exists.

**Comment by prajwal27** [comment]
@leoafarias  So, what I noticed is, the first when Android Studio is opened, it tracks the local changes and shows it.
If we make any further changes, the Android Studio won't detect it.  So every time we have to delete the `.fvm` folder in order to see the commits in the dialog box in android studio. 

In the terminal it's working fine, something is not right in the way fvm is linked with Android Studio.

**Comment by leoafarias** [comment]
When you say make local changes, you mean if you switch the version with `fvm use <version>` for example?

**Comment by prajwal27** [comment]
@leoafarias  no, not like that. If I make any code changes in the flutter project, that doesn't show in the local changes dialog when I do `ctrl  + k` in Android Studio.

**Comment by leoafarias** [comment]
@prajwal27 I am not as familiar with Android Studio inner workings, is there a way for
It to maybe ignore the symlink. 

I haven’t heard of this issue before

**Comment by prajwal27** [comment]
@leoafarias  I'm not really sure about ignoring the symlink. This is causing a major disturbance while coding, it takes away the advantages of Android Studio, hence I had to stop using fvm :(

**Comment by leoafarias** [comment]
Will try to replicate this

**Comment by leoafarias** [comment]
@prajwal27 but I could not replicate the error, can you make sure you add the flutter_sdk to your git ignore and also try the steps described here? https://stackoverflow.com/questions/25272326/jetbrains-warning-not-all-local-changes-may-be-shown-due-to-an-error-svn-e2

**Comment by leoafarias** [comment]
@prajwal27 I will go ahead close this issue as I dont have enough information to be able to troubleshoot and have not received feedback on the last comment. Please open a new issue if the problem persists.
