### ISSUE TITLE
[Feature Request] easy way to use forked flutter repository

### ISSUE THREAD

**Issue by 2ZeroSix** [leoafarias/fvm#315]
**Is your feature request related to a problem? Please describe.**
It's hard to use forked flutter repository across team members.
It was much harder until #256, but it's still really verbose and does not work with shared `.fvm/fvm_config.json` out of the box.
We can't just call `fvm install` and expect the desired version to be installed.

**Describe the solution you'd like**

We already have env variable for repo url override: `FVM_GIT_CACHE`.
I think the most convenient solution is to just add a flag to ignore the version validation in `FlutterTools.inferValidVersion` and save it `fvm_config.json`

**Describe alternatives you've considered**
1.  currently I end up with custom setup script. example:
    ```bash
    FLUTTER_VERSION="<version>"

    cachePath="$(fvm config | grep cachePath | sed -E 's/cachePath: (.*)/\1/g')"

    cd "$cachePath"
    if [ ! -d "$cachePath/custom_$FLUTTER_VERSION" ]; then
      git clone --single-branch --branch "$FLUTTER_VERSION" "<repo>" "custom_$FLUTTER_VERSION"
    else
      cd "custom_$FLUTTER_VERSION"
      git checkout "$FLUTTER_VERSION" --force
      git pull
    fi
    cd "$projectPath"
    
    fvm use "custom_$FLUTTER_VERSION"
    ```

2. ignore validation when `FVM_GIT_CACHE` is set

**Comment by leoafarias** [comment]
@2ZeroSix I think a flag on FVM settings to ignore version validation makes sense. However that would be in the FVM settings and not in the project to make things simpler. Is that something you would like to create a PR for? If not I will put on the queue but I am not sure when I can get to it.

**Comment by 2ZeroSix** [comment]
Thanks for feedback!

I'll try to implement this in the next few days

**Comment by leoafarias** [comment]
@2ZeroSix We had another similar issue, and due to some challenges with validation in the past few days due to downtime and changes on Flutter I decided to remove it. That should solve your problem.

**Comment by leoafarias** [comment]
This has been deployed on version 2.1.1
