### ISSUE TITLE
[Feature Request] control check fvm update

### ISSUE THREAD

**Issue by Mao-x-w** [leoafarias/fvm#316]
Can you provide an option to control check fvm update? Because, it was so slow sometime。

`
if (cmd == 'use' || cmd == 'install' || cmd == 'remove') {
    // Check if there is an update fofr FVM
    await checkForFvmUpdate();
  }
`

I want to control it through the following command:
`
fvm use 1.22.6 --not-check-update
`

**Comment by leoafarias** [comment]
@Mao-x-w I might add this as a config option

**Comment by Mao-x-w** [comment]
@leoafarias  OK,Thank you.

**Comment by leoafarias** [comment]
On 3.0, the check will happen only once per day. you are also able to pass the setting which we will be updating on the docs later
