### ISSUE TITLE
[BUG] cmd always show could not install

### ISSUE THREAD

**Issue by Nabouste** [leoafarias/fvm#319]
when i tried to build apk using 

fvm flutter build apk --release --target-platform=android-arm64 -t lib/main.dart --flavor dev

always show could not install

![image](https://user-images.githubusercontent.com/29367624/121993335-7df30380-cdcd-11eb-9a84-78914c8fe004.png)

![image](https://user-images.githubusercontent.com/29367624/121993623-04a7e080-cdce-11eb-8177-ccd1a97bc894.png)

**Comment by leoafarias** [comment]
@Nabouste can you run the command with `fvm --verbose ....` please also run fvm doctor on the same directory that you are running the command

**Comment by Nabouste** [comment]
fvm verbose. 


![image](https://user-images.githubusercontent.com/29367624/122903276-70172280-d379-11eb-8881-4af96f391d0e.png)

**Comment by leoafarias** [comment]
Maybe I was not clear please add `fvm --verbose` in front of the rest of the command `flutter build apk .........`
So its `fvm --verbose flutter build apk .....other args.... `

**Comment by cassiorosso** [comment]
![Capturar](https://user-images.githubusercontent.com/61170321/125544341-6b1eccf0-5cb9-49e9-b072-0b04ae1e0e7d.PNG)

Same problem here

**Comment by leoafarias** [comment]
@cassiorosso could you try to install 1.22.6 through `fvm install 1.22.6`, seems fvm is getting a configuration to run 1.22.6 but its getting an error which I am not familiar with

**Comment by leoafarias** [comment]
@cassiorosso looking at the issue again, I believe because the version is not installed.. you have to run it as administrator, and link to the project also. After that, you won't need to run as an administrator.

I will go ahead and close this issue, please reopen with detailed information on how to replicate it to see how I can help.
