### ISSUE TITLE
[BUG] Could not find a command named "dart".

### ISSUE THREAD

**Issue by rahuldange09** [leoafarias/fvm#320]
**Describe the bug**
Tried running "fvm dart" but it says

> Could not find a command named "dart".

Also some other also not working
like

> fvm doctor

> Could not find a command named "doctor".

But "fvm flutter" works and others also

**To Reproduce**
fvm dart

**Expected behavior**
Should show dart commands

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- FVM Version 1.3.7
- Dev OS: Mac os with zsh

**Comment by leoafarias** [comment]
@rahuldange09 The dart command is on version 2.0. If you are installing using `pub global activate fvm`, its important that you upgrade the local dart sdk

**Comment by rahuldange09** [comment]
Ohh
So I have to be on the latest flutter SDK locally?
Actually, I was on Flutter 1.22.6 and wanted to upgrade some projects to flutter 2.2 with null safety.
So I have to do the reverse thing?
Keep local to 2.2 and fvm to 1.22.6?

**Comment by leoafarias** [comment]
You can have whatever version of Flutter installed if you have the latest version of Dart SDK. Locally, if you are using the Dart version on Flutter to install FVM, then you would have to run the Dart on Flutter 2.2.

If the above is very confusing, I suggest just installing FVM through brew, or chocolatey, per the instructions on the docs.

**Comment by rahuldange09** [comment]
@leoafarias  Thank you so much for the quick response with a suggestion. I have installed standalone by brew.
Fixed that issue now
Thank you.
Closing this.
