### ISSUE TITLE
Flutter commands do not work without internet connection

### ISSUE THREAD

**Issue by vincevargadev** [leoafarias/fvm#321]
**Describe the bug**

FVM fetches `https://storage.googleapis.com/flutter_infra/releases/releases_macos.json` on every command, so this makes it so that even simple commands that should not depend on internet connection fail.

I already installed the correct version of Flutter with FVM, so that should not be an issue.

For example, I want to be able to execute `flutter format` without a working internet connection, currently, I cannot.

**To Reproduce**

1. Turn off your internet
2. Run `fvm flutter format .`

**Expected behavior**

I don't need internet connection to execute `flutter format`, or other Flutter commands that do not need internet connection via FVM.

**Logs**

```
$ fvm flutter format .

Failed to retrieve the Flutter SDK from: https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json
Fvm will use the value set on env FLUTTER_STORAGE_BASE_URL to check versions
if you are located in China, please see this page: https://flutter.dev/community/china

#0      fetchFlutterReleases (package:fvm/src/services/releases_service/releases_client.dart:54:7)
<asynchronous suspension>
#1      FlutterTools.inferValidVersion (package:fvm/src/services/flutter_tools.dart:41:22)
<asynchronous suspension>
#2      FlutterCommand.run (package:fvm/src/commands/flutter_command.dart:28:28)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#4      FvmCommandRunner.run (package:fvm/src/runner.dart:72:24)
<asynchronous suspension>
#5      main (file:///Users/vargavin/.pub-cache/hosted/pub.dartlang.org/fvm-2.1.0/bin/main.dart:6:8)
<asynchronous suspension>



$ flutter format .
### Works fine even without internet connection
```

**Desktop (please complete the following information):**

```
$ fvm --version
2.10.0
```

**Comment by leoafarias** [comment]
@vincevargadev that is correct. I am thinking about removing this check since now Flutter has reached more consistent versioning.

**Comment by kuhnroyal** [comment]
Great jib, this also makes all commands a lot faster in certain scenarios!
