### ISSUE TITLE
Not working on WSL

### ISSUE THREAD

**Issue by peterlobster** [leoafarias/fvm#328]
For some reason, I can't get this to work on my Windows machine using Debian on WSL2. I'm not even too sure if the problem is related to WSL but I'm assuming as it works on macOS fine. Anyone know what it could be?

```shell
bsh ➡ fvm install stable
/usr/bin/env: ‘bash\r’: No such file or directory
```

**Comment by leoafarias** [comment]
@peterlobster not sure how to approach this can you run a —verbose, is it even running fvm?

**Comment by peterlobster** [comment]
@leoafarias Thanks for stepping in. Here's the output with `--verbose`...
```shell
bsh ➡ fvm install --verbose stable
[     0.014s] Version: stable - already installed.
/usr/bin/env: ‘bash\r’: No such file or directory
```

**Comment by leoafarias** [comment]
@peterlobster are you sure the create did not run? Can you do `fvm --vebose flutter --version`?

**Comment by peterlobster** [comment]
@leoafarias Yes, cause there are no output files created. Kinda, this is what I get back...

```shell
bsh ➡ fvm --verbose flutter --version
[     0.019s] Version: stable - already installed.
[     0.025s] Link is setup correctly
[     0.025s] fvm: running version "stable"

/usr/bin/env: ‘bash\r’: No such file or directory
```

**Comment by leoafarias** [comment]
@peterlobster I am not sure what could be happening, but I believe that when its Windows it looks for .bat file, which I don't think it would run.

**Comment by peterlobster** [comment]
@leoafarias Could it be that I'm interop'ing the `FVM_HOME` folder between `FVM` on Linux, Windows, and Sidekick on Windows?

**Comment by leoafarias** [comment]
I think that could be having different side effects but I am not sure. In theory by the time it hits this fvm:running version, it found the SDK, and its creating a process linking to it.

My first thought is that this line

```
// Extension per platform
String _binExt = Platform.isWindows ? '.bat' : '';
```

Might be giving problems since it thinks it is windows.

Any way you can clone the repo and install the fvm version locally to debug this?

You can just run

```
pub global activate --source path . 
```

Once you inside the cloned fvm repo

**Comment by peterlobster** [comment]
@leoafarias Should I uninstall first? I installed it via `brew`.

**Comment by peterlobster** [comment]
@leoafarias Any word on what I should do?

**Comment by leoafarias** [comment]
I don’t to be honest. Did you try installing through pub? After uninstalling from brew?

**Comment by kevindaizj** [comment]
> For some reason, I can't get this to work on my Windows machine using Debian on WSL2. I'm not even too sure if the problem is related to WSL but I'm assuming as it works on macOS fine. Anyone know what it could be?
> 
> ```shell
> bsh ➡ fvm install stable
> /usr/bin/env: ‘bash\r’: No such file or directory
> ```

@leoafarias  some error on macOS. (installed fvm with brew)

**Comment by leoafarias** [comment]
@kevindaizj not sure if this is an fvm error.. since the binary does not even run… do you have other packages from brew also running on that env?
