### ISSUE TITLE
How to upgrade fvm version to latest?

### ISSUE THREAD

**Issue by Caiheng12** [leoafarias/fvm#335]
I run pub global activate fvm always update to 1.3.6, Why?

**Comment by Caiheng12** [comment]
but latest version is 2.2.2

**Comment by kuhnroyal** [comment]
Your global Dart version is probably too old. (The one you are running `pub` with)

**Comment by KyawNaingTun** [comment]
![Screen Shot 2021-07-19 at 22 35 58](https://user-images.githubusercontent.com/6079250/126191801-25049ad1-ef77-46ae-b7c4-7b6fe482146d.png)
Same here

**Comment by leoafarias** [comment]
In order for you to install through `pub global` you need to have the latest stable version of Dart with null safety.  If you do not want to go through that or does not have the standalone version of dart installed.. I would suggest installing through brew or chocolatey.

https://fvm.app/docs/getting_started/installation

**Comment by VisakhRaman** [comment]
Yes, agreeing with @leoafarias. Upgrading dart version to the latest will install the latest version of FVM through CLI.

To upgrade your Flutter SDK version, try `flutter upgrade` 
Once updated, try `pub global activate fvm`

**Comment by andynvt** [comment]
`brew install fvm` helped me
