### ISSUE TITLE
[BUG] "NoSuchMethodError: The getter 'iterator' was called on null" when using fvm use version command

### ISSUE THREAD

**Issue by madscs11** [leoafarias/fvm#336]
**Describe the bug**

Our CI suddenly started (this week) getting issues when running `fvm use $FLUTTER_VERSION` after having previously worked fine.
It now even fails on old builds that succeeded in the past.

As part of the commands given for this build task we should be updating fvm correctly and it has also been working fine previously.

This command is run before the `fvm use` command in question:
`$ flutter pub global activate fvm`

I hope you can help us with our issue! To me it doesn't appear to be an issue in our code since these commands now fail on build that were previously succesful. 

**Expected behavior**

Prior to this we would receive a prompt to update but since we haven't updated our Flutter project past 2.0 yet we have kept it as is. The command would succeed just fine and give the following prompt:

$ fvm use $FLUTTER_VERSION
Project now uses Flutter: 1.22.3
___________________________________________________
FVM Update Available 1.2.3 → 2.2.2 
Changelog: https://github.com/leoafarias/fvm/releases/tag/2.2.2
Run pub global activate fvm to update

**Logs**

$ fvm use $FLUTTER_VERSION --verbose
Project now uses Flutter: 1.22.3
[     0.483s] ⚠️  NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new List.from (dart:core-patch/array_patch.dart:54:19)
#2      new PubPackage.fromMap (package:fvm/utils/pubdev.dart:30:16)
#3      pubPackageFromMap (package:fvm/utils/pubdev.dart:8:16)
#4      _fetchPubPackageInfo (package:fvm/utils/pubdev.dart:44:10)
<asynchronous suspension>
#5      checkIfLatestVersion (package:fvm/utils/pubdev.dart:51:30)
#6      UseCommand.run (package:fvm/commands/use.dart:80:11)
#7      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Unhandled exception:
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new List.from (dart:core-patch/array_patch.dart:54:19)
#2      new PubPackage.fromMap (package:fvm/utils/pubdev.dart:30:16)
#3      pubPackageFromMap (package:fvm/utils/pubdev.dart:8:16)
#4      _fetchPubPackageInfo (package:fvm/utils/pubdev.dart:44:10)
<asynchronous suspension>
#5      checkIfLatestVersion (package:fvm/utils/pubdev.dart:51:30)
#6      UseCommand.run (package:fvm/commands/use.dart:80:11)
#7      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Cleaning up file based variables

ERROR: Job failed: exit code 1

**Desktop (please complete the following information):**

- OS: Docker machine
- FVM Version 1.2.3

**Comment by leoafarias** [comment]
@madscs11 I suggest updating FVM to the latest version. The previous version of FVM was dependent on an endpoint from Flutter that was deprecated without notice. I believe this is what might be causing the issue.

**Comment by madscs11** [comment]
@leoafarias Thank you! We were missing a `flutter upgrade` call in the given script before running the fvm commands 🙂 

It's working now so I'll close the issue.
