### ISSUE TITLE
VS Code got 'Could not find a Flutter SDK.' error after fvm installed

### ISSUE THREAD

**Issue by 1lin24** [leoafarias/fvm#338]
Thinks for developers of fvm at first.

I have install fvm and tow flutter SDK in my new mbp. But VS Code could not find the sdk downloaded by fvm.

I decide to use fvm to manage my Flutter SDK, and never download Flutter from official website.

How I can use fvm only, and let VS Code detect my Flutter SDK that has manage by fvm.

Thinks for your help. ^_^

**Comment by leoafarias** [comment]
@1lin24 let me know if this helps you https://fvm.app/docs/getting_started/configuration#vs-code

**Comment by leoafarias** [comment]
@whoizit did you follow the instructions I linked to? It seems the dart sdk is pointed to a repository on asdf, maybe it was removed?

**Comment by leoafarias** [comment]
@whoizit I will be closing this issue, please feel free to reopen if you still need help
