### ISSUE TITLE
cant see flutter version 2.5 ?

### ISSUE THREAD

**Issue by SogoGolf** [leoafarias/fvm#340]
hi, for some reason i cant see Flutter v2.5 in the stable channel in the FVM UI ?

```fvm --version```
is showing 2.0.4 which is not current...

**Comment by leoafarias** [comment]
@SogoGolf what version of FVM are you using. Also can you check again the version should be showing up now.

**Comment by SogoGolf** [comment]
hey @leoafarias yes it seems ive got 2.0.4 even though i ran a CLI update of FVM.

**Comment by SogoGolf** [comment]
i ran ```brew``` install of FVM again and its now showing v2.2.3. Version 2.5.0 is now also showing up in the list of available Flutter SDK versions
