### ISSUE TITLE
[Feature Request] Out-of-the-box Debian or Arch based Linux installation support

### ISSUE THREAD

**Issue by E-jarod** [leoafarias/fvm#343]
I am on Linux (Ubuntu/Debian or Manjaro/Arch Linux), can you add support for `apt` and `pacman` as "simple way to install" ?

```zsh
# Debian family distros
apt install fvm

# Arch family distros
pacman -S fvm

# or, on AUR repositories (personally I use yay)
yay -S fvm
```

I think it will bring way more people in order to contribute for this tool, or simply use it

**Comment by maks** [comment]
For Debian based distros getting something into the main debian repository I think is [quite an under taking](https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#getting-a-sponsor), but as an alternative there could just be a [package repository setup](https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#distributing-packages-yourself) to distribute the deb file, which is what even the Dart SDK does and pretty much the same as having to add the custom tap for homebrew users.

I'm a Ubuntu and Debian user so I can put up my hand to create a deb package repository, I'm guessing FVM can be compiled into a AOT standalone binary so it should be a fairly simple deb package.

**Comment by maks** [comment]
Actually since fvm uses [cli_pkg](https://pub.dev/packages/cli_pkg) its [in the same boat as dart_sass](https://github.com/sass/dart-sass/issues/1164) so really I think the best idea would be to contribute support for debian packages to cli_pkg and I guess @leoafarias that would tie in nicely with your existing CI/CD process for fvm?

**Comment by leoafarias** [comment]
@maks that is correct, I believe this would be the best route
