### ISSUE TITLE
[BUG] I Cant install flutter 2.2.3

### ISSUE THREAD

**Issue by toshiossada** [leoafarias/fvm#344]
I Cant install Flutter 2.2.3
When I ran `fvm install 2.2.3` I got `2.2.3 is not a valid Flutter channel or release`
![image](https://user-images.githubusercontent.com/2637049/133433057-4a58ac7c-b2d2-4eda-8ab9-5dfec715b7ea.png)
In releases list `fvm releases` don't has a 2.2.3 version
![image](https://user-images.githubusercontent.com/2637049/133433395-5ed2cb89-1195-435f-8f0b-be2069583c4d.png)

**Comment by leoafarias** [comment]
@toshiossada please make sure you are using the latest version of fvm, flutter had deprecated the UrL that checked for releases.

**Comment by leoafarias** [comment]
Will close this issue, as its solved once you update FVM

**Comment by toshiossada** [comment]
How I do?
![image](https://user-images.githubusercontent.com/2637049/133435763-68c4ce92-5205-4794-987d-3fc26cf50f96.png)

**Comment by toshiossada** [comment]
Ok, I've uninstall slidy, ran `choco upgrade fvm` an after re-installed slidy and thats works

**Comment by leoafarias** [comment]
Great @toshiossada!
