### ISSUE TITLE
Can FVM be used to proxy flutter commands headlessly, automatically using the version defined by fvm_config.json?

### ISSUE THREAD

**Issue by jjoelson** [leoafarias/fvm#345]
I'm not sure if this is the appropriate venue for a question, so please let me know if I should post this somewhere else.

Is there a way to use fvm headlessly (e.g. in a CI build script) such that the version defined for the project in `fvm_config.json` is automatically used? The issue I'm currently seeing is that if I try to call `fvm flutter <command>` when the version is not installed, then fvm asks for a confirmation:
```
$ fvm flutter <command>
Flutter "2.2.0" is not installed.
Would you like to install it? Y/n: 
```

I could do something hacky like this for all of my flutter commands, but it doesn't feel very good.:
```
echo Y | fvm flutter analyze
```

Due to https://github.com/leoafarias/fvm/issues/334, it seems there is no straightforward way to determine the current version and install it at the start of a CI pipeline.

**Comment by leoafarias** [comment]
@jjoelson if you run the command `fvm install`, it will automatically install the version that is configured on the project config. I suggest running that  before `fvm flutter analyze`

**Comment by jjoelson** [comment]
@leoafarias So simple! Thank you!
