### ISSUE TITLE
[Feature Request]How do I configure multiple environments?

### ISSUE THREAD

**Issue by Pluto1219** [leoafarias/fvm#346]
![image](https://user-images.githubusercontent.com/15402976/133928978-afce64cf-5c4e-45ee-aeea-2f88b3743b13.png)

**Comment by leoafarias** [comment]
@Pluto1219 will need a bit more context on the item above. I am not an android studio user. 

If it helps FVM does have the concept of flavors also for environments. 

https://fvm.app/docs/guides/project_flavors

**Comment by leoafarias** [comment]
@Pluto1219 will go ahead and close this issue. Please feel free the reopen if you still need help
