### ISSUE TITLE
[BUG] FVM_HOME is read relative to the current working directory

### ISSUE THREAD

**Issue by jld3103** [leoafarias/fvm#347]
**Describe the bug**
`FVM_HOME` is read relative to the current working directory and not relative to the directory that contains the config directory. This is confusing because you can not use a relative path for the `FVM_HOME` directory if you work with a monorepo.

**To Reproduce**

1. `export FVM_HOME=".fvm/cache"`
2. `fvm install`
3. `cd some-sub-directory`
4. `fvm install`

**Expected behavior**
fvm should find the installed flutter version in the top directory that contains the config directory and is the base for the `FVM_HOME` directory and not install the version again in the sub directory.

**Desktop:**
- OS: linux
- FVM Version 2.2.3

**Additional context**
I found this issue with a CI pipeline where each job goes into a sub directory, but they share the same `FVM_HOME` directory variable and should use the cached flutter version from there.

**Comment by leoafarias** [comment]
@jld3103 Sorry for the delay on this.  

I believe this is working as expected. FVM needs to support, external drives, and so on.  Would not using the relative path `.fvm/cache` solve your problem? I am try to understand the use case for this a bit better.

**Comment by jld3103** [comment]
We have a monorepo with multiple flutter and dart apps that are in different sub-directories (also different levels). We have a single fvm install at the root of the monorepo. If we run fvm in any of these apps it finds the config file correctly by traversing the path, but it then installs the sdk relative to the current working directory. That means we have it multiple times, but we actually only want to have it once at the root of the monorepo. I hope you understand now what I mean otherwise I can make an example repo with the exact structure we have (ofc a bit simplified).

**Comment by leoafarias** [comment]
@jld3103 I think I understand. One thing to keep in mind is that all that all it is added to each “package” is a symlink, to the same cache version, so its not really adding any overhead.

**Comment by leoafarias** [comment]
Closing this since I believe it addresses the concern about multiple "caches". Please feel free to open if you have any questions.
