### ISSUE TITLE
'fvm flutter pub cache clean' deactivates fvm

### ISSUE THREAD

**Issue by jamesncl** [leoafarias/fvm#349]
I have been using FVM on Windows for 2 projects with different versions of flutter (1.22.6 and 2.5.0) by doing the following:

- Installing Dart SDK via choco
- `dart pub global activate fvm`
- `fvm use <version>` in the project root
- Configured android studio to use the symbolic link in the .fvm folder via Languages & Frameworks -> Flutter

I've been using it with no problems for a few weeks now. Today I had a problem where I removed a dependency from my `pubspec.yaml`, did a `fvm flutter pub get`, but the dependency still seemed to be there - I could still import the package. So, I decided to try cleaning the pub cache using `fvm flutter pub cache clean`, which resulted in:

> This will remove everything inside C:\Users\james\AppData\Local\Pub\Cache.
> You will have to run `flutter pub get` again in each project.
> Are you sure? (y/N)? y
> Removing pub cache directory C:\Users\james\AppData\Local\Pub\Cache.
> The system cannot find the path specified.
> No active package fvm.
> The system cannot find the path specified.

After this I can no longer run FVM commands as it is not found. Running `dart pub global activate fvm` again solves the problem.

Is this expected behaviour, a bug, or does it suggest my setup is wrong? Would appreciate if someone else could try this command and report on what happens.

**Comment by leoafarias** [comment]
@jamesncl If you are using the dart version in cache I believe this will be the case..  could you try installing using chocolatey? See if the behavior persists in this case?

**Comment by jamesncl** [comment]
Sorry for the late reply, yes as stated in the original post I installed dart via chocolately. I did originally used the dart which came packaged with flutter, before I switched over to using FVM. When switching over to FVM I removed my existing installations of flutter first, so I had to install dart separately. Hope that makes sense.

I'm not sure what you mean by "the dart version in cache"?

Also, I just checked my PATH env variable and I have the following entries - I don't remember adding these, are these added by FVM automatically?

`C:\Users\james\AppData\Roaming\Pub\Cache\bin` (this directory doesn't exist)

`C:\Users\james\AppData\Local\Pub\Cache\bin` (this directory does exist, it contains fvm.bat and dectools.bat)

**Comment by leoafarias** [comment]
@jamesncl fvm does not add any environment variables, I think that is not even possible. However, these are the configuration instructions to use pub global from their guide.

**Comment by jamesncl** [comment]
Okay thanks, maybe I added them earlier and forgot. Are you able to reproduce this issue, i.e. does running `fvm flutter pub cache clean` on your system result in the same problem I encountered?

**Comment by leoafarias** [comment]
@jamesncl Not sure if its really an issue, once you run that command flutter warns you of the following.

```This will remove everything inside /Users/leofarias/.pub-cache.
You will have to run `flutter pub get` again in each project.
Are you sure? (y/N)? y```

On global it means you have to reinstall globally also which I think its the equivalent of the flutter pub get. Using brew helps you solve this problem.

**Comment by RomanKapshuk** [comment]
I have an alike issue. As a result of `fvm flutter pub cache repair` i get


```
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
  exit(await FvmCommandRunner().run(args));
             ^^^^^^^^^^^^^^^^
Failed to reactivate fvm 2.2.3: Failed to build fvm:main:
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:3:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
../../.pub-cache/hosted/pub.dartlang.org/fvm-2.2.3/bin/main.dart:6:14: Error: Method not found: 'FvmCommandRunner'.
  exit(await FvmCommandRunner().run(args));
             ^^^^^^^^^^^^^^^^
Binstubs exist for non-activated packages:
  From fvm: fvm
Reactivated 1 package.
Failed to reactivate 1 package:
- fvm
pub finished with exit code 69

```

**Comment by jamesncl** [comment]
@leoafarias Ah I see - so FVM is actually a dart package which is installed in the system package cache when we run `dart pub global activate fvm`. So yes it does make sense that cleaning the cache also basically deletes FVM. So I agree this is not really an issue, it's expected behaviour. I wonder if this is worthy of a small note in the docs?

**Comment by jamesncl** [comment]
@RomanKapshuk That's a different problem and might be worth opening a separate issue - it makes sense that `cache clean` deactivates FVM as it is itself a package in the cache, but it doesn't make sense that `cache repair` can't repair FVM, so that sounds like a more serious issue

**Comment by leoafarias** [comment]
@jamesncl if you can make any suggestions to the docs and do a PR, I will be able to review.
