### ISSUE TITLE
[QUESTION] Is npm/go install still valid?

### ISSUE THREAD

**Issue by ryan-sf** [leoafarias/fvm#35]
I found an [old post](https://flutterawesome.com/flutter-version-management-a-simple-cli-to-manage-flutter-sdk-versions/) that says you can install fvm using npm, yarn, or go, but the npm version is behind the current pub version.

Is it still possible to do this?

**Comment by leoafarias** [comment]
The npm version is no longer valid. I will make it more explicit. The version before was written on Go so the installation process was a bit more complicated. How Pub global is as easy as npm.
