### ISSUE TITLE
[BUG] flutter install returns 0.0.0-unknown regression

### ISSUE THREAD

**Issue by staminna** [leoafarias/fvm#350]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.

- [x] Run `fvm doctor` if possible and add the output to the issue.

$ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Describe the bug**
Trying fvm to have multiple flutter versions per project.
This seems like a regression, since I already saw the same issue but it is closed.

**To Reproduce**
 Installing with fvm install 2.0.0 I get 0.0.0-unknown.

FVM Settings:
Located at /Users/jorgenunes/fvm/.settings

skipSetup: false
gitCache: false

$ sudo fvm install 2.0.0

Flutter "2.0.0" is not installed.

Installing version: 2.0.0...
A clonar em '/Users/jorgenunes/fvm/versions/2.0.0'...
remote: Enumerating objects: 337101, done.        
remote: Counting objects: 100% (204/204), done.        
remote: Compressing objects: 100% (119/119), done.        
remote: Total 337101 (delta 93), reused 137 (delta 63), pack-reused 336897        
A receber objetos: 100% (337101/337101), 163.10 MiB | 8.53 MiB/s, concluído.
A resolver deltas: 100% (259226/259226), concluído.
HEAD está agora em 60bd88df91 enable build test, roll engine, flag flip (#77154)
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
Downloading Dart SDK from Flutter engine 40441def692f444660a11e20fac37af9050245ab...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  194M  100  194M    0     0  11.4M      0  0:00:17  0:00:17 --:--:-- 11.8M
Building flutter tool...
Failed to find the latest git commit date: VersionCheckError: Command exited with code 1: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard out: 
Standard error: xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.

Returning 1970-01-01 01:00:00.000 instead.
Flutter 0.0.0-unknown • channel unknown • unknown source
Framework • revision  () • 1970-01-01 01:00:00.000
Engine • revision 40441def69
Tools • Dart 2.12.0

**Expected behavior**
Should install flutter 2.0.0

**Logs**
 Not providing additional details

- macOS Catalina
- FVM Version 2.2.3

After repairing the cache, I have different error:

fvm install 2.0.0
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
Flutter failed to open a file at "/Users/jorgenunes/fvm/versions/2.0.0/bin/cache/lockfile". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

**Comment by staminna** [comment]
I went ahead and found out about Sidekick. Locks awesome!
[print screen](https://www.dropbox.com/s/5vithda6ksbh98g/Screenshot%202021-09-28%20at%2018.41.19.png?dl=0)

$ cat .bash_profile | grep "fvm"
f="fvm flutter"
d="fvm dart"
export PATH="$PATH:/Users/myusername/fvm/default/bin"

$ fvm doctor

No FVM config found:
/Users/myusername
Fvm will run the version in your PATH env: /usr/local/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/usr/local/bin/flutter

Dart:
/usr/local/bin/dart

FVM_HOME:
not set

**Comment by staminna** [comment]
I know it should be working properly but it's not on my macOS Catalina.
Besides the logs, what other information do you need?
I think it's something wrong in the PATH. Can you check the setting above and see if it's .bash_profile?
Should you require more information, I will be happy to assist you.

**Comment by leoafarias** [comment]
Not sure.  Why are you using sudo?

**Comment by staminna** [comment]
I tried sudo after standard installation guides because it could be wrong permissions. Same output.
There is an empty PATH setting though. Thinking it should have a set.
I will remove and reinstall from scratch and let you know.  Please don't clone just yet.

**Comment by leoafarias** [comment]
That path should not impact this. One thing that would impact is not using the latest version of fvm. Can you make sure you are using the latest?

**Comment by staminna** [comment]
I had the latest version. 
Only missed that Xcode was a dependency I did not wish to install because I was low on disk space.
Thanks for input
