### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by staminna** [leoafarias/fvm#351]
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
Done
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
macOS
- [x] Run `fvm doctor` if possible and add the output to the issue.

$ fvm doctor

FVM Version: 2.2.3
___________________________________________________

FVM config found:
___________________________________________________

Project: GeoFlutterFire
Directory: /Users/jorgenunes/Mobile/qteye/GeoFlutterFire
Version: 2.0.0
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: /Users/jorgenunes/fvm/versions/2.0.0
Channel: false
SDK Version: 2.0.0

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /Users/jorgenunes/Mobile/qteye/GeoFlutterFire/.fvm/flutter_sdk

Configured env paths:
___________________________________________________

Flutter:
/usr/local/bin/flutter

Dart:
/usr/local/bin/dart

FVM_HOME:
not set

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Run `fvm install 2.0.0`...
3. flutter --version
4. See error:
$ fvm install 2.0.0
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (7 months ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
MacBook-Pro-de-Jorge:GeoFlutterFire jorgenunes$ flutter --version
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Expected behavior**
Should see flutter 2.0.0

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- macOS Catalina
- FVM Version [e.g. 22]
- 2.2.3

Sidekick can see version 2.0.0 assigned to project successfully.

I think the problem is setting FVM_HOME  to somewhere. What is the recommended path for macOS? 
I will define on .bash_profile

**Comment by leoafarias** [comment]
@staminna This is not a bug. If you want to use the `flutter` command instead of the `fvm flutter` routing you have to read the configuration on how to set it as a global. https://fvm.app/docs/guides/global_version

**Comment by keylinwu** [comment]
Correction, for fvm global configuration please refer to this link https://fvm.app/documentation/guides/global-configuration
