### ISSUE TITLE
[BUG] Flutter git automatically adds to the Version Control

### ISSUE THREAD

**Issue by bartlomiejszm** [leoafarias/fvm#354]
**Describe the bug**
Flutter git source adds automatically to the Android Studio Version Control, resulting in uncontrolled flutter version change.
After using `git pull` without removing this source we are able to update the flutter without knowing i.e. version 2.2.3 -> 2.5.3, FVM still acts as if we are using version 2.2.3 but `flutter --version` shows version 2.5.3.

**To Reproduce**
1. In any project with external git source add fvm by `fvm use <version>`
2. Fetch changes from source
3. Not always but often flutter gets updated to the newest possible version

**Expected behavior**
it would be nice to have the flutter git ignored or at least set to never update

**Comment by leoafarias** [comment]
@bartlomiejszm sorry for the delay on this. I was not able to replicate this behavior, are you using.

What for client are you suing for the pull?

**Comment by Fasuh** [comment]
@leoafarias sorry as well for forgetting about this case.
I am using AndroidStudio, always when creating a new `fvm` folder i have to ignore its origin from the list of VCS. i am unsure if we can do anything about this because it gets a bit frustrating to have to remove a whole installed version because it upgraded itself.

**Comment by leoafarias** [comment]
The only thing I can't think of is to automatically add .fvm/flutter_sdk to gitignore on first setup on a project

**Comment by Fasuh** [comment]
It does not help since inside `.fvm/flutter_sdk` is considered a different origin, i am ignoring the `flutter_sdk` folder by default in my projects

**Comment by leoafarias** [comment]
@Fasuh can you share how are you ignoring flutter_sdk on Android Studio?

**Comment by Fasuh** [comment]
![image](https://user-images.githubusercontent.com/39801418/144506557-1a2bd696-3572-418b-8213-dce265076a45.png)
in the settings there is a "-" button on the right which allows me to "ignore" roots, which basically as far as i can tell just adds an xml to the `.idea/workspace.xml`

```
  <component name="VcsManagerConfiguration">
    <ignored-roots>
      <path value="$PROJECT_DIR$/.fvm/flutter_sdk" />
    </ignored-roots>
```

**Comment by leoafarias** [comment]
I have updated the documentation with that information

**Comment by Giuspepe** [comment]
Sure @leoafarias, I have created a PR here https://github.com/fluttertools/fvm/pull/430
