### ISSUE TITLE
[Feature Request] Embed SDK version in app during build phase

### ISSUE THREAD

**Issue by mrdc** [leoafarias/fvm#356]
Hello,

Would be nice to be able to include SDK version in app which was used during build, so it can be checked later during runtime.
For example, I have multiple versions of flutter and sometimes it's not clear which version Xcode uses during build.
With built-in version it will be easy to verify that everything is fine.

**Comment by leoafarias** [comment]
@mrdc the version of SDK is symlinked within the project. `.fvm/flutter_sdk` The version of the SDK most likely will never be "included" within the project, as this creates a lot of different challenges

**Comment by mrdc** [comment]
> I did some research and could not find anything that does that. I will ask around a bit.

I thought that dart/flutter has something similar to C++ where it's possible to include custom info during compilation.

**Comment by kuhnroyal** [comment]
You can use `--dart-define=SOME_VAR=SOME_VALUE --dart-define=OTHER_VAR=OTHER_VALUE` but I don't see FVM automatically setting something here.
