### ISSUE TITLE
[BUG] Update install to state dart should be installed globally

### ISSUE THREAD

**Issue by ryan-sf** [leoafarias/fvm#36]
**Describe the bug**

Currently the docs assume that the user has Dart installed globally.  Should probably add some verbiage to explicitly say that or add instructions for when you're only using the Flutter installed version.

**To Reproduce**
1. Run install commands without having Dart installed globally with `.pub-cache` added to path.

**Expected behavior**
Expect the documentation to reflect missing steps and account for users who only have the Dart version shipped with Flutter installed.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - FVM Version [e.g. 22]: 0.6.6

**Additional context**
n/a

**Comment by leoafarias** [comment]
@ryan-sf I am looking into improving this. Maybe having a binary that gets shipped would be best, but still not 100% sure what is the best way to approach this.

**Comment by ryan-sf** [comment]
I like the idea of a binary. Right now I get tons of warnings about using two versions of Flutter that I just ignore.
