### ISSUE TITLE
[BUG] Flutter 2.5?

### ISSUE THREAD

**Issue by iyobo** [leoafarias/fvm#360]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Run `fvm use stable`...
3. Check...

**Expected behavior**

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- FVM Version [e.g. 22]
- If Windows: Which Powershell are you using?

**Additional context**

**Comment by leoafarias** [comment]
@iyobo can you provide a proper description of what is happening and also the information requested in  the template

**Comment by leoafarias** [comment]
Will close this for now. Please open a new issue with a more detailed description and I will be happy to help you out.
