### ISSUE TITLE
[Feature Request] Option to silence output to stdout / logging

### ISSUE THREAD

**Issue by zarko-tg** [leoafarias/fvm#361]
**Is your feature request related to a problem? Please describe.**

Yes, there's a problem if say you want to run some Dart CLI program, whose goal is to write something to the stdout, a result that might be used by something else later. The problem is that FVM is doing at least some logging and thus "polluting" the stdout in this scenario. This line for example:
[FvmLogger.info('fvm: running Dart from Flutter "$version"\n');](https://github.com/leoafarias/fvm/blob/88b5514736796e204f73061ff3bd981065e955f2/lib/src/commands/dart_command.dart#L30)

**Describe the solution you'd like**

A way to silence any logging from FVM, an option such as -s / --silent or similar.

**Describe alternatives you've considered**

Calling dart directly, with downside being that one needs to hardcode the path and not use "fvm dart ...".

**Comment by leoafarias** [comment]
@zarko-tg I believe I had done this already for the flutter command.

If you want you can do a PR using the logger.trace as it shown here and I can review.

https://github.com/leoafarias/fvm/blob/main/lib/src/commands/flutter_command.dart

If not I should be able to get to it over the weekend.

**Comment by zarko-tg** [comment]
Now that went quickly, cheers!
