### ISSUE TITLE
[BUG] VSCode terminal does not find flutter

### ISSUE THREAD

**Issue by mtxphil** [leoafarias/fvm#369]
**Before creating a bug report please make check the following**

When a terminal window is opened in VSCode, flutter command is not available.  

**To Reproduce**
Install fvm, perform setup, 

**Expected behavior**
I am expecting, hoping that the terminal window in VSCode would use the same flutter version as the project configuration.

- OSX 12.0.1
- FVM Version 2.2.4

**fvm doctor**
```
FVM Version: 2.2.4
___________________________________________________

FVM config found:
___________________________________________________

Project: tap-flutter
Directory: /Users/michaelblood/Documents/tap/tap-flutter
Version: 2.2.3
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: /Users/michaelblood/fvm/versions/2.2.3
Channel: false
SDK Version: 2.2.3

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /Users/michaelblood/Documents/tap/tap-flutter/.fvm/flutter_sdk


Configured env paths:
___________________________________________________

Flutter:


Dart:
/opt/homebrew/bin/dart

FVM_HOME:
not set
```

**Comment by leoafarias** [comment]
@mtxphil Please review this https://fvm.app/docs/getting_started/configuration

**Comment by mtxphil** [comment]
I have reviewed the configuration document again.  
when running a terminal from VSCode, there is not flutter available in the PATH.

```
fvm doctor 

FVM Version: 2.2.4
___________________________________________________

FVM config found:
___________________________________________________

Project: buddhaPath
Directory: /Users/phil/Documents/projects/buddhaPath
Version: 2.2.3
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: /Users/phil/fvm/versions/2.2.3
Channel: false
SDK Version: 2.2.3

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /Users/phil/Documents/projects/buddhaPath/.fvm/flutter_sdk


Configured env paths:
___________________________________________________

Flutter:


Dart:
/usr/local/bin/dart

FVM_HOME:
not set
```

as a work-around, I am using the following in .bash_profile to add flutter when the VSCode terminal is run from a project.  
```bash
# setup project flutter version
if [[ -d .fvm/flutter_sdk ]]
then
    FLUTTER_PATH="`pwd`/.fvm/flutter_sdk/bin"
    export PATH="$FLUTTER_PATH:$PATH"
fi
```

**Comment by mtxphil** [comment]
Thank you very much for the assistance.  I did not fully understand the instructions.

**Comment by leoafarias** [comment]
> Thank you very much for the assistance. I did not fully understand the instructions.

@mtxphil let me know how I can improve the docs. To summarize to use `flutter` from terminal it needs to be configured in the PATH. Fvm does not do that automatically for you. Your option is to have `flutter` by just following the Flutter installation instructions, or fvm does allow you to have dynamic switching by point the PATH to a "dynamic" symlink directory.

This allows to preserve the dynamic switching on the "global" level.
