### ISSUE TITLE
[Feature Request] Add command to print out current verion of fvm

### ISSUE THREAD

**Issue by ryan-sf** [leoafarias/fvm#37]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy way to see what version of fvm is installed.  This is useful information when reporting bugs.

**Describe the solution you'd like**
Would like a `version` command to be added that would print out the latest installed version.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by leoafarias** [comment]
#42 closes this
