### ISSUE TITLE
[BUG] Could not find a command named "global".

### ISSUE THREAD

**Issue by somdipdey** [leoafarias/fvm#371]
**Describe the bug**
I am trying to set the flutter version to 1.17.4, however, when I use `fvm global 1.17.4` it's giving me the error: `Could not find a command named "global".`
**To Reproduce**

Following are the results of my commands:

`$flutter --version`
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

`$fvm global 1.17.4`
Could not find a command named "global".

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Set configuration for FVM
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.

**Expected behavior**
I am trying to set the global flutter version to 1.1.7.4 as per docs: https://fvm.app/docs/guides/global_version

**Logs**

`$fvm --verbose`
Flutter Version Management: A cli to manage Flutter SDK versions.

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Set configuration for FVM
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.

`$fvm global --verbose`
Could not find a command named "global".

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Set configuration for FVM
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.
#0      CommandRunner.usageException (package:args/command_runner.dart:95:7)
#1      CommandRunner.runCommand (package:args/command_runner.dart:163:13)
#2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#3      new Future.sync (dart:async/future.dart:223:31)
#4      CommandRunner.run (package:args/command_runner.dart:112:14)
#5      fvmRunner (package:fvm/src/runner.dart:35:18)
#6      main (file:///Users/somdipdey/.pub-cache/hosted/pub.dartlang.org/fvm-1.3.7/bin/main.dart:6:9)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Unhandled exception:
Could not find a command named "global".

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Set configuration for FVM
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.
#0      CommandRunner.usageException (package:args/command_runner.dart:95:7)
#1      CommandRunner.runCommand (package:args/command_runner.dart:163:13)
#2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#3      new Future.sync (dart:async/future.dart:223:31)
#4      CommandRunner.run (package:args/command_runner.dart:112:14)
#5      fvmRunner (package:fvm/src/runner.dart:35:18)
#6      main (file:///Users/somdipdey/.pub-cache/hosted/pub.dartlang.org/fvm-1.3.7/bin/main.dart:6:9)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Desktop (please complete the following information):**

- OS: MacOS Big Sur 11.4 (20F71)
- FVM Version 1.3.7

**Comment by leoafarias** [comment]
@somdipdey version 1.3.7 of FVM does have the `global` command.

**Comment by somdipdey** [comment]
@leoafarias Thank you for your reply on this. I have seen the docs and it also mentions that but as you can see from the options, the global command isn't there. Is there something which might be missing from my version because it's a bit weird?!

**Comment by leoafarias** [comment]
What I mean is that the version you are running of fvm does not have the global command feature.

Most likely because of the dart sdk used when activating is old. Update dart and deactivate fvm

**Comment by somdipdey** [comment]
@leoafarias I checked the flutter/dart version and they seem to be the (almost) latest on the system. The result as follows:

```
$flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

For this particular project when I use the following:
```
$fvm use 1.17.4
Project now uses Flutter: 1.17.4
```

However, if I use the `flutter --version` command then the system is still using 2.5.3 instead of the specified version 1.17.4.

My current nvm version as follows:
```
$fvm version
1.3.7
```

**Comment by leoafarias** [comment]
@somdipdey can you reinstall fvm to see if you get the latest version?

if that does not work run “fvm doctor”

**Comment by leoafarias** [comment]
Closing the issue. If you need assistance feel free to reopen.
