### ISSUE TITLE
When having Plugins in project, Flutter version not working when running "build apk"[BUG]

### ISSUE THREAD

**Issue by AleFachini** [leoafarias/fvm#373]
**Issue Description**
using fvm flutter version when building apk, the plugins inside my project do not find some classes inside the flutter version used in fvm
Also, when debugging on virtual device after flutter clean it works ok. 
It just fails when building APKs

**To Reproduce**
you need a project with plugins so its hard to reproduce

1. run fvm flutter build apk --release

**Expected behavior**
creation of the apk

**Logs**

**Desktop (please complete the following information):**

- OS: [Android]
- FVM Version [e.g. 223]
- If Windows: Which Powershell are you using? CMD as ADMIN

**Additional context**
what i did was checkout flutter 1.22.6 on the oficial SDK (installed in C:\flutter) and it worked and build, on the project, i changed back the sdk path from fvm path to c:flutter.

So what should be the problem?

**Comment by leoafarias** [comment]
@AleFachini I would need more information on this, but could it be because of some API changes between the SDK versions?

**Comment by AleFachini** [comment]
What i did was downgrade flutter sdk to the same version and  with that compiled OK, then changed the configuration of the project to fvm version again and now I dont have problems 
using "fvm flutter" commands no problem and also pointing to the version inside fvm folder again in my project

**Comment by leoafarias** [comment]
great will go ahead and close this issue then.
