### ISSUE TITLE
FVM COM SLIDY

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [leoafarias/fvm#374]
Bom dia, fiz da seguinte maneira instalei o dart via brew, ativei o fvm , instalou via fvm os sdk flutter que vou usar, ativei o slidy na versao que me projeto precisa mas  deu erro
`diegolimeiradasilva@MacBook-Pro-de-Diego fixtoc %  slidy run mobx_build 
Can't load Kernel binary: Invalid kernel binary format version.
Building package executable... (1.2s)
Failed to build slidy:main:
../../../../../../.pub-cache/hosted/pub.dartlang.org/dart_console-0.6.2/lib/src/ffi/win/termlib-win.dart:28:25: Error: The getter 'addressOf' isn't defined for the class 'CONSOLE_SCREEN_BUFFER_INFO'.
 - 'CONSOLE_SCREEN_BUFFER_INFO' is from 'package:win32/src/structs.dart' ('../../../../../../.pub-cache/hosted/pub.dartlang.org/win32-1.7.4+1/lib/src/structs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
    ffi.free(bufferInfo.addressOf);`

tentei instalar o slidy sem usar o fvm flutter deu outro erro
`diegolimeiradasilva@MacBook-Pro-de-Diego fixtoc %  slidy run mobx_build
/bin/sh: flutter: command not found

ERROR: flutter clean
/bin/sh: flutter: command not found

ERROR: flutter pub get
/bin/sh: flutter: command not found

ERROR: flutter pub run build_runner build --delete-conflicting-outputs`

**Comment by leoafarias** [comment]
@DiegoLimeiradaSilva acredito que esse erro nao e do FVM. Isso pode acontecer pq o slidy foi compilado com outra versão do Dart. Eu sugiro reinstalar o slidy.
