### ISSUE TITLE
How to setup fvm in Xcode

### ISSUE THREAD

**Issue by raymondnexsoftech** [leoafarias/fvm#376]
Sometimes I would like to run an app in Xcode, or need to build an archive to app store.
By testing in Xcode, it seems cannot get the fvm setting.
So I would like to know if anyway to use fvm in Xcode
Thanks

**Comment by leoafarias** [comment]
@raymondnexsoftech hmm I am not familiar with the need for this. Flutter offers a command `flutter build ipa` and you can read more about it here.

https://docs.flutter.dev/deployment/ios#create-a-build-archive-with-xcode

As far as running the Flutter app from Xcode, I am not sure what the behavior on this, but probably is configured to `global` or path version.

**Comment by rostopira** [comment]
Open Xcode, Build phase, and inside `Run script` add line
```sh
export FLUTTER_ROOT="$PROJECT_DIR/../.fvm/flutter_sdk"
```
