### ISSUE TITLE
[BUG]: incorrect instructions for VS Code settings

### ISSUE THREAD

**Issue by ryan-sf** [leoafarias/fvm#38]
**Describe the bug**
When following the instructions for configuring VS Code, the version switcher fails to locate the installed versions.

**To Reproduce**
1. Add `"dart.flutterSdkPaths": ["fvm"]` to VS Code settings
2. Click on dart version
3. Observe that version switcher fails to display, or displays only current version.

**Expected behavior**
Change the dart.flutterSdkPaths from `fvm` to `~/fvm/versions`

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - VS Code: v1.40.2
 - FVM Version [e.g. 22]: v0.6.6

**Additional context**

**Comment by leoafarias** [comment]
@ryan-sf i believe the instructions is correct the local the project ‘fvm’ symlinks to the current ~/fvm/versions.

Do you mind going into a bit more detail what you expected and where it fails?

**Comment by chimon2000** [comment]
I was having issues where vs code could not correctly locate my versions until I changed the path. I will retest.

**Comment by orestesgaolin** [comment]
For some reason even though I have selected `stable` version with `fvm use stable` VS Code uses `dev` version of Flutter. The only thing I set was this SDK path in settings.json to `fvm`.
