### ISSUE TITLE
Uninstall instructions?

### ISSUE THREAD

**Issue by whiplashoo** [leoafarias/fvm#380]
Are there anywhere instructions for properly uninstalling `fvm`? 

I don't need to use it for a dev machine, so I followed these steps to uninstall:

- `dart pub global deactivate fvm`
- Deleted the `.fvm` folders in my projects' root.
- Deleted the `fvm` directory under my home ($HOME) folder (it's a Mac).

Is there anything else to be done to remove it completely?

**Comment by leoafarias** [comment]
I might create a `destroy` command. But for now, I have updated the FAQ
https://fvm.app/docs/guides/faq#how-to-uninstall-fvm

**Comment by AngelDevXiii** [comment]
i still cant delete it

- ran dart pub global deactivate fvm
-i deleted the fvm folder on my machine (on my username folder, its a mac)
-i ran the fvm destroy
-i deleted the fvm paths from the zshrc

but if i run fvm in the terminal it still recognizes the command and can be used. i want to delete it completly.
