### ISSUE TITLE
[Feature Request] Make it possible to use a commit as a version

### ISSUE THREAD

**Issue by jld3103** [leoafarias/fvm#382]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to use the master branch for the latest changes, but also want to pin the used version at the same time. Just using `master` as the version does not work in this case.

**Describe the solution you'd like**
I would like to be able to use a commit hash as the version in the config file.

**Comment by leoafarias** [comment]
We currently support this functionality. You can read more about it here https://fvm.app/docs/advanced/install_revision

**Comment by jld3103** [comment]
Hm maybe the commit hash was wrong. Sorry for the nose!
