### ISSUE TITLE
What version of dart to use? Because the current one is giving an error with dart 2.10.5

### ISSUE THREAD

**Issue by EwertonDutra** [leoafarias/fvm#387]
Uso windows 10 (21H2)
FVM 2.2.6

I installed like this:
`choco install fvm`

After I installed it, it worked! After restarting (notebook) it no longer works

Problem:
<img width="611" alt="2022-02-14" src="https://user-images.githubusercontent.com/13201575/153899719-6c012d07-3ce7-4d42-b132-26cd68422712.png">

Kind regards

**Comment by leoafarias** [comment]
@EwertonDutra sorry for the delay on this, seems this issue fell through the cracks. When updating dart sometimes you have to reinstall FVM, or any other global installed packages

**Comment by EwertonDutra** [comment]
Now with your comment I decided to test the FVM again
Oh it worked now, it didn't give the error message again

Thanks for the feedback 😅
