### ISSUE TITLE
[Feature Request] Use a different way to distinguish flutter version to use

### ISSUE THREAD

**Issue by rchavik** [leoafarias/fvm#39]
Current way to differentiate flutter version to use is by creating a symlink in the root project directly.
Unfortunately this symlink uses absolute path, and it does not make sense to commit it into git repo.

A solution that comes to mind is like what [`nodenv`](https://github.com/nodenv/nodenv) uses.  It stores the version to use in `.node-version` file in the root project.  This file contains a version string, and contains no path.  So it can be commited to git.

The nodenv package also provides a`node` executable in `~/.nodenv/shims/node` that then calls the requested version `node` binary.

**Comment by Prathik-Jain** [comment]
Hi @rchavik, I agree that symlinks is not something to be used. Would you please explain the benefits of pushing the flutter version to git? Is it because you want the team to stay on the same page?

According to me a better approach would be something like what the nvm (node version manager) does. which is it edits the `PATH` every time the `use` command is executed.
https://github.com/nvm-sh/nvm/blob/6fa92c82caef03081de0adca99f6256e5fd209ca/nvm.sh#L2983

This might also be an option to fix the issue #21.
In this case we can soft link the existing flutter directory to the fcm cache dir, and use it by default.

**Comment by rchavik** [comment]
> Would you please explain the benefits of pushing the flutter version to git? Is it because you want the team to stay on the same page?

Yes. That is my objective.

> According to me a better approach would be something like what the nvm (node version manager) does. which is it edits the PATH every time the use command is executed.

I used nvm before but switch to nodenv after I got tired of the slow loading times on all my terminals after cold boot.   However, this approach is also worth considering.

Please note that `nodenv`'s `node-version` is more like `nvm`'s `.nvmrc` where you specify which `node` version to use.

For `nvm`, afaik it requires manual command `nvm use` OR with some tweaks in your shell [init scripts](https://github.com/nvm-sh/nvm#automatically-call-nvm-use)

For `nodenv`,  `~/.nodenv/shims/node` uses the file to determine the version to use.  Thus, version selection is 'automatic' when calling `node` in a directory with this file.  This is one thing I like about it.

**Comment by leoafarias** [comment]
Good discussion. I am interested in improving where we can. Maybe improving the reference file together with current version would at least allow to install the needed flutter version.

Will look into a bit more detail later

**Comment by Prathik-Jain** [comment]
I am open for contribution. I can start working once we decide what we want to do.
Thanks @leoafarias

**Comment by leoafarias** [comment]
@Prathik-Jain I am open to a PR on this. I think the best approach is to have a `.fvm` file that contains the version instead of being a symlink. 

FVM can then look for the version that is currently installed and if its not installed it can go ahead and install it.

**Comment by Prathik-Jain** [comment]
@rchavik, can you please post a example of `.nodenv`?

**Comment by Prathik-Jain** [comment]
ok found a couple of `.nodenv`

https://github.com/s-wirth/DungeonsRevenge/blob/4fb20d06a4e20e4c77700582fac24fd64f4e2581/.nodenv

https://github.com/ShayDavidson/ShayDavidson.github.io/blob/ae38e83f1fb7497e0ce1fc37278850b4dd43776a/.nodenv

https://github.com/hfu/rfc8142-check/blob/dd62574c933cd73fc175e8d64eea42181de8f33b/.nodenv

It holds the version number and nothing else. Correct me if I am wrong.

**Comment by Prathik-Jain** [comment]
@leoafarias, How do we keep track of channels? For now I see that fvm only takes care of channel/version and not both.

`fvm use 1.12.0` would work
`fvm use 1.9.0 beta` wouldn't work

right?

**Comment by leoafarias** [comment]
@Prathik-Jain It will get any tagged versions from the Flutter repo. That is mostly stable releases and hotfix releases. https://github.com/flutter/flutter/releases?after=v1.9.1

What would be the use case for this if a lot of the channels are unstable and nightlies?

**Comment by leoafarias** [comment]
Also to be honest I don’t think it can be done is not tagged so it’s probably only noted on the flutter version within the sdk

**Comment by Prathik-Jain** [comment]
Playing with the new experimental features like the web, hot UI etc. can be considered for moving into unstable channels. Do you think its good to ignore such use cases?

**Comment by leoafarias** [comment]
@Prathik-Jain I don’t think about it’s ignoring. The Flutter team does not tag does version. Also experimental UI, web version gets rolled into a channel. By using the channel you will get those versions... the only issue is not being able to get a previous version of a channel which was never stable.

But the cases you described are covered by what you described. To be honest that is exactly how Flutter team rolls it out.

**Comment by CaiJingLong** [comment]
@leoafarias 
Regarding the unstable version, can it be solved by ref (commit hash).

You can even specify a different git remote, for example, clone github in China is slower, so we can use a custom three-party source to clone flutter code.

**Comment by leoafarias** [comment]
I know it can be done with a commit hash.. but how do we query the commit for that version. Also I am not sold that this should/needs to be done since the channel behavior covers.

Let me if I have a blind spot here

**Comment by CaiJingLong** [comment]
There can be some solutions about this node dev configuration file, such as adding a .fvm_version file to the project

1. The config file will store flutter's commit hash/ tag/ branch or other information. It can be json, yaml or properties.
2. This file can be submitted to version-control-tools.

We can add commands such as fvm init or setup to read this configuration file. If there is no the version of hash / branch / tag, then download and call the 'use command'.

**Comment by kuhnroyal** [comment]
I currently have a `.flutter_version` file in every project. This is read by a small wrapper script in the CI system which then sets up FVM with the correct version.
The file only contains a single line with the channel or version.

**Comment by kuhnroyal** [comment]
We need to get rid of the `fvm` link and create a script instead when `fvm use` is called. Start with something simple like:

```shell
#!/usr/bin/env sh

if [ -z "$FVM_FILE" ]; then
  FVM_FILE=.flutter_version
fi

if [ -z "$FVM_VERSION" ]; then
  if [ -f "$FVM_FILE" ]; then
    FVM_VERSION=$(head -n 1 $FVM_FILE)
  else
    FVM_VERSION="stable"
  fi
fi

if [ -z "$FVM_PATH" ]; then
  FVM_PATH=$HOME/fvm
fi

$FVM_PATH/versions/$FVM_VERSION/bin/flutter $@
```

**Comment by leoafarias** [comment]
Just getting back to tackling this. The biggest need to the symlink is that it allows for local ide configurations. That will respect the change in the sdk.

I am thinking about a configuration with a symlink, any suggestions on how to make the per project use configurations work without symlink would be great.

**Comment by rchavik** [comment]
> The biggest need to the symlink is that it allows for local ide configurations. That will respect the change in the sdk.

Shouldn't this responsibility be separated from `fvm`. Different editors will have different ways of configuring which SDK to use, eg: vscode dart plugin has [`dart.flutterSdkPaths`](https://dartcode.org/docs/settings/#dartfluttersdkpaths)

**Comment by kuhnroyal** [comment]
IDE configurations is different for each one but what we need here is for `./fvm` to be version controlled. Which means it must not be a link and must not contain a system dependent path.

In the end I want to check the project out in CI or a new developer machine and just run something like `./fvm init` that will setup flutter if it is not already configured.

**Comment by leoafarias** [comment]
> IDE configurations is different for each one but what we need here is for `./fvm` to be version controlled. Which means it must not be a link and must not contain a system dependent path.
> 
> In the end I want to check the project out in CI or a new developer machine and just run something like `./fvm init` that will setup flutter if it is not already configured.

Yes the init process with a versioned config is something that is planned.

**Comment by leoafarias** [comment]
> > The biggest need to the symlink is that it allows for local ide configurations. That will respect the change in the sdk.
> 
> Shouldn't this responsibility be separated from `fvm`. Different editors will have different ways of configuring which SDK to use, eg: vscode dart plugin has [`dart.flutterSdkPaths`](https://dartcode.org/docs/settings/#dartfluttersdkpaths)

@rchavik that is correct, but the symlink allows for the user to not have to change this path when they change version being used in the project

**Comment by kuhnroyal** [comment]
https://github.com/leoafarias/fvm/commit/28587822231c2107ea8841cd1b6ef298c4bb79af is a good start but it breaks every setup. The `./fvm` file is gone and now any command line use is basically impossible. I can't change every call to `./.fvm/flutter_sdk/bin/flutter`.

**Comment by leoafarias** [comment]
@kuhnroyal if you check the `.fvm` folder it contains the version. Fvm will use the version to resolve the path, so there is no need for the symlink anymore on `fvm`. The `flutter_sdk` symlink is created just as an IDE helper. So you can use it for VSCode and have it switch dynamically with with the `fvm use` command.

Also keep in mind that the command `./fvm` was created to run flutter commands because there was an issue with the Dart args package. Once this is fixed `fvm flutter` will work for everything, and I think its the way to go.
