### ISSUE TITLE
[BUG] VSCode not switching Flutter version when switching branches on MacOS

### ISSUE THREAD

**Issue by GP4cK** [leoafarias/fvm#392]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] ~~If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.~~ I'm on macOS
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
I have 2 branches:
- `dev` where I'm using Flutter 2.8.1
- `upgrade-2.10` where I'm trying to upgrade to Flutter 2.10

When I checkout the upgrade branch, VSCode still tells me that I'm using Flutter 2.8.1. I tried restarting VSCode but no effect.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/2680243/155256649-ca70c77a-85c5-49be-b52f-57cfed8bf799.png">

**To Reproduce**

1. Create a git project with 2 branches that use 2 different versions
2. Checkout between branches

**Expected behavior**
VSCode should display the right flutter version

**Desktop (please complete the following information):**

- OS: MacOS 11.6.2
- FVM Version 2.2.3
- ~~If Windows: Which Powershell are you using?~~

**Additional context**

Here's an extract from my `my_project/settings.json`:

```json
{
  "dart.flutterSdkPath": ".fvm/flutter_sdk",
  "files.watcherExclude": {
    "**/.fvm": true
  },
  "search.exclude": {
    "**/.fvm": true
  },
}
```

My `my_project/.fvm/fvm_config.json`:

```json
{
  "flutterSdkVersion": "2.10.2", // on the dev branch, it's 2.8.1
  "flavors": {}
}
```

`fvm doctor`
```sh
FVM Version: 2.2.3
___________________________________________________

FVM config found:
___________________________________________________

Project: my_project
Directory: /Users/.../github/flutter/my_project
Version: 2.10.2
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: /Users/.../fvm/versions/2.10.2
Channel: false
SDK Version: 2.10.2

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /Users/.../github/flutter/my_project/.fvm/flutter_sdk


Configured env paths:
___________________________________________________

Flutter:
/Users/.../flutter/bin/flutter

Dart:
/usr/local/bin/dart

FVM_HOME:
not set
```

**Comment by GP4cK** [comment]
After restarting VSCode several times, it finally displays the correct version. But if you knew a way to clear the cache or something, that'd be super cool.

**Comment by leoafarias** [comment]
@GP4cK the Version switching on vscode will work only when using the “fvm use “ command as it has to regenerate the symlink

**Comment by GP4cK** [comment]
Ok so if I checkout the new branch, then do `fvm use 2.10.2` and restart VSCode, it works well. Thank you very much!

**Comment by martin-braun** [comment]
> @GP4cK the Version switching on vscode will work only when using the “fvm use “ command as it has to regenerate the symlink

This is not working for me on for `use` and `flavor`. It still shows the old version in the top-right corner until I restart VSCode on MacOS. I have checked my `settings.json` is correct and the version will be switched. As said, restarting VSCode will solve the issue, but it's annoying when I try to support more Flutter versions with a Flutter package I develop.
