### ISSUE TITLE
Fvm use not working

### ISSUE THREAD

**Issue by tony123S** [leoafarias/fvm#394]
I want to use flutter `1.22.6`. I have use `fvm use 1.22.6`, but why version still in `2.5.3`?

```
PS C:\Users\nick_\xxx> fvm use 1.22.6 
Project now uses Flutter [1.22.6] 
PS C:\Users\nick_\xxx> fvm flutter --version 
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 18116933e7 (5 months ago) • 2021-10-15 10:46:35 -0700 
Engine • revision d3ea636dc5 
Tools • Dart 2.14.4 
PS C:\Users\nick_\xxx>
```

**Comment by leoafarias** [comment]
@tony123S can you run `fvm use 1.22.6 --verbose`, also can you confirm that you are running on administrator mode, and paste the `fvm doctor` output

**Comment by leoafarias** [comment]
Closing this, if you have any other info please feel free to reopen
