### ISSUE TITLE
[Feature Request] git worktree

### ISSUE THREAD

**Issue by nielsenko** [leoafarias/fvm#396]
Are there any plans of having fvm use [git worktree](https://git-scm.com/docs/git-worktree) as opposed to full clones for each version?

**Comment by leoafarias** [comment]
@nielsenko there is no plan since we try to follow closely the Flutter install process. However we do check for a `FVM_GIT_CACHE` env var, if you want to create a local cache. Haven't tested this a lot we just use for speeding up testing.

**Comment by nielsenko** [comment]
Okay, and thank you for the swift feedback, I really appreciate that. Good luck with fvm going forward!
