### ISSUE TITLE
[Feature Request] Calling fvm use will try to use and/or install the flutter version defined in the config

### ISSUE THREAD

**Issue by zeshuaro** [leoafarias/fvm#397]
## Before creating a feature request make sure the suggestion fit within our [principles](https://fvm.app/docs/getting_started/overview#principles)

**Is your feature request related to a problem? Please describe.**
When using the `fvm use` command, I find it a bit annoying having to specify or select the Flutter version even though the version is already defined in the config file.

**Describe the solution you'd like**
Calling `fvm use` without providing any arguments should attempt to use and/or install the Flutter version defined in the config file. Basically something similar to the `nvm` CLI where calling `nvm use` will automatically use the Node version defined in `.nvmrc`.

**Describe alternatives you've considered**
N/A

**Additional context**
`nvm use` [example](https://github.com/nvm-sh/nvm#nvmrc)

**Comment by leoafarias** [comment]
@zeshuaro we currently do this using the `fvm install` without any arguments. I am open to having that behavior on `use` also if you would like to create a PR that I can review.
