### ISSUE TITLE
[Feature Request] fvm install <version_code> --auto_confirm

### ISSUE THREAD

**Issue by kuyazee** [leoafarias/fvm#403]
## Before creating a feature request make sure the suggestion fit within our [principles](https://fvm.app/docs/getting_started/overview#principles)

**Is your feature request related to a problem? Please describe.**

I work on CI/CD pipelines a lot, and several of these times I use machines that preserve their state. Now some of these projects I work on have varying Flutter versions and I'd like to automate the installation of a Flutter version on the fly.

At first this was solved by adding this to the CI scripts

```bash
fvm use $FLUTTER_VERSION
```

There are problems here is that specific Flutter version needs to have been pre installed

So, I tried adding the the auto yes input command 

```bash
yes | fvm use $FLUTTER_VERSION
```

This worked! **But only in the first run** because the next time you run it, since the terminal does not wait for a yes input, this command fails

![Screen Shot 2022-03-18 at 9 33 28 AM](https://user-images.githubusercontent.com/17846698/158920511-c1d4ffe2-2f33-484a-810c-89e96c4be41d.png)

**Describe the solution you'd like**
I'd like to have a parameter like `--auto_confirm` that skips the needed user input if ever a new Flutter version needs to be installed. This means, whether or not a Flutter version exists, no 'yes' input needs to be accepted and FVM will automatically install that version if not installed yet

**Describe alternatives you've considered**

1. Manually preinstall the Flutter version to the build machine

2. Create a script to check if a specific version has been installed by using `fvm list` to see if I need to install a version first before running `fvm use`

**Additional context**
N/A

**Comment by kuyazee** [comment]
Nevermind, I can use the ff command below instead

```bash
fvm install 2.2.3 && fvm use 2.2.3
```

`fvm install` will not need reinstall anyway if a specific version has already been installed

**Comment by leoafarias** [comment]
@kuyazee the method for use already accepts a `skipConfirmation` parameter, which is set to `true` on install. If you want to create a PR which passes as a parameter on `UseCommand` I will review.
