### ISSUE TITLE
Cannot install flutter using fvm

### ISSUE THREAD

**Issue by harilet** [leoafarias/fvm#406]
When I run `fvm install 2.10.3` I get a Could not install 2.10.3 Like shown below
![image](https://user-images.githubusercontent.com/40688601/161087587-d68bab14-188c-4535-b2e4-95ff6d8f1597.png)

But the flutter 2.10.3 is showing in fvm list
![image](https://user-images.githubusercontent.com/40688601/161088078-d17e2af3-c2e3-4af9-9411-bca2929db2df.png)

When trying to use any of both installed flutter version will show Could not install <flutter version>
![image](https://user-images.githubusercontent.com/40688601/161088466-e1669dea-df92-4ebc-89ae-77d911aeebf3.png)

Please help

**Comment by leoafarias** [comment]
Are you running as administrator? Also can you run with the —verbose flag?

**Comment by harilet** [comment]
It is working, It was the administrator
