### ISSUE TITLE
[Feature Request] Android Studio configuration

### ISSUE THREAD

**Issue by panthe** [leoafarias/fvm#41]
After you've installed fvm cli and all works fine, you can add in you Android Studio project the feature to build directly with the Flutter version that you want follow this simple step:
1) copy the path of fvm symbolic link in your root project directory.
example {fvm-path}/versions/beta/bin/flutter
2) in the Android Studio menù open Languages & Frameworks -> Flutter or search for Flutter and change Flutter SDK path to the previous path
3) Apply the changes

You now can Run and Debug with the selected versions of Flutter.

Thanks for this version management system, is wonderful!

**Comment by leoafarias** [comment]
@all-contributors please add @panthe for doc

**Comment by d-apps** [comment]
Sorry guys but I couldn't understand this, does anyone please can explain detailed this part:

1 - copy the path of fvm symbolic link in your root project directory.
example {fvm-path}/versions/beta/bin/flutter.

![image](https://user-images.githubusercontent.com/20110433/87805163-4c736000-c82b-11ea-824c-4e7c6a8b4e06.png)
