### ISSUE TITLE
fvm : The term 'fvm' is not recognized as the name of a cmdlet (windows) [BUG]

### ISSUE THREAD

**Issue by salim97** [leoafarias/fvm#45]
**Describe the bug**
i got an error of command not recognized after installing it.

**To Reproduce**

1-$ `flutter pub global activate fvm`
Package fvm is currently active at version 0.6.7.
Resolving dependencies...
+ args 1.5.2
+ charcode 1.1.2
+ cli_util 0.1.3+2
+ console 3.1.0
+ fvm 0.6.7
+ io 0.3.3
+ meta 1.1.8
+ path 1.6.4
+ source_span 1.5.5
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ vector_math 2.0.8
Precompiling executables...
Precompiled fvm:bin\main.
Installed executable fvm.
Warning: Pub installs executables into C:\Archive\1_ DEV TOOLS\FLUTTER\SETUP 2019-03-11\flutter\.pub-cache\bin, which is not on your path.
You can fix that by adding that directory to your system's "Path" environment variable.
A web search for "configure windows path" will show you how.
Activated fvm 0.6.7.

2-$ `fvm help`
fvm : The term 'fvm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
the path is correct and try again.
At line:1 char:1
+ fvm help
+ ~~~
    + CategoryInfo          : ObjectNotFound: (fvm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

**Desktop (please complete the following information):**
 - OS: windows10
 - IDE: VScode
 - FVM Version 0.6.7

**Comment by leoafarias** [comment]
@salim97 please make sure you are running ‘pub global activate’ instead of flutter command and also make sure you have configured the system path

https://dart.dev/tools/pub/cmd/pub-global#running-a-script

**Comment by leoafarias** [comment]
@salim97 I will be closing this issue. I have updated the docs pointing to this

**Comment by NullByte08** [comment]
> @salim97 please make sure you are running ‘pub global activate’ instead of flutter command and also make sure you have configured the system path
> 
> https://dart.dev/tools/pub/cmd/pub-global#running-a-script

@leoafarias `pub global activate` gives this 
'pub' is not recognized as an internal or external command,
operable program or batch file.

and I have configured the system path according to the warning
 `
Warning: Pub installs executables into F:\Flutter\FlutterSDK\flutter\.pub-cache\bin, which is not on your path.`
`You can fix that by adding that directory to your system's "Path" environment variable.
`

**Comment by leoafarias** [comment]
@NullByte08 can you try running 'flutter pub...' instead?

**Comment by NullByte08** [comment]
> after running `flutter pub global activate fvm`

@leoafarias Please check my comment, I have tried with flutter pub...

**Comment by leoafarias** [comment]
Seems like the path is not configured. See if this helps https://stackoverflow.com/questions/52794266/pub-global-activate-command-home-pub-cache-bin-not-on-path
