### ISSUE TITLE
Activating version could not find the link

### ISSUE THREAD

**Issue by SantyTaco** [leoafarias/fvm#47]
**Describe the bug**
I am trying to use fvm in a windows 10 computer. I have downloaded two versions:
*1.12.13+hotfix.5
*1.9.1+hotfix.2

Those version are installed in this path: C:\Users\mighu\fvm\versions
When I try to use one version I got this message:
 Sorry could not link C:\Users\mighu\fvm\versions\1.12.13+hotfix.5\bin\flutter.bat

I reviewed the folder and I can see the flutter.bat in that path.

**To Reproduce**
1. Run pub global activate fvm
2. Add this Path C:\Users\mighu\Flutter\flutter_windows_v1.0.0-stable\flutter\.pub-cache\bin in environment variables
3. Run fvm install 1.12.13+hotfix.5
4. Run use 1.12.13+hotfix.5

**Expected behavior**
Run flutter.bat from path  C:\Users\mighu\fvm\versions\1.12.13+hotfix.5\bin\flutter.bat

**Screenshots**
![fvmBug](https://user-images.githubusercontent.com/38363806/71774728-eafc3b80-2f41-11ea-9d13-63e74d91fcbf.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - FVM Version [0.6.7]

**Additional context**

**Comment by leoafarias** [comment]
@zmtzawqlp any way you can take a look at the issue above. It's being a bit difficult to troubleshoot on windows. Seems it has to do with the symlink which you have made some improvements on.

**Comment by zmtzawqlp** [comment]
I couldn't reproduce it with your steps. 
more, i think you should add C:\Users\xxxxx\AppData\Roaming\Pub\Cache\bin to your environment path.  
and you can try to run fvm list to see your cache folder and run fvm config -c C:\Users\xxxx\fvm\versions to set cache folder

**Comment by leoafarias** [comment]
@zmtzawqlp Sorry if it's too much to ask, but would you mind doing a quick bullet point of things you need to make sure are done. You can link to flutter docs if needed, so I can add to readme.md

**Comment by zmtzawqlp** [comment]
@leoafarias in fact, i didn't see any direct problem from the describe of this issue, those are just suggestions, let us wait @SantyTaco 's reply, see any progress at his side.

**Comment by zmtzawqlp** [comment]
@leoafarias @SantyTaco I reproduced it in win10 home edition, and i  found error msg
' Error Code 1314 - A required privilege is not held by the client'. 

It's easy to fix it with run cmd as Administrator and maybe you can update win10 version to p professional edition(home editiion has no full control)

**Comment by zmtzawqlp** [comment]
more, if you run fvm in terminal of vscode, you need to run vscode as Administrator

**Comment by ozyl** [comment]
Same problem on mac.Is there a solution?
```
➜  ~ fvm list
1.12.13+hotfix.8
➜  ~ fvm use 1.12.13+hotfix.8
Activating 1.12.13+hotfix.8...
⚠️  Sorry could not link /Users/yorla/fvm/versions/1.12.13+hotfix.8/bin/flutter
```

**Comment by atprastyo** [comment]
@SantyTaco you need run IDE as administrator on windows
