### ISSUE TITLE
"v1.9.1+hotfix.6" is not a valid version

### ISSUE THREAD

**Issue by dudongdaoqi** [leoafarias/fvm#48]
**Describe the bug**
when i install
fvm install v1.9.1+hotfix.6

tips:
"v1.9.1+hotfix.6" is not a valid version

#0      flutterVersionClone (package:fvm/utils/flutter_tools.dart:68:5)
<asynchronous suspension>
#1      InstallCommand.run (package:fvm/commands/install.dart:34:13)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#4      new Future.sync (dart:async/future.dart:224:31)
#5      CommandRunner.run (package:args/command_runner.dart:112:14)
#6      fvmRunner (package:fvm/fvm.dart:26:23)
<asynchronous suspension>
#7      main (file:///Users/mac/.pub-cache/hosted/pub.dartlang.org/fvm-0.6.7/bin/main.dart:4:9)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by leoafarias** [comment]
@dudongdaoqi can you try using the version without the `v` in front of it

**Comment by dudongdaoqi** [comment]
@leoafarias Thank you very much! It's OK!
