### ISSUE TITLE
Automatic dependencies upgrade

### ISSUE THREAD

**Issue by subzero911** [leoafarias/fvm#486]
Currently we have to ask @leoafarias to bump dependencies every time the Dart SDK is upgraded. Like this topic https://github.com/fluttertools/fvm/issues/474
Consider automation of this process, so fvm utility will check the latest Dart SDK on startup and upgrade itself.

**Comment by subzero911** [comment]
I personally never used `dart pub global activate`, and installed it via Chocolatey only.
2 - I agree to this solution.
3 - i'm not completely understand what a build script do you mean, and how could I help you? To pin somewhere on the fvm site or on pub.dev?

**Comment by subzero911** [comment]
@leoafarias how about adding `dependabot`? It updates dependencies automatically.

**Comment by leoafarias** [comment]
> @leoafarias how about adding `dependabot`? It updates dependencies automatically.

We did a setup of dependabot on another project, and we did not have proper upgrade PRs, due to conflicts in between dependencies. We tried as soon as they released it, and I am not sure if this has been fixed.

What has been your experience with it?

**Comment by subzero911** [comment]
No, I did not try it yet. I just know that it is used on many github projects.

**Comment by subzero911** [comment]
Any updates?

**Comment by leoafarias** [comment]
@subzero911 there is a contributor that plan on taking a look on this for, but I don’t think they had the time yet, will follow up.

**Comment by leoafarias** [comment]
This is closed. The actions on deploy were getting the latest stable version, which was causing a conflict. I have changed the FVM constraints and have pinned the SDK version on the deploy for chocolatey and brew.
