### ISSUE TITLE
[Feature Request] Respect XDG Directory specification

### ISSUE THREAD

**Issue by realitymolder** [leoafarias/fvm#489]
Hey, been using `fvm` for a while, it has been a blast.
I think it would be very beneficial to move the cache and config files to respect the XDG Base Directory specification.
Read more [here](https://wiki.archlinux.org/title/XDG_Base_Directory)

With that said, I have tried to use the already supported --config flag to move the cache into another folder. While it works, when I'm trying to use `fvm global stable` or any other version - it resets my config into the default cache folder. 
Because of that reason, Flutter path is moving all the time.

**Comment by leoafarias** [comment]
@realitymolder the next version of fvm we are removing the `global` command. you can read more about it here #469.

I think there might be a bug on the --config flag, could try using the the `FVM_HOME` environment variable to define the fvm cache path, and see if that works?

**Comment by realitymolder** [comment]
> @realitymolder the next version of fvm we are removing the `global` command. you can read more about it here #469.

Interesting, so basically the best practice according to this is to install (lets say via brew) `fvm` + `flutter`, and use fvm for the edge cases with `fvm use versionNumber` ? 
> I think there might be a bug on the --config flag, could try using the the `FVM_HOME` environment variable to define the fvm cache path, and see if that works?

Looks like it is working ! :) 
If that's the case, why not use this as the default path?

**Comment by leoafarias** [comment]
@realitymolder I will make a note of that change. I believe there is an issue when saving the config file. 

Deprecating the global command because the pub cache is heavily impacted by the change on the global version.

**Comment by Leptopoda** [comment]
Is there any option to move the settings into a separate dir?
I'd optimally like to have the flutter toolcahin in `.cache` and the settings in `.config`.

@leoafarias are you open for PRs?

**Comment by TheLastGimbus** [comment]
+1 this, would love to have it all clean

**Comment by leoafarias** [comment]
@Leptopoda With version 3 of FVM, the configuration will change a bit, so might be worth exploring this after 3.0

**Comment by leoafarias** [comment]
FVM will now respect the XDG directory specifications

**Comment by xeruf** [comment]
does it?
```sh
❯ fvm list
Cache directory:  /home/janek/fvm/versions
Directory Size: 0 B

No SDKs have been installed yet. Flutter. SDKs
installed outside of fvm will not be displayed.
❯ fvm -v
3.2.1
❯ ls .config/fvm -A
.fvmrc
❯ cat .config/fvm/.fvmrc
{}%                                                                                                                                         
```

Btw the toolchain should be in XDG_STATE_HOME if it isn't yet.

**Comment by barraIhsan** [comment]
[See env var option on fvm](https://fvm.app/documentation/getting-started/configuration#supported-environment-variables)
```
export FVM_CACHE_PATH=$XDG_DATA_HOME/fvm
```
This works for me
