### ISSUE TITLE
[BUG] Sorry could not link xxx/bin/flutter

### ISSUE THREAD

**Issue by zebrallel** [leoafarias/fvm#50]
**Describe the bug**
it shows "Sorry could not link xxx/bin/flutter" when i execute "fvm use 1.7.8+hotfix.4"

**To Reproduce**
1. open a shell in item2
2. exec fvm use "v1.7.8+hotfix.4"

**Expected behavior**
use target version success

**Screenshots**
![image](https://user-images.githubusercontent.com/7269427/76483187-4de1e580-6451-11ea-8591-fc6ba9f6dd45.png)

**Desktop (please complete the following information):**
 - OS: [macos 10.15.3]
 - FVM Version [0.6.7]

**Comment by dawnyu** [comment]
So did me

**Comment by leoafarias** [comment]
Could try running a `--verbose` flag on the command so I can see the stack trace?

**Comment by ayush221b** [comment]
I ran into the same issue, here's the stacktrace:

```
 ✘ ayushshekhar@Ayushs-MacBook-Pro  ~  fvm use stable --verbose
[     0.050s] Activating stable...
[     0.058s] FileSystemException: Cannot create link to target '/Users/ayushshekhar/fvm/versions/stable/bin/flutter', path = '/Users/ayushshekhar/fvm' (OS Error: File exists, errno = 17)
[     0.059s] ⚠️  Sorry could not link /Users/ayushshekhar/fvm/versions/stable/bin/flutter
#0      linkDir (package:fvm/utils/helpers.dart:35:5)
<asynchronous suspension>
#1      linkProjectFlutterDir (package:fvm/utils/flutter_tools.dart:201:9)
#2      UseCommand.run (package:fvm/commands/use.dart:38:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      fvmRunner (package:fvm/fvm.dart:26:23)
#8      main (file:///Users/ayushshekhar/development/flutter/.pub-cache/hosted/pub.dartlang.org/fvm-0.6.7/bin/main.dart:4:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by hortegag91** [comment]
Can you solve ir @ayush221b  ?

**Comment by mustafa96m** [comment]
I think there is a misunderstanding here, according to the readme. 

> Use a SDK Version
> You can use different Flutter SDK versions per project. **To do that you have to go into the root of the project and:**
> 
> > fvm use <version>

fvm use specifies the flutter version per project, not globally. Therefore, go to your project root and apply fvm use.
