### ISSUE TITLE
Cannot install not start with 'v' version.

### ISSUE THREAD

**Issue by CaiJingLong** [leoafarias/fvm#51]
![image](https://user-images.githubusercontent.com/14145407/78672477-465c1200-7913-11ea-8adb-31b5afffd915.png)

Such as the 1.17.0 isn't start with 'v'.

https://github.com/leoafarias/fvm/blob/19006666e02769765707402ad9e38a91098f698e/lib/utils/helpers.dart#L9-L11

https://github.com/leoafarias/fvm/blob/19006666e02769765707402ad9e38a91098f698e/lib/utils/flutter_tools.dart#L79

The 'v' is hard-coded into the tool, so I can't use it download them.

**Comment by kuhnroyal** [comment]
This is due to the new Dart/Flutter release process and versioning: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/flutter-announce/b_EcYtyo8Q4/2QSfdp2aBwAJ

**Comment by leoafarias** [comment]
Fixed with #52
