### ISSUE TITLE
[BUG] Invalid Source Map when using fvm

### ISSUE THREAD

**Issue by pmartelletti** [leoafarias/fvm#528]
**Describe the bug**
When building my Flutter app using fvm using the source-map option, the generated main.dart.js.map file is incorrect. In the sources array it generates filenames like:

"../../../../../../fvm/versions/3.7.1/bin/cache/flutter_web_sdk/lib/_engine/engine/browser_detection.dart"

which of course can't be mapped to my code in the 3rd party app (sentry, for example), when the js file is minified.

**To Reproduce**
Just run:

`fvm flutter build --release -t lib/main.js --source-maps`

**Comment by leoafarias** [comment]
@pmartelletti can you provide a reproducible example of the code itself, so I can clone it and run?

**Comment by leoafarias** [comment]
Closing as 3.0 has been released. Check again and reopen the issue if needed.
