### ISSUE TITLE
[BUG] when flutter is 3.10.0,fvm is 2.4.1, fvm's behavior is very strange

### ISSUE THREAD

**Issue by hanger23** [leoafarias/fvm#530]
My system is windows10.
First this normal，when I use flutter 3.3.4，fvm 2.4.1 ,I use 'fvm flutter packages get' and then the dependent libraries will be downloaded to flutter 3.3.4 is installation directory,like E:\fvm\flutter_sdks\flutter_3.3.4\\.pub-cache\hosted.
Now this strange, I use flutter 3.10.0，fvm 2.4.1 ,I use 'fvm flutter packages get' and then the dependent libraries will be downloaded to
default installation directory that is C:\Users\hanger\AppData\Local\Pub\Cache\hosted，and it doesn't downloaded to flutter 3.10.0 is installation directory,like E:\fvm\flutter_sdks\flutter_3.10.0\\.pub-cache\hosted.
I don't believe, then I downloaded flutter 3.7.10，its dependent libraries still downloaded to default installation directory.
After trying for a while,I gave up.I don't know from which version it started, it became abnormal.
Who has the same experience as me?
Or did I make a mistake in my operation?

**Comment by leoafarias** [comment]
@hanger23 not sure, can you provide the output requested when opening an issue, and also provide steps to replicate?

**Comment by hanger23** [comment]
ok,the output requested:
when is flutter 3.3.4:

            `
            F:\File\temppppppp\flutter_test2>fvm flutter --version
            Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
            Framework • revision eb6d86ee27 (8 months ago) • 2022-10-04 22:31:45 -0700
            Engine • revision c08d7d5efc
            Tools • Dart 2.18.2 • DevTools 2.15.0
            
            F:\File\temppppppp\flutter_test2>fvm flutter pub get
            Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
            Running "flutter pub get" in flutter_test2...                      860ms
            `



when is flutter 3.7.10:

          `F:\File\temppppppp\flutter_test_3_7_10>fvm use flutter_3.7.10
          Project now uses Flutter [flutter_3.7.10]
          
          F:\File\temppppppp\flutter_test_3_7_10>fvm flutter --version
          Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
          Framework • revision 4b12645012 (8 weeks ago) • 2023-04-03 17:46:48 -0700
          Engine • revision ec975089ac
          Tools • Dart 2.19.6 • DevTools 2.20.1
          
          F:\File\temppppppp\flutter_test_3_7_10>fvm flutter pub get
          Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
          Running "flutter pub get" in flutter_test_3_7_10...
          Resolving dependencies...
            async 2.10.0 (2.11.0 available)
            characters 1.2.1 (1.3.0 available)
            collection 1.17.0 (1.17.2 available)
            js 0.6.5 (0.6.7 available)
            lints 2.0.1 (2.1.0 available)
            matcher 0.12.13 (0.12.16 available)
            material_color_utilities 0.2.0 (0.5.0 available)
            meta 1.8.0 (1.9.1 available)
            path 1.8.2 (1.8.3 available)
            source_span 1.9.1 (1.10.0 available)
            test_api 0.4.16 (0.6.0 available)
          Got dependencies!
          `

when is flutter 3.10.0:

            `F:\File\temppppppp\flutter_test_3_10_0>fvm use flutter_3.10.0
            Project now uses Flutter [flutter_3.10.0]
            
            F:\File\temppppppp\flutter_test_3_10_0>
            F:\File\temppppppp\flutter_test_3_10_0>fvm flutter --version
            Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
            Framework • revision 84a1e904f4 (3 weeks ago) • 2023-05-09 07:41:44 -0700
            Engine • revision d44b5a94c9
            Tools • Dart 3.0.0 • DevTools 2.23.1
            
            F:\File\temppppppp\flutter_test_3_10_0>fvm flutter pub get
            Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
            Resolving dependencies...
              collection 1.17.1 (1.17.2 available)
              matcher 0.12.15 (0.12.16 available)
              material_color_utilities 0.2.0 (0.5.0 available)
              source_span 1.9.1 (1.10.0 available)
              test_api 0.5.1 (0.6.0 available)
            Got dependencies!
            `

**Comment by hanger23** [comment]
configure environment variables that PUB_CACHE is like E:\pub\cache
