### ISSUE TITLE
FVM and VSCode integration problem

### ISSUE THREAD

**Issue by claudneysessa** [leoafarias/fvm#531]
Hello,

I noticed a problem in FVM and VSCode integration, when I change the environment in VSCode it doesn't change the version and the project has a problem:

Example:

I'm working on VSCode's CMD on version 3.7.5 and I make a global fvm for stable..

It changes to stable but flutter --version remains in 3.7.5 all commands stay in 3.7.5.

If I do the same thing in the default CDM of the operating system, this doesn't happen.

Here's an example video

Video Example:
https://www.youtube.com/watch?v=miHC82YcvJ0

**Comment by claudneysessa** [comment]
I believe he is fixing the version in the project that was used in flutter create...

If I did flutter create with version 3.7.5 for example, it does not accept the global fvm <new_version>

**Comment by quyenlv-unicloud** [comment]
Did you tried setting `"dart.addSdkToTerminalPath": false`?

**Comment by fortinjoffrey** [comment]
> Did you try setting `"dart.addSdkToTerminalPath": false`?

For some reason, I kept having a path to an older version of Flutter "/Users/myname/fvm/versions/3.3.5" even though I had the 3.10.5 in global. I had never set the 3.3.5 path to my PATH (after checking for hours in .zshrc, .zprofile...)
Outside of VS Code `echo $PATH` never had the 3.3.5 path. In VS Code It had it. 

Using what @quyenlv-unicloud wrote fix the "automatic" set in PATH of the 3.3.5 path.

**Comment by leoafarias** [comment]
As @quyenlv-unicloud mentioned flutter vscode extension does add the configured flutterSDK in the settings to the path. That could be causing the issue.

**Comment by leoafarias** [comment]
Closing as 3.0 has been released. Check again and reopen the issue if needed.
