### ISSUE TITLE
Unable to find a version of 'fvm' that is compatible with 'dart-sdk 3.0.4'.

### ISSUE THREAD

**Issue by Amitpatil215** [leoafarias/fvm#533]
**Before creating a bug report please make check the following**

- [X] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [X] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [X] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [X] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

Couldn't upgrade to dart 3.0.4

Unable to find a version of 'fvm' that is compatible with 'dart-sdk 3.0.4'.

**To Reproduce**
**Logs**
```PS C:\WINDOWS\system32> choco upgrade dart-sdk
>>
Chocolatey v0.12.1
Upgrading the following packages:
dart-sdk
By upgrading, you accept licenses for the packages.

You have dart-sdk v2.17.5 installed. Version 3.0.4 is available based on your source(s).
dart-sdk not upgraded. An error occurred during installation:
 Updating 'dart-sdk 2.17.5' to 'dart-sdk 3.0.4' failed. Unable to find a version of 'fvm' that is compatible with 'dart-sdk 3.0.4'.
dart-sdk package files upgrade failed with exit code 1. Performing other installation steps.
The upgrade of dart-sdk was NOT successful.
dart-sdk not upgraded. An error occurred during installation:
 Updating 'dart-sdk 2.17.5' to 'dart-sdk 3.0.4' failed. Unable to find a version of 'fvm' that is compatible with 'dart-sdk 3.0.4'.
 Unsuccessful operation for dart-sdk.```

**Comment by leoafarias** [comment]
This is fixed for version 3.0
