### ISSUE TITLE
[Feature Request]get path command

### ISSUE THREAD

**Issue by mkbsugita** [leoafarias/fvm#534]
## Before creating a feature request make sure the suggestion fit within our [principles](https://fvm.app/docs/getting_started/overview#principles)

**Is your feature request related to a problem? Please describe.**

I want to use get current use Flutter path command

**Describe the solution you'd like**

`fvm list`

```
/Users/s-sugita/fvm/versions
3.7.7 (active)
3.3.4
```

`3.7.7` is current using version.

The new command.

`fvm path`

```
/Users/s-sugita/fvm/versions/3.7.7/
```

**Describe alternatives you've considered**

add the command

`fvm path`

**Additional context**

**Comment by leoafarias** [comment]
@mkbsugita I wont be able to get to this,but I will accept a PR, however I believe it should be part of `fvm doctor`
