### ISSUE TITLE
Provide documentation how to use FVM in a project

### ISSUE THREAD

**Issue by lukaszciastko** [leoafarias/fvm#535]
I am looking at your documentation and cannot find information on how to use FVM. There in an article how to [install FVM](https://fvm.app/docs/getting_started/installation) and an article explaining the [configuration](https://fvm.app/docs/getting_started/configuration). The latter article states: _FVM will create a relative symlink in your project from .fvm/flutter_sdk to the cache of the selected version._ How does it create it? I installed FVM, activated it, and opened my project, and no magic happened, thus I suppose there is a step missing that adds FVM to a project?

Update: I figured our that I had to add the configuration in VS Code to settings.json first and then execute fvm use VERSION. This then created the .fvm folder. I think this should be clearly explained in the configuration steps - right now, the documentation only explains how to install FVM but not how to initialise it in a project.

**Comment by leoafarias** [comment]
Closing this as the documentation has been updated, and FVM handles setup automatically as well.
