### ISSUE TITLE
[BUG] vscode is using global version instead of project version

### ISSUE THREAD

**Issue by vadrian89** [leoafarias/fvm#537]
Hello,

**Before creating a bug report please make check the following**

- [x ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
If I try to run pub get from the vscode either by shortcut or saving the pubspec.yaml file it tries to use the global version, which currently is 3.7.12. 

**To Reproduce**

1. Install FVM using homebrew
2. Install stable version and 3.7.12 version of Flutter
3. Use 'fvm global stable' to set the global version
4. Use 'fvm use 3.7.12' to set the project version
5. Use Ctrl+Shift+P shortcut
6. Type "Get packages"
7. Use command: "Flutter: Get packages"

**Expected behavior**
I expectd the project to use the fvm flutter version I set it in both terminal and vscode.

**Desktop (please complete the following information):**
fvm flutter doctor -v:
```
[!] Flutter (Channel stable, 3.10.5, on KDE neon 5.27 5.19.0-45-generic, locale ro_RO.UTF-8)
    • Flutter version 3.10.5 on channel stable at /home/adrian/fvm/versions/stable
    ! Warning: `dart` on your path resolves to /home/linuxbrew/.linuxbrew/Cellar/dart/2.19.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /home/adrian/fvm/versions/stable. Consider adding /home/adrian/fvm/versions/stable/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/adrian/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /home/adrian/Android/Sdk
    • Java binary at: /home/adrian/Programe/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/adrian/Programe/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • KDE neon 5.27 5.19.0-45-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.
```

.fvm/fvm_config.json content:
```
{
  "flutterSdkVersion": "stable",
  "flavors": {}
}
```

**Additional context**
I initially used the Flutter official version as my global, but it seemed that some of the 'fvm flutter', suchs as build apk, used the official version instead of fvm.

**Comment by BlackCatHehe** [comment]
same

**Comment by husainazkas** [comment]
same

**Comment by jopmiddelkamp** [comment]
same

**Comment by husainazkas** [comment]
> Did you configured vscode to use .fvm? https://fvm.app/docs/getting_started/configuration#vs-code

Of course I've already configure as that, but I thought it have a missing part.

The docs only tells about how to pointing vscode to the selected SDK path, BUT the Flutter SDK must read PATH environment to the flutter/dart bin file e.g `/Users/<pc-name>/fvm/versions/3.10.6/bin` so if we have multiple Flutter versions we can only set single path.

I've tried to add multiple paths to the environment but SDK still find the first path, here is my .zshrc file

```zsh
export PATH=$PATH:/Users/<pc-name>/fvm/versions/3.12.0/bin
export PATH=$PATH:/Users/<pc-name>/fvm/versions/stable/bin
```

The SDK will take the first line instead of another one, even it reversed. I tried many another way and it can't help.

**Comment by quyenlv-unicloud** [comment]
did you disabled setting `dart.addSdkToTerminalPath`?

**Comment by christinachimi** [comment]
I think I'm having a similar issue, although I don't know that it's necessarily related to VSCode. I can run `fvm use 3.10.6` as many times as I like, and it will say "Project now uses Flutter [3.10.6]" but when I run `fvm flutter --version` or try to run `fvm flutter pub get` it is still using 3.7.12.

`fvm flutter doctor` has this warning:

```
[!] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/me/fvm/versions/3.10.6. Consider adding /Users/me/fvm/versions/3.10.6/bin to the front of your path.
```

but doing that doesn't help. Is there any documentation on what should and shouldn't be in the PATH when using fvm?

**Comment by leoafarias** [comment]
Can you make sure vscode is configured correctly according g to the https://fvm.app docs

**Comment by leoafarias** [comment]
@vadrian89  we have made some improvements on this for version 3.0, I am closing this issue, let me know if you can still replicate it on 3.0.0
