### ISSUE TITLE
[BUG] Brew install (Linux Mint)

### ISSUE THREAD

**Issue by MartinRValdez** [leoafarias/fvm#543]
Hi, i try install fvm with brew in Linux Mint, and it gives me this error "Got TLS error trying to find package meta at https://pub.dev.
" any idea? Thanks!

**Comment by MartinRValdez** [comment]
@leoafarias since yesterday I'm trying and it gives me the same error =(

**Comment by MartinRValdez** [comment]
![Captura de pantalla de 2023-07-05 12-29-22](https://github.com/fluttertools/fvm/assets/50831681/542682a1-bbed-4bdc-8026-25f3715930c8)

**Comment by leoafarias** [comment]
This should have been resolved on the latest homebrew formula
