### ISSUE TITLE
[Feature Request] add support for web-hostname and web-port

### ISSUE THREAD

**Issue by andrewpmoore** [leoafarias/fvm#55]
If I run 
 flutter run --verbose -d chrome --web-hostname localhost --web-port 7357

so that my chrome instance is running on a specific port (needed for google sign in) it works fine.

If I enter the same but with fvm on the start I just get errors that the options aren't defined.
Would it be possible to add support for these?

**Comment by leoafarias** [comment]
This is currently an impediment on the arcs module. Please use `./fvm run` for now

**Comment by leoafarias** [comment]
This has been solved with version 0.72
