### ISSUE TITLE
[BUG] [Android Studio] You may need to increase the maximum number of file handles available globally

### ISSUE THREAD

**Issue by cybex-dev** [leoafarias/fvm#553]
**Describe the bug**
Changing the location of Flutter SDK to that provided by `fvm` causes an error/exception preventing the Flutter dameon from running (starting).

Android Studio [installation/configuration](https://fvm.app/docs/getting_started/configuration#android-studio) steps were (mostly) used _with exception of the symbolic link_.

![Android Studio Dart Configuration](https://i.imgur.com/skCfaPQ.png)

**To Reproduce**

1. Install `fvm` 
2. Install Flutter SDK (or select preferred e.g. `3.10.6`)
3. Run `fvm use stable` (or installed)
4. Open Android Studio
5. Set new Dart/Flutter SDK location in `Settings` (Settings > Languages & Framework > Dart > Dart SDK Path)
6. Restart IDE

### Observe error(s):

**Flutter Device Daemon**
![Flutter Device Daemon (exit code 1)](https://i.imgur.com/fPjCkDn.png)

With File handles error:
> The Flutter device daemon cannot be started. 
> Please check your configuration and restart the IDE.
>
> You may need to [increase the maximum number of file handles](https://www.google.com/search?q=increase%20maximum%20file%20handles%20Windows%2011%2010.0) available globally.
![Increase the maximum number of file handles](https://i.imgur.com/ewUhXmx.png)

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop:**

Tested on Android Studio Giraffe | 2022.3.1
- OS: Windows 11 x64
- FVM Version 2.4.1
- If Windows: 5.1.22621.1778 (Desktop)

Android Studio Giraffe | 2022.3.1
> Build #AI-223.8836.35.2231.10406996, built on June 29, 2023
> Runtime version: 17.0.8+7-b1000.8 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Flutter branch: 3. (3.10.6)

**Additional context**

<details>
  <summary>flutter doctor -v</summary>

  ```js
  PS C:\Users\cybex\.flutter> git checkout 3.10.6
HEAD is now at f468f3366c [flutter_releases] Flutter stable 3.10.6 Framework Cherrypicks (#130446)
PS C:\Users\cybex\.flutter> flutter doctor -v
[!] Flutter (Channel unknown, 3.10.6, on Microsoft Windows [Version 10.0.22621.2134], locale en-ZA)
    ! Flutter version 3.10.6 on channel unknown at C:\Users\cybex\.flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision f468f3366c (6 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\cybex\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34003.232
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.111
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 116.0.1938.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
  ```
</details>

**Comment by cybex-dev** [comment]
As a temporary solution, one can fallback to the [default](https://github.com/flutter/flutter/issues/87383#issuecomment-948081570) installation.

**Comment by cybex-dev** [comment]
#### Symbolic Link 

Using the absolute path to the symbolic link

_In my case: `C:\Users\cybex\FlutterProjects\twilio_voice\.fvm\flutter_sdk`_

![Absolute Path](https://i.imgur.com/V5PGgSQ.png)

and inserting this path into the IDE Dart Location settings (described [here](https://fvm.app/docs/getting_started/configuration#android-studio))

Results in the SDK not being found:

![Absolute path of symbolic link](https://i.imgur.com/Y3TEbhd.png)

**Comment by leoafarias** [comment]
@cybex-dev Can you fill out this form for 3.0 beta testing. We were able to get really good integration with vscode, but it seems there are a few things that the fluttertools does that overrides some internal settings.

https://forms.gle/PMgVw78sq6oXdHQ76

**Comment by anakin-jin** [comment]
encounter the same problem, it'll pop up window to show the information once launched the AS.
reinstalled the git, cannot fix it.

thinking it's maybe caused by old flutter version. so I try to upgrade it using git directly.

`
D:\Work\flutter>git status
fatal: detected dubious ownership in repository at 'D:/Work/flutter'
'D:/Work/flutter' is owned by:
        'S-1-5-21-4011354511-2983545020-2485740568-1001'
but the current user is:
        'S-1-5-21-2579974789-1159429007-3621735976-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory D:/Work/flutter

D:\Work\flutter>git config --global --add safe.directory D:/Work/flutter

D:\Work\flutter>git status
On branch stable
Your branch and 'origin/stable' have diverged,
and have 18 and 1402 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

nothing to commit, working tree clean`

then everything work well again.
