### ISSUE TITLE
[BUG] FormatMessage failed for error code 16389 (error 317)

### ISSUE THREAD

**Issue by Choi-JinYong** [leoafarias/fvm#554]
**Before creating a bug report please make check the following**

- [ ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ ] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

**To Reproduce**

1. Go to powershell (run as Admin)
2. Run `fvm use stable`...
3. Check...

**Expected behavior**

**Logs**
Please check photo

![123](https://github.com/fluttertools/fvm/assets/86086943/a40ecf2c-12d2-4686-a246-4f36f4f6b688)
All release versions have the same symptoms !!!
help!!!!!!!

**Desktop (please complete the following information):**

- OS: windows
- FVM Version 2.4.1
- If Windows: Which Powershell are you using?

**Additional context**

**Comment by leoafarias** [comment]
Closing as 3.0 has been released. Check again and reopen the issue if needed.
