### ISSUE TITLE
[BUG] fvm flutter run not working

### ISSUE THREAD

**Issue by aseef17** [leoafarias/fvm#56]
I've been getting the following error while trying to change SDK to the local one.

<img width="788" alt="Screenshot 2020-04-24 at 5 40 30 AM" src="https://user-images.githubusercontent.com/26878414/80161489-281e3380-85ee-11ea-901f-05e171f6badb.png">

**Comment by leoafarias** [comment]
I believe you have to run the simulator first. This happens when you switch the sdk for the last compile but normally is not an error, just a notification

**Comment by aseef17** [comment]
You were right. But what I would wish to achieve is that make sure that the particular directory runs on the specified version of flutter. 
I have the stable version installed globally and would like to run the beta version on the particular directory to essentially build flutter for web (using the command flutter create .)
But when I try to run flutter --version after running fvm flutter run, I get the following warning. How do change the head to the installed version using fvm?

<img width="788" alt="Screenshot 2020-04-24 at 6 00 04 AM" src="https://user-images.githubusercontent.com/26878414/80162393-daef9100-85f0-11ea-971f-bf005707b5c3.png">

**Comment by aseef17** [comment]
I got it working with fvm flutter create . and running the application on chrome using fvm flutter run -d chrome. Sorry for the trouble.
Anyway, we can make VS Code refer to fvm so I don't have to run the application from the terminal
I've already added 

  "dart.flutterSdkPaths": [
        "fvm"
    ],

to the settings.json file.

**Comment by leoafarias** [comment]
Yes no problem ... flutter references the global flutter which is configured. Let me know if we could have addd anything on the docs to make a bit clearer
