### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by congfandi** [leoafarias/fvm#574]
## Error isntallation on windows 11 with flutter 3.16. here the log

![image](https://github.com/leoafarias/fvm/assets/10652810/383afb89-1b91-4f8d-9a2c-0ea710aa3db7)

and when i rey to use fvm with anything, its just say

`Cannot find file at '..\lib\fvm\bin\fvm.exe' (C:\ProgramData\chocolatey\lib\fvm\bin\fvm.exe). This usually indicates a missing or moved file.`

please help guys. Thank you.

**Comment by SasLuca** [comment]
I have the same bug, tried downgrading flutter and dart since I thought it was because fvm is not up to date with the latest dart sdk or something but still got this issue.

**Comment by SasLuca** [comment]
For now i downloaded fvm from the github repo's releases, but does fvm have an updater feature? If not, getting it via chocolatey is more convenient because i can check for updates and install them.

Hope this gets looked into.

**Comment by leoafarias** [comment]
@congfandi can you try installing the beta version from Chocolatey and see if the issue persists?

**Comment by congfandi** [comment]
> @congfandi can you try installing the beta version from Chocolatey and see if the issue persists?

is there any link or tutorial can read about the beca version @leoafarias ? iam new with windows env

**Comment by leoafarias** [comment]
Closing this as it seems it has been resolved based on the comments
