### ISSUE TITLE
[BUG] "fvm use" with "--force" does not skip prompt with default answer yes.

### ISSUE THREAD

**Issue by zagori** [leoafarias/fvm#579]
**Before creating a bug report please make check the following**

**Describe the bug**
I am trying to use a version of flutter that is not installed using the command `fvm use 3.16.2 -f`. This is expected to install the version if not installed already.

**Expected behavior**
Running `fvm use 3.16.2 -f` is expected to use the specified version. If the specified version is not installed, user will be prompted to answer "yes/no" to install version. The `-f` is meant to skip the prompt by taking "yes" as default answer. 

**Actual behavior**
Running `fvm use 3.16.2 -f` gives the following error:

> + fvm use 3.16.2 --force
> Flutter "3.16.2" is not installed.
> Would you like to install it? Y/n: Unhandled exception:
> type 'Null' is not a subtype of type 'FutureOr<String>'
> #0      _AsyncCompleter.complete (dart:async/future_impl.dart:36)
> #1      Prompter.prompt.<anonymous closure>.<anonymous closure> (package:console/src/prompt.dart:222)
> #2      new Future.<anonymous closure> (dart:async/future.dart:253)
> #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
> #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
> #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
> #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
> exit status 255

**To Reproduce**

1. Go to terminal
2. Run `fvm use {version} -f`, where {version} is a version that is not installed
4. See the exception thrown

**Stack**
- Xcode 14.2.x, on macOS 13.2 (Ventura) on ARM (M1 Max)

**Comment by zagori** [comment]
@leoafarias I have used fvm 2.4.1 which is the latest stable version.

I have also tried 3.0 version as you suggested. I have installed [3.0.0-beta.5](https://github.com/leoafarias/fvm/releases/tag/3.0.0-beta.5) and issue persists.

Here are some logs:
```
+ fvm --version
3.0.0-beta.5
```

```
+ fvm use 3.16.5 -f
Creating local mirror...

 Counting objects:    [██████████████████................................] 35%
 Counting objects:    [████████████████████████████████████████████......] 88%
 Counting objects:    [████████████████████████████████████████████████..] 95%
 Counting objects:    [██████████████████████████████████████████████████] 100%

 Compressing objects: [███...............................................] 5%
.
.
.
Resolving deltas:    [███████████████████████████████████████████████...] 94%
 Resolving deltas:    [████████████████████████████████████████████████..] 95%
 Resolving deltas:    [████████████████████████████████████████████████..] 96%
 Resolving deltas:    [█████████████████████████████████████████████████.] 97%
 Resolving deltas:    [█████████████████████████████████████████████████.] 98%
 Resolving deltas:    [██████████████████████████████████████████████████] 99%
 Resolving deltas:    [██████████████████████████████████████████████████] 100%
✓ Clone complete
Flutter SDK: SDK Version : 3.16.5 is not installed.
? Would you like to install it now? (y/n) › yes                                 
timeout after 12600 seconds
```

As you can see in the previous log, the command `fvm use 3.16.5 -f` still prompt user despite having `-f`

**Comment by leoafarias** [comment]
@leoafarias Is this running on a CI? if so run `fvm install 3.16.5` then `fvm use 3.16.5` command, while I review

**Comment by zagori** [comment]
@leoafarias yes, this is running on a CI.

And as you recommended, i will continue using `fvm install 3.16.5` and `fvm use 3.16.5` for now.

Thanks for the follow up.
