### ISSUE TITLE
Is there a way to add and existing flutter sdks to the fvm cli ? [Feature Request]

### ISSUE THREAD

**Issue by 3mrdev** [leoafarias/fvm#58]
**Is your feature request related to a problem? Please describe.**
I can't find a command to add my existing flutter sdk

**Describe the solution you'd like**
Add a path to the flutter sdk i already have .. for those who have slow internet and already have flutter 

**Describe alternatives you've considered**
provide us with a clear documentation of how to clone my existing flutter to a directory that fvm can see

**Comment by leoafarias** [comment]
Seems that this is related to #21

**Comment by leoafarias** [comment]
Seems that this is related to #21

**Comment by leoafarias** [comment]
Right now there is not a way to add the existing SDK. You can however move the SDK folder into the FVM versions folder, and use the `channel` as the folder name.
