### ISSUE TITLE
[BUG] Cannot use dart 2.x when run on fvm v2

### ISSUE THREAD

**Issue by FujiKinaga** [leoafarias/fvm#582]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
It appears that the minimum dart support version is now 3.x due to an update to the path used internally.
https://github.com/dart-lang/path/releases/tag/v1.9.0

**To Reproduce**

1. Set `dart-lang/setup-dart` with sdk by `2.19.6`
2. Run `fvm install` and `fvm flutter build ...`
3. Check...

**Expected behavior**
That fvm 2.4.1 works with dart's 2 series.

**Logs**

on CI

```
Package fvm is currently active at version 2.4.1.
Resolving dependencies...
  cli_util 0.3.5 (0.4.0 available)
> path 1.9.0 (was 1.8.3)
  process_run 0.12.5+3 (0.13.3 available)
Building package executables...
Built fvm:main.
Installed executable fvm.
Activated fvm 2.4.1.
Flutter 3.7.12 • channel stable • ssh://git@github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (8 months ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

~~~

fvm as globally activated doesn't support Dart 2.19.6, try: dart pub global activate fvm
...
```

**Desktop (please complete the following information):**

- Run on CircleCI MacOS / [Medium Gen2](https://circleci.com/docs/2.0/configuration-reference/#resourceclass)
- FVM Version 2.4.1

**Additional context**
I am thinking that maybe changing the path specification in pubspec.yaml will work correctly!
https://github.com/leoafarias/fvm/blob/main/pubspec.yaml#L21

**Comment by leoafarias** [comment]
This workflow has been improved on FVM 3; I suggest testing it again and reopening the ticket if the issue remains. However, using the global version is recommended to install FVM as a standalone package.
