### ISSUE TITLE
[BUG]Extremely Slow and Failing fvm install Command

### ISSUE THREAD

**Issue by numa08** [leoafarias/fvm#586]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

fvm doctor

```

FVM Version: 2.4.1
___________________________________________________

FVM config found:
___________________________________________________

Project: radio_qth_map
Directory: /home/numa08/src/github.com/covelline/radio_qth_map/app/radio_qth_map
Version: 3.16.4
Project Flavor: None selected
___________________________________________________

Version is currently cached locally.

Cache Path: /home/numa08/fvm/versions/3.16.4
Channel: false
SDK Version: 3.16.4

IDE Links
VSCode: .fvm/flutter_sdk
Android Studio: /home/numa08/src/github.com/covelline/radio_qth_map/app/radio_qth_map/.fvm/flutter_sdk


Configured env paths:
___________________________________________________

Flutter:


Dart:
/home/linuxbrew/.linuxbrew/bin/dart

FVM_HOME:
not set
```

**Describe the bug**

When using the fvm install command to clone Flutter, I am experiencing significantly slow download speeds for the source code. Here is a copy from the terminal, indicating speeds around 80 ~ 200 KiB/s.

<img width="534" alt="image" src="https://github.com/leoafarias/fvm/assets/937552/1019647d-f652-43de-9d8a-25f04770486d">

To troubleshoot the issue, I attempted the following:

1. Manual Git Clone:
I executed git clone git@github.com:flutter/flutter.git -b 3.16.4. This process worked fine with speeds around 10 MiB/s, indicating no issues with cloning speed.

<img width="495" alt="image" src="https://github.com/leoafarias/fvm/assets/937552/6ef0fd51-19e2-4529-938c-83b72af6b0b0">

2. Using Process.start:
Realizing that the git execution is ultimately handled by Dart's Process.start, I wrote and executed the following code to measure the speed .

```dart
import 'dart:io';

void main() async {
    final p = await Process.start(
        'git',
        ['clone',
        'git@github.com:flutter/flutter.git',
        '-b',
        '3.16.4',
        ],
        runInShell: true,
        mode: ProcessStartMode.inheritStdio
        );
}
```

 The result was similar to the first test, with cloning speeds of about 10 MiB/s.

3. Testing with git.dart Used Internally by FVM:
To see if the issue lies within git.dart, which is used internally by FVM, I wrote and executed the following code to measure the speed . 

```dart
import 'package:test_app/test_app.dart' as test_app;
import 'package:git/git.dart';

void main(List<String> arguments) async {
  await runGit(
    [
      'clone',
      '--progress',
      '-c',
      'advice.detachedHead=false',
      '-b',
      '3.16.4',
      'git@github.com:flutter/flutter.git',
    ],
    echoOutput: true,
  );
}
```

Like the second test, it confirmed sufficient speeds.

--- 

It seems the issue might be within FVM's internal implementation or the command-line options being executed. I am unsure of how to resolve this but would appreciate guidance on further steps for a detailed investigation.

**To Reproduce**

1. Go to terminal..
2. Run `fvm use stable`...
3. Check...

**Expected behavior**

I expect the cloning process to complete at speeds comparable to the standard git command, typically in the range of several tens of MiB/s.

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

fvm install --verbose

```
Flutter "3.16.4" is not installed.

Installing version: 3.16.4...
Cloning into '/home/numa08/fvm/versions/3.16.4'...
remote: Enumerating objects: 485131, done.        
remote: Counting objects: 100% (41909/41909), done.        
remote: Compressing objects: 100% (1593/1593), done.        
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 4595 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
[ 2m 41.448s] Cloning into '/home/numa08/fvm/versions/3.16.4'...
remote: Enumerating objects: 485131, done.        
remote: Counting objects: 100% (41909/41909), done.        
remote: Compressing objects: 100% (1593/1593), done.        
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 4595 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

[ 2m 41.449s] Internal Error: Could not git clone 3.16.4

Could not install 3.16.4

Please run command with  --verbose if you want more information
```

**Desktop (please complete the following information):**

- OS: Ubuntu (WSL2)
- FVM Version 2.4.1
- If Windows: Which Powershell are you using?

**Additional context**

I considered the possibility of using the --filter=tree:0 option in the clone command to only clone necessary information.

**Comment by DavidOrakpo** [comment]
I'm facing this issue as well! How do we solve it? I'd try the manual method you said and report back

**Comment by numa08** [comment]
Thank you for your comment.

I also tried cloning manually. The command I used is as follows.

```
cd $HOME/fvm/versions
git clone git@github.com:flutter/flutter.git -b 3.16.4 --filter=tree:0 ./3.16.4
# and go your project directory that is managed by fvm
fvm use
```

**Comment by AliYar-Khan** [comment]
facing same issue

**Comment by AliYar-Khan** [comment]
I am facing same issue with -filter=tree command as well

**Comment by leoafarias** [comment]
Maybe this was a hick up on git? if not can you do the same command on version 3.0 beta 5?

**Comment by AliYar-Khan** [comment]
github is also slow ... can be an issue. !!!

**Comment by AliYar-Khan** [comment]
but i am trying to clone using 

`git clone git@github.com:flutter/flutter.git -b 3.16.5 --filter=tree:0 ./3.16.5`

but it doesn't consider it as a clean setup and delete the folder and its content @leoafarias

**Comment by AliYar-Khan** [comment]
I got it working with this --filter=tree command

**Comment by leoafarias** [comment]
Be aware of any command that does partial clones, as flutter tooling is tightly dependent on the clone itself and can cause weird issue due to release channel detection and feature flags

**Comment by yaotutu** [comment]
I had same problem. 
```
[64] % fvm doctor

No FVM config found:
/Users/yao
Fvm will run the version in your PATH env: /Users/yao/fvm/versions/stable/bin/flutter

Configured env paths:
___________________________________________________

Flutter:
/Users/yao/fvm/versions/stable/bin/flutter

Dart:
/opt/homebrew/bin/dart

FVM_HOME:
not set

```

<img width="693" alt="image" src="https://github.com/leoafarias/fvm/assets/21394924/69d86c95-645a-4085-9379-8daef8fdfc8c">

**Comment by ForFlutter400** [comment]
i'm facing the same issue, my internet connection is good everything is downloading with the speed of 5mb/s on browser but when i run 'fvm install' then speed is 50, 100, 200, 400 kb/s and then it suddenly stops, please solve this issue.

![prob1](https://github.com/leoafarias/fvm/assets/136308671/ae4c560d-a23a-4e9d-b1fe-001c3958e487)

![image](https://github.com/leoafarias/fvm/assets/136308671/67e12693-24cb-4acf-8a40-38bc827948c4)

**Comment by leoafarias** [comment]
When you have an issue like this, can you run the clone command through git? This seems to be a git issue, as `fvm` is running the clone command behind the scenes. Also, I suggest using version 3.0.0 beta, as it does some optimizations behind the scenes.

**Comment by ikoamu** [comment]
I was able to install it by changing my git settings.

```
$ git config --global http.postBuffer 52428800
$ git config --global core.compression 0
```

```
$ fvm install 3.16.8                          
Flutter "3.16.8" is not installed.

Installing version: 3.16.8...
Cloning into '/Users/shotaroaoki/fvm/versions/3.16.8'...
remote: Enumerating objects: 490967, done.        
remote: Counting objects: 100% (94009/94009), done.        
remote: Compressing objects: 100% (2683/2683), done.        
remote: Total 490967 (delta 91704), reused 91326 (delta 91326), pack-reused 396958        
Receiving objects: 100% (490967/490967), 87.69 MiB | 822.00 KiB/s, done.
Resolving deltas: 100% (399354/399354), done.
Updating files: 100% (7856/7856), done.
HEAD is now at 67457e669f [flutter_releases] Flutter stable 3.16.8 Framework Cherrypicks (#141648)
Downloading Darwin arm64 Dart SDK from Flutter engine 6e2ea58a5ccbefcfadc2d4b7b8045fc6c20ab812...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  207M  100  207M    0     0  3702k      0  0:00:57  0:00:57 --:--:-- 3690k
Building flutter tool...
Resolving dependencies...
Got dependencies.
Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (7 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5
```

**Comment by AliYar-Khan** [comment]
@leoafarias 
I am facing issue on latest fvm version as well. How to utilize the Git mirroring for faster cloning?

**Comment by leoafarias** [comment]
It should already be enabled. Can you try to clone outside of fvm to see if it's an issue with fvm itself?

**Comment by BrianRigii** [comment]
Anyone with a working solution for this problem ?

**Comment by ViktorKirjanov** [comment]
still the same issue

**Comment by leoafarias** [comment]
Sorry guys not sure what to do here.. the information is not as clear if it was a git hick up or if  its happening internally...

**Comment by zeexan-dev** [comment]
I had same issue and i solved it by
1. Uninstalled Git
2. Installed git again using choco
3. Installed fvm again using choco
4. now fvm install command worked fine

**Comment by faseehhyder** [comment]
I was facing the same issue, and it turned out my machine needed **Developer Mode** enabled in Windows. After I switched Developer Mode on in the Windows settings, everything started working correctly.
