### ISSUE TITLE
I have an error when trying to run FVM on Windows , Unable to find git in your PATH

### ISSUE THREAD

**Issue by albinrk10** [leoafarias/fvm#589]
When I run fvm install or fvm flutter clean, I get the error: Error: Unable to find git in your PATH. I reinstalled Git and added it to its environment variables, but I still get the same error.

![image](https://github.com/leoafarias/fvm/assets/79820950/89f49dba-771a-4dac-83be-f492eb31ccd7)

**Comment by AliYar-Khan** [comment]
Use cmd as administrator. I also faced this and the error was gone when I convert cmd to admin.

**Comment by albinrk10** [comment]
I solved it, but do you always have to run as administrator?

**Comment by leoafarias** [comment]
FYI, This is not an FVM issue; I found an article about the subject.

https://codingislove.com/unable-to-find-git-path-flutter

**Comment by dickermoshe** [comment]
@leoafarias 
This should be added to FAQ

**Comment by leoafarias** [comment]
@dickermoshe can you do a PR? If not I can try to add it later

**Comment by dickermoshe** [comment]
Done
