### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by haadinorouzi** [leoafarias/fvm#59]
First time i install a sdk it doesn't have a default cache path and doesn't prompt me to set this.

 - OS: macOS
 - FVM Version 0.7.0

**Comment by leoafarias** [comment]
@haadinorouzi there should be a default cache path if one is not set. Could you provide more info?

**Comment by haadinorouzi** [comment]
Maybe it has. 
But first time run ‘fvm config’ doesn’t show me cache_path
It says not set.
