### ISSUE TITLE
How to change java version?

### ISSUE THREAD

**Issue by devnta** [leoafarias/fvm#590]
`fvm flutter doctor -v`
```
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/myname/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/myname/Library/Android/sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.1+12-29)
    • All Android licenses accepted.
```
Run without `fvm`:
```
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/myname/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/myname/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.
```
Why `Java binary` when use fvm and without it is not same?
I know set `JAVA_HOME` will resolved this issue.
But how can I change `Java binary` to other path without set `JAVA_HOME`?
Because `JAVA_HOME` related several another applications.
ps: Sorry for my English

**Comment by ntaworking** [comment]
@leoafarias  Sorry for mention.

**Comment by leoafarias** [comment]
@ntaworking can you run the same test with version 3.0 which was released? If the issue persists I would have to know the flutter version that is running under `fvm flutter` vs just `flutter`

**Comment by leoafarias** [comment]
Closing this issue due to lack of update.

**Comment by devnta** [comment]
@leoafarias 
I ran flutter doctor -v on Flutter version 3.24.2, and currently, both are using the same Java version. But if I want my project to run on Java 17, what should I do? Thank you.

**Comment by leoafarias** [comment]
@devnta I believe you have to change the Java version installed, as Flutter does not ship with Java itself, so this does not seem like an FVM issue. Here is something that might help:

https://stackoverflow.com/questions/66980512/android-studio-error-android-gradle-plugin-requires-java-11-to-run-you-are-cur/67002271#67002271

**Comment by devnta** [comment]
@leoafarias Thanks for your support.
