### ISSUE TITLE
[Feature Request] Add parameter to "fvm use", so install is performed without acknowledging it manually

### ISSUE THREAD

**Issue by Markus43** [leoafarias/fvm#594]
**Is your feature request related to a problem? Please describe.**
I'd like to use fvm in my CI system to install the flutter version that is configured for a project. When using "fvm use" with a version that has not been installed yet, I get the following, asking for user input, which I cannot give in an automated environment:
> Flutter "3.16.9" is not installed.
> Would you like to install it? Y/n

**Describe the solution you'd like**
I'd like to have a parameter for "fvm use" which skips the question, so the required version is installed.

**Describe alternatives you've considered**
Until now, I have to manually install all versions on the CI server before my apps can use it via fvm. This is tedious work that I would like to avoid.

**Comment by AndreasMattsson** [comment]
I'd also like this feature for my CI configuration, but for now simply piping `yes | fvm use` seems to do it for now (in case that is of any help to others here).

**Comment by leoafarias** [comment]
This was closed by https://github.com/leoafarias/fvm/pull/670, will be on the next release
