### ISSUE TITLE
[BUG] Install FVM 3.0.0 on Linux docker image

### ISSUE THREAD

**Issue by SebastianKlaiber** [leoafarias/fvm#601]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ ] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
I'm trying to update fvm to version 3.0.0 on my docker image. 

https://github.com/SebastianKlaiber/flutter_docker

**To Reproduce**

1. Checkout branch https://github.com/SebastianKlaiber/flutter_docker/pull/14
2. docker build --tag flutter_docker:latest --no-cache .

**Expected behavior**

**Logs**
4.921 ===== CRASH =====
4.921 si_signo=Segmentation fault(11), si_code=1, si_addr=(nil)
4.921 version=3.2.4 (stable) (Thu Dec 21 19:13:53 2023 +0000) on "linux_x64"
4.921 pid=80, thread=90, isolate_group=main(0x555557a4a5c0), isolate=main(0x555557a4cfb0)
4.921 os=linux, arch=x64, comp=no, sim=no
4.921 isolate_instructions=ffffb4633000, vm_instructions=5555574e4c80
4.921 fp=7ffff4c7ccf0, sp=7ffff4c7ccf0, pc=55555760c690
4.921   pc 0x000055555760c690 fp 0x00007ffff4c7ccf0 dart::ReadStream::Read64+0x10
4.921   pc 0x0000555557630e21 fp 0x00007ffff4c7cd20 dart::DeoptInfo::FrameSize+0xd1
4.921   pc 0x0000555557630c66 fp 0x00007ffff4c7cd80 dart::DeoptContext::DeoptContext+0x1f6
4.921   pc 0x000055555773244d fp 0x00007ffff4c7d380 DLRT_DeoptimizeCopyFrame+0x36d
4.921   pc 0x0000ffffb4583279 fp 0x00007ffff4c7d390 Unknown symbol
4.921   pc 0x0000000000000000 fp 0x00007ffff4c7d528 Unknown symbol
4.921   pc 0x0000ffffb44b62eb fp 0x00007ffff4c7d5c0 Unknown symbol
4.921   pc 0x0000ffffb4a69c86 fp 0x00007ffff4c7d700 Unknown symbol
4.921   pc 0x0000ffffb4a6cfe8 fp 0x00007ffff4c7d790 Unknown symbol
4.921   pc 0x0000ffffb4d52182 fp 0x00007ffff4c7d888 Unknown symbol
4.921   pc 0x0000ffffb4d60a73 fp 0x00007ffff4c7d938 Unknown symbol
4.921   pc 0x0000ffffb4d790d9 fp 0x00007ffff4c7da00 Unknown symbol
4.921   pc 0x0000ffffb44ae4af fp 0x00007ffff4c7db38 Unknown symbol
4.921   pc 0x0000ffffb4dc7505 fp 0x00007ffff4c7db90 Unknown symbol
4.921   pc 0x0000ffffb4dc7258 fp 0x00007ffff4c7dbd8 Unknown symbol
4.921   pc 0x0000ffffb4dd92b1 fp 0x00007ffff4c7dc48 Unknown symbol
4.921   pc 0x0000ffffb4dbb283 fp 0x00007ffff4c7dce8 Unknown symbol
4.921   pc 0x0000ffffb4d93409 fp 0x00007ffff4c7dd78 Unknown symbol
4.921   pc 0x0000ffffb44b8791 fp 0x00007ffff4c7de08 Unknown symbol
4.921   pc 0x0000ffffb4dda88a fp 0x00007ffff4c7de70 Unknown symbol
4.921   pc 0x0000ffffb4f06f82 fp 0x00007ffff4c7df08 Unknown symbol
4.921   pc 0x0000ffffb508625c fp 0x00007ffff4c7df58 Unknown symbol
4.921   pc 0x0000ffffb469a9c4 fp 0x00007ffff4c7dfd8 Unknown symbol
4.921   pc 0x0000ffffb469acd6 fp 0x00007ffff4c7e040 Unknown symbol
4.921   pc 0x0000ffffb5020332 fp 0x00007ffff4c7e0d8 Unknown symbol
4.921   pc 0x0000ffffb50858ef fp 0x00007ffff4c7e128 Unknown symbol
4.921   pc 0x0000ffffb501c0aa fp 0x00007ffff4c7e1a0 Unknown symbol
4.921   pc 0x0000ffffb501c283 fp 0x00007ffff4c7e200 Unknown symbol
4.921   pc 0x0000ffffb469651f fp 0x00007ffff4c7e290 Unknown symbol
4.921   pc 0x0000ffffb46a602d fp 0x00007ffff4c7e2e0 Unknown symbol
4.921   pc 0x0000ffffb501fc6d fp 0x00007ffff4c7e328 Unknown symbol
4.921   pc 0x0000ffffb501fdb5 fp 0x00007ffff4c7e368 Unknown symbol
4.921   pc 0x0000ffffb501ffb6 fp 0x00007ffff4c7e390 Unknown symbol
4.921   pc 0x0000ffffb4692ee9 fp 0x00007ffff4c7e3d0 Unknown symbol
4.921   pc 0x0000ffffb4694660 fp 0x00007ffff4c7e450 Unknown symbol
4.921   pc 0x0000ffffb4691593 fp 0x00007ffff4c7e488 Unknown symbol
4.921   pc 0x0000ffffb4691659 fp 0x00007ffff4c7e4b8 Unknown symbol
4.921   pc 0x0000ffffb4693886 fp 0x00007ffff4c7e520 Unknown symbol
4.921   pc 0x0000ffffb5088b4c fp 0x00007ffff4c7e578 Unknown symbol
4.921   pc 0x0000ffffb4582e46 fp 0x00007ffff4c7e5f0 Unknown symbol
4.921   pc 0x0000555557622bd3 fp 0x00007ffff4c7e650 dart::DartEntry::InvokeFunction+0x163
4.921   pc 0x0000555557624616 fp 0x00007ffff4c7e690 dart::DartLibraryCalls::HandleMessage+0x126
4.921   pc 0x0000555557640c5f fp 0x00007ffff4c7ec20 dart::IsolateMessageHandler::HandleMessage+0x2bf
4.921   pc 0x0000555557662e87 fp 0x00007ffff4c7ec90 dart::MessageHandler::HandleMessages+0x127
4.921   pc 0x0000555557663478 fp 0x00007ffff4c7ece0 dart::MessageHandler::TaskCallback+0x1e8
4.921   pc 0x00005555577604ab fp 0x00007ffff4c7ed60 dart::ThreadPool::WorkerLoop+0x14b
4.921   pc 0x0000555557760748 fp 0x00007ffff4c7ed90 dart::ThreadPool::Worker::Main+0x78
4.921   pc 0x00005555576e9d36 fp 0x00007ffff4c7ee50 dart::ThreadStart+0xd6
4.921 -- End of DumpStackTrace
4.928 Compilation did not produce any result. Expected file at `/home/circleci/.pub-cache/_temp/dirLISLMP/bin/tmpZGVQNM/main.dart-3.2.4.snapshot.incremental.temp`
4.928 Built fvm:main.
4.934 Cannot rename file to '/home/circleci/.pub-cache/_temp/dirLISLMP/bin/main.dart-3.2.4.snapshot', path = '/home/circleci/.pub-cache/_temp/dirLISLMP/bin/tmpZGVQNM/main.dart-3.2.4.snapshot.incremental.temp' (OS Error: No such file or directory, errno = 2)
------
Dockerfile:18
--------------------
  16 |
  17 |     # Install fvm
  18 | >>> RUN dart pub global activate fvm
  19 |
  20 |     # Install melos dart package
--------------------
ERROR: failed to solve: process "/bin/bash -exo pipefail -c dart pub global activate fvm" did not complete successfully: exit code: 66

**Desktop (please complete the following information):**

- FVM Version [e.g. 22]
- If Windows: Which Powershell are you using?

**Additional context**

**Comment by leoafarias** [comment]
@SebastianKlaiber I made a change on the bew formula this morning can you try if this fixes the issue?

**Comment by SebastianKlaiber** [comment]
=> ERROR [ 8/12] RUN brew install fvm                                                                                                                      102.7s 
------                                                                                                                                                             
 > [ 8/12] RUN brew install fvm:                                                                                                                                   
0.336 + brew install fvm                                                                                                                                           
4.970 Running `brew update --auto-update`...                                                                                                                       
77.11 ==> Fetching leoafarias/fvm/fvm                                                                                                                              
78.28 ==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/release/3.2.6/sdk/dartsdk-macos-x64-release.zip                                  
88.92 ==> Downloading https://github.com/leoafarias/fvm/archive/3.0.0.tar.gz
88.92 ==> Downloading from https://codeload.github.com/leoafarias/fvm/tar.gz/refs/tags/3.0.0
89.60 ==> Installing fvm from leoafarias/fvm
98.69 ==> /home/linuxbrew/.linuxbrew/Cellar/fvm/3.0.0/libexec/bin/dart pub get
98.72 Last 15 lines from /home/circleci/.cache/Homebrew/Logs/fvm/01.dart:
98.74 2024-02-12 18:44:11 +0000
98.74 
98.74 /home/linuxbrew/.linuxbrew/Cellar/fvm/3.0.0/libexec/bin/dart
98.74 pub
98.74 get
98.74 
98.74 /home/linuxbrew/.linuxbrew/Cellar/fvm/3.0.0/libexec/bin/dart: 1: ������
                                                                             ��H__PAGEZEROh__TEXT�#�#: not found
98.74 /home/linuxbrew/.linuxbrew/Cellar/fvm/3.0.0/libexec/bin/dart: 2: Syntax error: Unterminated quoted string

**Comment by SebastianKlaiber** [comment]
FYI: The initial error message is from the dart pub global active fvm command.

**Comment by leoafarias** [comment]
@SebastianKlaiber I will need fvm specific output. Can you try to replicate this outside of docker to understand where is failing?

**Comment by SebastianKlaiber** [comment]
@leoafarias it's working with dart 3.3 and fvm version 3.0.4. If you need more information I could try to reproduce it again on a linux machine.

**Comment by leoafarias** [comment]
@SebastianKlaiber i have a lot of open issues with docker, I am not an expert, and wanted some help creating a simple image that works similarly to the brew formula.

Any assistance with it would be helpful.

**Comment by SebastianKlaiber** [comment]
@leoafarias I would be happy to support you, I'm not a docker expert either, but I can take a look at the docker issues so that the requirements become clearer to me.
