### ISSUE TITLE
[Feature Request] Support brew like links

### ISSUE THREAD

**Issue by long1eu** [leoafarias/fvm#61]
In brew you can have multiple version but still point to the same folder. This folder is a symlink to the current version. This way I don't need to set the version of dart everytime in IntelliJ

**Comment by long1eu** [comment]
![Screenshot 2020-06-14 at 18 20 18](https://user-images.githubusercontent.com/9283414/84597294-bcc54500-ae6b-11ea-9932-a5f5a1137ff5.png)
This way I only need to add to path the symlink. Also this allows to have a global version of flutter.

**Comment by leoafarias** [comment]
@long1eu I think the new version of the config solves that problem for you https://github.com/leoafarias/fvm#android-studio

**Comment by long1eu** [comment]
If you say so. But what about a global flutter?

**Comment by leoafarias** [comment]
@long1eu https://github.com/leoafarias/fvm/blob/master/CHANGELOG.md#080

**Comment by long1eu** [comment]
Thanks
