### ISSUE TITLE
[BUG] endless loop

### ISSUE THREAD

**Issue by TomaszCz** [leoafarias/fvm#613]
**Describe the bug**
A new command to update FVM doesn't update
![image](https://github.com/leoafarias/fvm/assets/20865719/4f1d40ad-bbc0-43fb-b3f8-0e5f21af23dd)

**Expected behavior**
Update performed

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

Windows 11 Pro
FVM 3.0.1

https://github.com/leoafarias/fvm/assets/20865719/b0f3d762-057c-4161-b05d-0733ff7051ab

**Comment by leoafarias** [comment]
@TomaszCz This is most likely because it was installed using chocolatey, I have created a PR to add that in the env for a check
