### ISSUE TITLE
[Feature Request] Enable automatic release new fvm docker version when release new fvm version

### ISSUE THREAD

**Issue by deandreamatias** [leoafarias/fvm#617]
**Is your feature request related to a problem? Please describe.**
I want to enable automatic release new fvm docker version when release new fvm version. [This line](https://github.com/leoafarias/fvm/blob/9866bade578dab7f6eca4d3876b1c2abbc967baf/.github/workflows/release.yml#L89) was commented on [this commit](https://github.com/leoafarias/fvm/commit/521e991d40d751fd593d619b7de9f480c8c59b7e)

**Describe the solution you'd like**
Able to use the last version of FVM on docker image https://hub.docker.com/r/leoafarias/fvm

**Describe alternatives you've considered**
Maybe remove comment on workflow line, solve the problem

**Comment by AngeloAvv** [comment]
[This](https://github.com/leoafarias/fvm/issues/621) might be related
