### ISSUE TITLE
[BUG] monorepo support broken in version 3

### ISSUE THREAD

**Issue by krispypen** [leoafarias/fvm#624]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
When having a .fvmrc file in the root, and the flutter packages in subfolder. When you run "fvm use" it result in the error:
```
This does not seem to be a Flutter project directory
? Would you like to continue? (y/n) › 
```
According to [this](https://fvm.app/documentation/getting-started/faq#monorepo-support) it should work, and it also worked on version 2. You can just say "y" but that does not work on CI tests

**Desktop:**

- OS:  macos
- FVM Version 3.0.3

**Comment by leoafarias** [comment]
Might keep the check just for pubspec and not just Flutter
