### ISSUE TITLE
[BUG] Flutter SDK: (3.19.0) is not valid Flutter version

### ISSUE THREAD

**Issue by josh-burton** [leoafarias/fvm#627]
**Before creating a bug report please make check the following**

- [x ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
With the new 3.19.0 Flutter release, FVM seems to not recognize it.

When i run fvm install (or any fvm command), the following error is shown:

```
Flutter SDK: (3.19.0) is not valid Flutter version
Do you want to continue?
```
Answering yes proceeds to install it, but this is not working on CI as I can't answer the prompt.

**Comment by kuhnroyal** [comment]
I also get this for other versions, `3.16.9@stable` for example.

**Comment by leoafarias** [comment]
I am able to install correctly both of these versions on the latest version 3.0.4, I am running `fvm install 3.19.0`

**Comment by leoafarias** [comment]
I believe I found the issue, there is probably a strange behavior that causes the Git command to get the reference to fail.

**Comment by josh-burton** [comment]
> I believe I found the issue, there is probably a strange behavior that causes the Git command to get the reference to fail.

Thanks! That has fixed the issue for me.
