### ISSUE TITLE
[BUG] can't proxy to pub

### ISSUE THREAD

**Issue by jamesdixon** [leoafarias/fvm#63]
**Describe the bug**
Hi, I'm trying to proxy to the `flutter pub` command to execute `build_runner`. It doesn't seem to be possible.

**To Reproduce**
Run `flutter pub run build_runner build --delete-conflicting-outputs`

**Expected behavior**
`build_runner` is executed. Instead, I see an error that `--delete-conflicting-outputs` is not an option.

**Desktop (please complete the following information):**
 - MacOS 10.15.5
 - FVM Version 0.7.1

**Comment by leoafarias** [comment]
@jamesdixon this was just fixed on version 0.7.2.

**Comment by jamesdixon** [comment]
@leoafarias thanks!

My apologies...didn't realize there was a 0.7.2. 

Just tried this and it DOES work. 

Thanks for this and for your amazing work on FVM.

Cheers
