### ISSUE TITLE
[BUG]fvm use   No pubspec.yaml detected in this directory but pubspec.yaml have

### ISSUE THREAD

**Issue by dujj** [leoafarias/fvm#638]
**Before creating a bug report please make check the following**

- [ ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ ] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Run `fvm use stable`...
3. Check...

**Expected behavior**

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- FVM Version [e.g. 22]
- If Windows: Which Powershell are you using?

**Additional context**

**Comment by leoafarias** [comment]
@dujj I will need more information, as it's asked on the template, to replicate. Even basic things like the FVM version, if it's a monorepo or not.

**Comment by dujj** [comment]
<img width="1508" alt="企业微信截图_4f02b226-0c0e-43b4-bfc2-e560d25b2c36" src="https://github.com/leoafarias/fvm/assets/9443889/65389c87-86d0-4b0a-aa93-969716c1ec16">
<img width="1508" alt="企业微信截图_8940f839-0df0-4c3b-aaa6-5329560fc871" src="https://github.com/leoafarias/fvm/assets/9443889/87f17214-8880-4b65-b977-83cef9faa886">

**Comment by dujj** [comment]
Please look at the picture above. In the directory created by flutter, using fvm use, pubspec.yaml clearly exists, but it still prompts: No pubspec.yaml detected in this directory. Select yes, and the .fvm directory is not generated.

**Comment by Bassiuz** [comment]
We are currently experiencing the same problems on our CI; after upgrading our FVM version. Multiple projects have exactly the same problem.

**Comment by leoafarias** [comment]
But it should fall under this line if you are running on the directory itself.
`if (isRootDir) return Project.loadFromPath(context.workingDirectory);`

**Comment by Bassiuz** [comment]
> If you want to run locally, you can just go into the fvm directory on your machine for this PR and do `dart pub global activate --source path .` make sure you uninstall fvm from brew or chocolatey if you have installed outside of fvm.

I tested by running this version locally on the repo that doesn't work with the stable version. It seems that re-enabling the line fixes this problem.

**Comment by leoafarias** [comment]
> > If you want to run locally, you can just go into the fvm directory on your machine for this PR and do `dart pub global activate --source path .` make sure you uninstall fvm from brew or chocolatey if you have installed outside of fvm.
> 
> I tested by running this version locally on the repo that doesn't work with the stable version. It seems that re-enabling the line fixes this problem.

@Bassiuz, thank you. Let me review the impact of adding this back in. It should have hit the isRootDir condition. Trying to replicate it on my end

**Comment by Bassiuz** [comment]
> But it should fall under this line if you are running on the directory itself. `if (isRootDir) return Project.loadFromPath(context.workingDirectory);`
> 
> It seems that it is not.

I just checked, and indeed the the `isRootDir` is not firing for me. I added some prints here

```
    // Checks if the directory is root
    final isRootDir = path.rootPrefix(directory.path) == directory.path;
    print(isRootDir);
    print(directory.path);
    print(path.rootPrefix(directory.path));

```

results in this:

```
false
/Users/bassiuz/test/project-name
/
```

So it seems to elevate to above the location you are currently running FVM

**Comment by leoafarias** [comment]
@Bassiuz can you also print the context `context.workingDirectory` for me?

**Comment by Bassiuz** [comment]
@leoafarias Yes, that is `/Users/bassiuz/test/project-name`

**Comment by leoafarias** [comment]
@Bassiuz, I think the problem is somewhere else. so when it finally hits the root, it should use the context.workingDirectory to find the pubspec.yaml, I am digging in to see if I can find the problem or at least replicate it. 

Just to take a step back, can you provide info about how FVM is installed, (brew, chocolatey),  OS, and so on?

**Comment by Bassiuz** [comment]
> @Bassiuz, I think the problem is somewhere else. so when it finally hits the root, it should use the context.workingDirectory to find the pubspec.yaml, I am digging in to see if I can find the problem or at least replicate it.

Aah! You are right indeed. It seems that it does not keep recursively looping until it reached the root.

```
false
/Users/bassiuz/test/project-name
/
/Users/bassiuz/test/project-name

false
/Users/bassiuz/test
/
/Users/bassiuz/test/project-name

false
/Users/bassiuz
/
/Users/bassiuz/test/project-name
```

And while testing it I see that I configured somewhere higher in the hierarchy somewhere. Same goes for my build machine.

Is there a command we can use to force configuring FVM in the working directory instead of looking for an ancestoring FVM configuration?

**Comment by leoafarias** [comment]
@Bassiuz I believe the issue is that the 'hasConfig' has been hit. Do you have a 'fvm_config.json' or a '.fvmrc' in '/Users/bassiuz'?

**Comment by leoafarias** [comment]
@Bassiuz, I am pushing a fix; thanks for your patience.

**Comment by Bassiuz** [comment]
@leoafarias Thanks a lot for the fast responses and joint debugging.

This was fun :). Have a nice weekend!

**Comment by Pamblam** [comment]
I can't be the only person who is new to Flutter who ended up here after a Google search and had no idea what anyone in this thread is talking about, so I'll share the simple solution for my use case...

For some reason fvm created a .fvm and .fvmrc in my home directory, most likely when i was playing with fvm in my home directory without knowing what I was doing. Once the .fvm directory exists in the home directory it apparently uses that and ignores whatever directory you're currently in. **After removing .fvm and .fvmrc from my home directory, `fvm use` worked as expected by creating the fvm config in the current project directory.**

This is probably obvious to most of you but it took me an hour to figure out.
