### ISSUE TITLE
[Feature Request] Version brew formulas

### ISSUE THREAD

**Issue by ikaem-csq** [leoafarias/fvm#645]
## Before creating a feature request make sure the suggestion fit within our [principles](https://fvm.app/docs/#principles)

**Describe the solution you'd like**
I'd like to be able to install specific patch version of fvm via brew. 
From what I see, 3.0.3 is the last one available. 

THanks

**Comment by leoafarias** [comment]
Now it will create versioned formulas, also I added the versions on homebrew back to 2.4.1
