### ISSUE TITLE
fvm install command is not working in iOS

### ISSUE THREAD

**Issue by thanoofayoob** [leoafarias/fvm#661]
tried this command in 
 fvm --version - 3.0.11
then this error is thrown

<img width="715" alt="Screenshot 2024-02-27 at 1 03 05 PM" src="https://github.com/leoafarias/fvm/assets/67316775/ba681995-fb0d-41e1-96e7-21f1060c0f19">

**Comment by leoafarias** [comment]
@thanoofayoob the screenshot seems to be different  than your description. Can you review it so I can try to replicate the problem?

**Comment by thanoofayoob** [comment]
> @thanoofayoob the screenshot seems to be different than your description. Can you review it so I can try to replicate the problem?

this error is thrown when this command "fvm install 3.16.0 --verbose" is called

**Comment by thanoofayoob** [comment]
Closing this issue.
it was because of my internet.
