### ISSUE TITLE
[BUG] The `install.sh` script uses `/usr/local/bin/fvm` as a link target which requires sudo privileges

### ISSUE THREAD

**Issue by Nidal-Bakir** [leoafarias/fvm#699]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
When using the `install.sh` to install the FVM as a standalone bin the script will try to create a link target in the `/usr/local/bin/fvm` which requires sudo privileges.

**To Reproduce**

1. Go to terminal..
2. Run `curl -fsSL https://fvm.app/install.sh | bash`
5. See an error 

> permission denied: /usr/local/bin/fvm
> Failed to create symlink.

**Expected behavior**
The FVM bin can be run from anywhere on the system after installation.

**Logs**
N/A

**Desktop (please complete the following information):**

- OS: [linux ubuntu]
- FVM Version [N/A]

**Additional context**
we have tow options to discuss:

1. The docs should state that the user should run the script with sudo or in root user mode, then the FVM bin will be in `/usr/local/bin/fvm` without any errors
2. Change the link target to `$HOME/.local/bin/fvm`

I have modified the install.sh script to use `$HOME/.local/bin/fvm` and everything worked as expected.

**Comment by leoafarias** [comment]
@Nidal-Bakir can you do a PR so I can review?

**Comment by Nidal-Bakir** [comment]
sure thing..

**Comment by jamilxt** [comment]
I am facing this issue for a long time. I hope the PR will be merged as soon as possible.

Thanks @Nidal-Bakir

**Comment by azharbinanwar** [comment]
@Nidal-Bakir 
Thank you raising this issue, I tried a lot but nothing was helpful except your PR.

I tried this and it started working fine.

`sudo curl -fsSL https://raw.githubusercontent.com/leoafarias/fvm/e04a1f455c4db33c4c220a5239acb76c0e132c02/scripts/install.sh | bash`

:+1:

**Comment by Nidal-Bakir** [comment]
@azharbinanwar 
Tip: You do not need sudo privileges to run the script

And you should use the update script `update.sh` to update FVM to the latest version.

We did not make a final decision about the changes yet. You probably should wait until the PR is merged and the package owner approves the changes.

**Comment by azharbinanwar** [comment]
> @azharbinanwar 
> Tip: You do not need sudo privileges to run the script
> 
> And you should use the update script `update.sh` to update FVM to the latest version.
> 
> We did not make a final decision about the changes yet. You probably should wait until the PR is merged and the package owner approves the changes. 

Thank you for your quick response.
I'll try update.sh

**Comment by 2XL** [comment]
> curl -fsSL https://raw.githubusercontent.com/leoafarias/fvm/e04a1f455c4db33c4c220a5239acb76c0e132c02/scripts/install.sh | bash

for linux make sure $HOME/.local/bin/ parent dirs exists..

**Comment by hongfeiyang** [comment]
Got the same issue

**Comment by mighty-phoenix** [comment]
Without sudo, the installation command(`curl -fsSL https://fvm.app/install.sh | bash`) results in the following error on linux:
```
ln: failed to create symbolic link '/usr/local/bin/fvm': Permission denied
error: Failed to create symlink.
```

**Comment by Wilker-uwu** [comment]
hi, i've had this problem when setting up fvm. the script i'm getting from the installation doc[1] didn't seem to have the patch in #700, so i had some issues setting it up. i got that fixed by manually setting up the path.

[1] https://fvm.app/documentation/getting-started/installation

**Comment by gyuri-fluttech** [comment]
the issue seems to be fixed, but not deployed to `https://fvm.app/install.sh` 

@leoafarias , @Nidal-Bakir

**Comment by Nidal-Bakir** [comment]
Hay @gyuri-fluttech,

I do not have control over this.
please contact @leoafarias about it

**Comment by Edlavio** [comment]
`curl -fsSL https://raw.githubusercontent.com/leoafarias/fvm/e04a1f455c4db33c4c220a5239acb76c0e132c02/scripts/install.sh | bash`

Create `$HOME/.local/bin/` dir and add `export PATH="$HOME/.local/bin:$PATH"` to .bashrc
Results for me

**Comment by erlangparasu** [comment]
> `curl -fsSL https://raw.githubusercontent.com/leoafarias/fvm/e04a1f455c4db33c4c220a5239acb76c0e132c02/scripts/install.sh | bash`
> 
> Create `$HOME/.local/bin/` dir and add `export PATH="$HOME/.local/bin:$PATH"` to .bashrc Results for me

Thanks this my steps that works for me
```
        mkdir -p $HOME/.local/bin/
        ls -laF $HOME/.local/bin/

        export PATH="$HOME/.local/bin:$PATH"

        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.profile

        curl -fsSL https://raw.githubusercontent.com/leoafarias/fvm/e04a1f455c4db33c4c220a5239acb76c0e132c02/scripts/install.sh | bash
        fvm --version
```

**Comment by sgehrman** [comment]
?? is this project dead? No fixes for a year now?
