### ISSUE TITLE
[BUG] Update fvm

### ISSUE THREAD

**Issue by zerowu49** [leoafarias/fvm#706]
**Intention**
I want to update the fvm version since mine is 2.4.1 and want to update it to latest version (3.1.3)

**To Reproduce**

1. Go to terminal
2. Run `fvm --version` and shows me "2.4.1"
3. Run `dart pub global deactivate fvm` and `dart pub global activate fvm` but returned "Activated fvm 2.3.1."
4. Re-run `fvm --version` and still shows me "2.4.1"

**Expected behavior**
Re-run `fvm --version` and return latest version of 3.1.3

**Desktop (please complete the following information):**

- OS: macOS
- FVM Version : 2.4.1

**Comment by leoafarias** [comment]
@zerowu49 most likely the dart version you are using is incompatible. I suggest installing the standalone executable.

you can run `dart --version` to check the dart version which you are using to setup the global

**Comment by BBarisKilic** [comment]
I had the same issue, and as @leoafarias suggested, I upgraded the main Flutter SDK to have a newer Dart version. It solved the issue.

**Comment by ristiisa** [comment]
I had the same issue, but `brew upgrade fvm` did the update...

**Comment by zerowu49** [comment]
Doing what ristiisa said and it works. Many thanks for your information!
