### ISSUE TITLE
[BUG]https://github.com/leoafarias/fvm/issues/638 report in fvm version:3.1.3

### ISSUE THREAD

**Issue by dujj** [leoafarias/fvm#707]
**Before creating a bug report please make check the following**

- [ ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [ ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [ ] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Run `fvm use stable`...
3. Check...

**Expected behavior**

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

- FVM Version [e.g. 22]
- If Windows: Which Powershell are you using?

**Additional context**

**Comment by dujj** [comment]
<img width="1165" alt="企业微信截图_26fe03ca-eee8-4e00-b380-b98c4c5056a7" src="https://github.com/leoafarias/fvm/assets/9443889/937cf882-4828-44c2-ba58-48e9a96153d1">

**Comment by leoafarias** [comment]
Can you tell me the version of fvm

also run the command with the `--verbose` flag as it will show which directories are looking at.

**Comment by dujj** [comment]
3.1.3

**Comment by leoafarias** [comment]
@dujj Can you run with the `--verbose` flag so we can see the directories that is lookin into for pubspec?

**Comment by dujj** [comment]
<img width="1508" alt="企业微信截图_2c38bb03-f2e3-4bc7-8f2f-5a10ca8344db" src="https://github.com/leoafarias/fvm/assets/9443889/190d2ff4-ff4c-4c9a-9321-4eef7f37cae6">

**Comment by leoafarias** [comment]
@dujj Based on those logs it seems there an fvm config in that /work directory. So its looking for the config file instead of the pubspec, because of nested directories. So it seems the message says there is no pubspec found in the same direcotry that the project config is found

**Comment by dujj** [comment]
1. flutter create test

**Comment by dujj** [comment]
see :

**Comment by dujj** [comment]
I clean work,result:
fvm use 3.19.6 --verbose

Argument information:
  Top level options:
  - verbose: true

Command: use

Searching for project in /Users/k/Documents/work/123/test
Searching for project in /Users/k/Documents/work/123
Searching for project in /Users/k/Documents/work
Searching for project in /Users/k/Documents
Searching for project in /Users/k
Searching for project in /Users
Searching for project in /
No project found in /Users/k/Documents/work/123/test

Updating project config
Project name: test
Project path: /Users/k/Documents/work/123/test

Checking .gitignore
Update gitignore: true
[WARN] Project is not a git repository. 
 But will set .gitignore as IDEs may use it,to determine what to index and display on searches,
You should add the fvm version directory ".fvm/" to .gitignore.
✔ Would you like to do that now? · yes                                                                                                                                                                                
✓ Added .fvm/ to .gitignore

✓ Project now uses Flutter SDK : SDK Version : 3.19.6

**This operation was as expected**

But I still don’t understand why the search is not in the current directory to determine whether there is a problem with the conditions of a project, and why it is searched recursively upwards.

**Comment by leoafarias** [comment]
@dujj I will close this issue since it seems to be working. The recursion supports workspaces and/or monorepos, so you have the same version configured for multiple projects.
