### ISSUE TITLE
[Feature Request] Correct way to move the main fvm folder

### ISSUE THREAD

**Issue by fzyzcjy** [leoafarias/fvm#708]
Hi thanks for the tool! I have fvm installed, and would like to move the `~/fvm` folder to another disk. Is there any suggested way to do so, or should I uninstall and reinstall fvm, etc?

**Comment by leoafarias** [comment]
@fzyzcjy sorry for the delay on this. There is not really a recommended way, you can copy the whole directory.

**Comment by fzyzcjy** [comment]
I see, thank you!
