### ISSUE TITLE
[Enhancement] Show warning when git not installed

### ISSUE THREAD

**Issue by listepo** [leoafarias/fvm#714]
**Before creating a bug report please make check the following**

**Describe the bug**

**To Reproduce**

1. Go to terminal..
2. Install choco
3. Install fvm
```

Creating local mirror...

✓ Clone complete
✗ Failed to ensure FlutterVersion(name: stable, releaseFromChannel: null, type: VersionType.channel) is cached.

Exception: Git clone failed

package:fvm/src/utils/parsers/git_clone_update_printer.dart 92   runGitCloneUpdate
package:fvm/src/services/flutter_service.dart 146                FlutterService.updateLocalMirror
package:fvm/src/workflows/ensure_cache.workflow.dart 85          ensureCacheWorkflow
package:fvm/src/commands/install_command.dart 75                 InstallCommand.run
package:args/command_runner.dart 212                             CommandRunner.runCommand
package:fvm/src/runner.dart 246                                  FvmCommandRunner.runCommand
package:fvm/src/runner.dart 122                                  FvmCommandRunner.run
package:scope/src/scope.dart 151                                 Scope.run
c:\programdata\chocolatey\lib\fvm\tools\source\bin\main.dart 13  main
```

**Desktop (please complete the following information):**

- OS: [Windows 11]
- FVM Version [e.g. 22]
- If Windows: Which Powershell are you using?
- Yes

**Additional context**

**Comment by leoafarias** [comment]
@listepo can you share the version of FVM, I believe this has been fixed in one of the latest versions.

**Comment by listepo** [comment]
I try install latest version

**Comment by listepo** [comment]
@leoafarias  `fvm --version 3.1.3`

**Comment by listepo** [comment]
I found the problem, I didn't have git installed. I think you need to check and display a clear error. cc @leoafarias

**Comment by Ay0ubCheurfi** [comment]
@listepo, I'm also encountering this issue. I've verified that I have Git installed. Any insights would be appreciated.

**Comment by Ay0ubCheurfi** [comment]
@leoafarias, I'm getting this error despite using FVM v3.1.3, which I believe is the latest version. Any ideas what might be causing this?

**Comment by leoafarias** [comment]
@Ay0ubCheurfi Can you create a directory and run `git clone https://github.com/flutter/flutter.git` to see if there is an issue on git?

**Comment by Ay0ubCheurfi** [comment]
@listepo  Just an update – the issue wasn't reflected correctly in the error message "Exception: Git clone failed".  It was my internet connection. Switching networks fixed it.
