### ISSUE TITLE
run ‘fvm list’， TOO SOLW [BUG]

### ISSUE THREAD

**Issue by YueLiXing** [leoafarias/fvm#718]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
run fvm list.it took so lonnnnnnnnnng time.

**To Reproduce**

1. Go to terminal..
2. Run `

https://github.com/leoafarias/fvm/assets/9456800/7a6b0e56-4f08-4ed6-ac56-4c29c21a0bdf

fvm list`

**Logs**
Please provide the verbose logs by running `--verbose` after the command.

**Desktop (please complete the following information):**

macos 14.4.1
fvm 3.1.4

**Comment by leoafarias** [comment]
@YueLiXing can you run it with the `--verbose` flag?

**Comment by leoafarias** [comment]
@YueLiXing I suspect that it is slow when fetching the flutter releases. Can you also run `fvm releases` and see if its slow.

**Comment by yjt1216** [comment]
[WARN] FVM_HOME environment variable is deprecated. 
Please use FVM_CACHE_PATH instead
No SDKs have been installed yet. Flutter. SDKs
installed outside of fvm will not be displayed.

**Comment by yjt1216** [comment]
你解决了吗？我这暂时用本来flutter list代替了fvm
