### ISSUE TITLE
The provided value cache.git is not the root of a git directory

### ISSUE THREAD

**Issue by joshua1996** [leoafarias/fvm#729]
![image](https://github.com/leoafarias/fvm/assets/7079972/44604e48-552e-4eb9-b5b4-7b9102b325b9)

**Comment by leoafarias** [comment]
@joshua1996, can you go into that directory and remove the cache.git file, and try again? Not sure why this was not completed, but I will review.

**Comment by joshua1996** [comment]
@leoafarias 
KEYWORD #731 
I have removed the cache.git file as you suggested, but unfortunately, the issue persists.

**Comment by leoafarias** [comment]
@joshua1996 I have released version 3.1.5, which should handle errors better. Is that the version you tested with?

**Comment by Soliardi-Chyngyz** [comment]
Same problem, how to install specific fvm version to install?

**Comment by leoafarias** [comment]
Try running `fvm config --no-use-git-cache` see if that resolves the issue.

**Comment by Soliardi-Chyngyz** [comment]
https://github.com/leoafarias/fvm/issues/731
