### ISSUE TITLE
Flutter command alias

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/fvm#73]
Create a helper alias command to link project flutter bin to the `flutter` command
```
fvm alias
```
This will alias the local project bin to `flutter` for that terminal session.

**Comment by hunght** [comment]
use can use 'fvm flutter' if you want to run loal flutter sdk on your project

**Comment by hunght** [comment]
@leoafarias  btw when i use fvm flutter i can't run hot reload by typing 'r' or 'R'
![Screen Shot 2020-07-02 at 10 56 14 AM](https://user-images.githubusercontent.com/1697756/86314749-a7fdf500-bc52-11ea-9ba4-5e13f8e6b308.png)
could you help with that?

**Comment by kuhnroyal** [comment]
Having the same problem, didn't think of fvm as the reason but could very well be. Probably stdin not being piped through.

**Comment by leoafarias** [comment]
@kuhnroyal @hunght That was it. pushing a new update. This issue is not related to this though, next time please create a new one.

**Comment by leoafarias** [comment]
@hunght fix pushed to version 1.0.3

**Comment by jascodes** [comment]
@leoafarias 
How about aliasing dart version inside cache of flutter as well?

**Comment by jascodes** [comment]
@leoafarias Any work done on this? Just curious.

**Comment by leoafarias** [comment]
Not yet

**Comment by jascodes** [comment]
I might send a PR if you agree with the way I intend to do it. 

- I will add new executable `flutter` and proxy based on `.fvm/fvm_config.json`. 
- If not found `.fvm/fvm_config.json` proxy to global version. 
- If global not found try to proxy flutter find in path.
- If not found in path as well throw error to install a version of flutter.

**Comment by leoafarias** [comment]
@jascodes I would just proxy to the one found on config. 
I am trying to minimize the coverage around all the conditional logic to use the version.
The flutter in path should already be the 'flutter' version of the command and the same applies to the global one.

**Comment by jascodes** [comment]
Okay np, I will try to find sometime and send you PR for this.

**Comment by jascodes** [comment]
So should I add flutter bin in pubsec or `flutter alias` should enable or disable the binary??

**Comment by leoafarias** [comment]
Should just enable... keep in mind that the goal is just to attach to the terminal session equivalent of an export

**Comment by jascodes** [comment]
@leoafarias I was planing to write flutter proxy in dart; so it would also work on windows. Do you want the proxy written in bash and bat?

**Comment by jascodes** [comment]
@leoafarias Hey I was also looking what do you think about PR I sent. Plus whats plan with gui-support branch? Are we also refactoring how channels will be tracked?

**Comment by leoafarias** [comment]
@jascodes we can discuss the PR, within the PR thread. Also the GUI support branch there. Right now the GUI support branch is more just of a clean up and code reorg.

**Comment by jascodes** [comment]
@leoafarias You missed my previous question..
> @leoafarias I was planing to write flutter proxy in dart; so it would also work on windows. Do you want the proxy written in bash and batch?

**Comment by leoafarias** [comment]
@jascodes seems like there is no easy way to do this on windows. I was looking as just an export for the terminal session.

I think this might more complicated than initially expected in order to support windows

**Comment by jascodes** [comment]
Look man, I just want to add dart binary 'flutter' via which I wanted to proxy. This should work on all platforms. If you insist on fvm alias to toggle, maybe we can rename the binary to fvm-flutter and when fvm alias is run rename it to just flutter. Something like that.

**Comment by leoafarias** [comment]
@jascodes sorry but I don't understand. We currently allow to proxy the flutter bin.. through the 'fvm flutter...' and also we allow to set a version as global to link to the path.

The initial goal for the 'fvm alias' is just to allow the user to continue to use 'flutter' command within the terminal section.

Maybe I am missing something. Can you break down the use case for what you are thinking?

**Comment by jascodes** [comment]
My earlier plan was simply doing this.
```
executables:
  fvm: main
  flutter: flutter
```
And move/copy fvm flutter logic to separate `flutter` binary which is not in path.

if you want to link and delink `flutter`, I was saying we can simulate via doing this.

```
executables:
  fvm: main
  fvm-flutter: flutter
```

Now when `fvm alias` is enabled rename `fvm-flutter` to `flutter` and on disable toggle it back.

You see what I was sayin.. ??

**Comment by leoafarias** [comment]
Ok sounds good. The struggle with the project is to try to no touch flutter expected behavior and dev expectations.

Sure send a PR and I will review.
