### ISSUE TITLE
[BUG] installation failed but choco report it as success

### ISSUE THREAD

**Issue by vallerydelexy** [leoafarias/fvm#737]
**Before creating a bug report please make check the following**

- [x ] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x ] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [x ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x ] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
PS C:\Users\Rizki Aprita> choco install fvm
Chocolatey v2.2.2
Installing the following packages:
fvm
By installing, you accept licenses for the packages.
Progress: Downloading dart-sdk 3.4.1... 100%

dart-sdk v3.4.1 [Approved]
dart-sdk package files install completed. Performing other installation steps.
PATH environment variable does not have C:\tools\dart-sdk\bin in it. Adding...
PATH environment variable does not have C:\Users\Rizki Aprita\AppData\Local\Pub\Cache\bin in it. Adding...
Downloading dart-sdk 64 bit
  from 'https://storage.googleapis.com/dart-archive/channels/stable/release/3.4.1/sdk/dartsdk-windows-x64-release.zip'
Progress: 100% - Completed download of C:\Users\Rizki Aprita\AppData\Local\Temp\dart-sdk\3.4.1\dartsdk-windows-x64-release.zip (220.52 MB).
Download of dartsdk-windows-x64-release.zip (220.52 MB) completed.
Hashes match.
Extracting C:\Users\Rizki Aprita\AppData\Local\Temp\dart-sdk\3.4.1\dartsdk-windows-x64-release.zip to C:\tools...
C:\tools
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of dart-sdk was successful.
  Software installed to 'C:\tools'
Progress: Downloading fvm 3.1.7... 100%

fvm v3.1.7 [Approved]
fvm package files install completed. Performing other installation steps.
Fetching Dart dependencies...
The current Dart SDK version is 2.19.6.
System.Management.Automation.RemoteException
Because dart_mappable 4.2.2 requires SDK version >=3.0.0 <4.0.0 and no versions of dart_mappable match >4.2.2 <5.0.0, dart_mappable ^4.2.2 is forbidden.
So, because fvm depends on dart_mappable ^4.2.2, version solving failed.
Building executable...
Info: Compiling with sound null safety.
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/utils/context.dart'.
Error: Couldn't resolve the package 'scope' in 'package:scope/scope.dart'.
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:5:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:6:8: Error: Not found: 'package:fvm/src/utils/context.dart'
import 'package:fvm/src/utils/context.dart';
       ^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:7:8: Error: Not found: 'package:scope/scope.dart'
import 'package:scope/scope.dart';
       ^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:10:17: Error: Method not found: 'Scope'.
  final scope = Scope()..value(contextKey, FVMContext.create(args: args));
                ^^^^^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:10:44: Error: Undefined name 'FVMContext'.
  final scope = Scope()..value(contextKey, FVMContext.create(args: args));
                                           ^^^^^^^^^^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:10:32: Error: Undefined name 'contextKey'.
  final scope = Scope()..value(contextKey, FVMContext.create(args: args));
                               ^^^^^^^^^^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:13:27: Error: Method not found: 'FvmCommandRunner'.
    await scope.run(() => FvmCommandRunner().run((args))),
                          ^^^^^^^^^^^^^^^^
Error: AOT compilation failed
Generating AOT kernel dill failed!
Added C:\ProgramData\chocolatey\bin\fvm.exe shim pointed to '..\lib\fvm\bin\fvm.exe'.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
 The install of fvm was successful.
  Software install location not explicitly set, it could be in package or
  default install location of installer.

Chocolatey installed 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Users\Rizki Aprita> choco install fvm
Chocolatey v2.2.2
Installing the following packages:
fvm
By installing, you accept licenses for the packages.
fvm v3.1.7 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - fvm - fvm v3.1.7 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

**To Reproduce**

1. open windows terminal as admin
2. type choco install fvm
3. enter
4. error

- OS: windows
- FVM Version 3.1.7
- If Windows: 5.1.22621.2706

**Comment by kuyazee** [comment]
Up, this is happening on Windows Powershell ran as admin as well

Already did the same checklist to check if it's working or not

Chocolatey v1.1.0

```
PS C:\WINDOWS\system32> choco install fvm
Chocolatey v1.1.0
Installing the following packages:
fvm
By installing, you accept licenses for the packages.
fvm v3.2.1 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - fvm - fvm v3.2.1 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
PS C:\WINDOWS\system32> choco install fvm --force
Chocolatey v1.1.0
Installing the following packages:
fvm
By installing, you accept licenses for the packages.
fvm v3.2.1 already installed. Forcing reinstall of version '3.2.1'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading fvm 3.2.1... 100%

fvm v3.2.1 (forced) [Approved] - Possibly broken
fvm package files install completed. Performing other installation steps.
The package fvm wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Fetching Dart dependencies...
The current Dart SDK version is 2.17.0.
System.Management.Automation.RemoteException
Because fvm depends on dart_mappable >=4.0.0-dev.0 which requires SDK version >=3.0.0 <4.0.0, version solving failed.
Building executable...
Info: Compiling with sound null safety
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/runner.dart'.
Error: Couldn't resolve the package 'fvm' in 'package:fvm/src/utils/context.dart'.
Error: Couldn't resolve the package 'scope' in 'package:scope/scope.dart'.
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:5:8: Error: Not found: 'package:fvm/src/runner.dart'
import 'package:fvm/src/runner.dart';
       ^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:6:8: Error: Not found: 'package:fvm/src/utils/context.dart'
import 'package:fvm/src/utils/context.dart';
       ^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:7:8: Error: Not found: 'package:scope/scope.dart'
import 'package:scope/scope.dart';
       ^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:10:17: Error: Method not found: 'Scope'.
  final scope = Scope()..value(contextKey, FVMContext.create(args: args));
                ^^^^^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:10:44: Error: Undefined name 'FVMContext'.
  final scope = Scope()..value(contextKey, FVMContext.create(args: args));
                                           ^^^^^^^^^^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:10:32: Error: Undefined name 'contextKey'.
  final scope = Scope()..value(contextKey, FVMContext.create(args: args));
                               ^^^^^^^^^^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:13:33: Error: Method not found: 'FvmCommandRunner'.
    await scope.run(() async => FvmCommandRunner().run((ctx.args))),
                                ^^^^^^^^^^^^^^^^
/c:/programdata/chocolatey/lib/fvm/tools/source/bin/main.dart:13:57: Error: Undefined name 'ctx'.
    await scope.run(() async => FvmCommandRunner().run((ctx.args))),
                                                        ^^^
Error: AOT compilation failed
Generating AOT kernel dill failed!
Added C:\ProgramData\chocolatey\bin\fvm.exe shim pointed to '..\lib\fvm\bin\fvm.exe'.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
 The install of fvm was successful.
  Software install location not explicitly set, it could be in package or
  default install location of installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

To Reproduce
Steps to reproduce the behavior:

- open windows terminal as admin
- type choco install fvm
- enter
- error

OS: Windows 11 Pro
FVM Version 3.2.1
If Windows: 10.0.22631

**Comment by leoafarias** [comment]
Consolidated chocolatey tickets with #781
