### ISSUE TITLE
Fvm folder size too big

### ISSUE THREAD

**Issue by lim-freddy** [leoafarias/fvm#741]
My fvm folder is too big. When i checked the content, the biggest folder is cache and .git (hidden folder on my mac).
Is it ok to clear both folder?

Is there any command i can use to clear both folder only?
And which fvm version supported that command?

**Comment by leoafarias** [comment]
@lim-freddy you can use `fvm destroy`; however, the cache should just have a copy of the Flutter git. The versions directory should be where the size is, which contains the different versions of Flutter.

**Comment by lim-freddy** [comment]
I read `fvm destroy` will clear all my flutter version too, is it true? 
after use that command, must I install all my previous flutter version again?

**Comment by leoafarias** [comment]
Yes, that is true, correct, or you can use `fvm remove <version>` to remove individual versions.
