### ISSUE TITLE
[BUG] Trying to use the symlink in the vscode settings.json 

### ISSUE THREAD

**Issue by Katekko** [leoafarias/fvm#752]
I wanna use the default path in vscode, idk if it is a bug or I'm doing something wrong. This is my settings.json for my entire vscode
```JSON
{
    "workbench.iconTheme": "material-icon-theme",
    "dart.showTodos": false,
    "dart.sdkPath": "/home/katekko/fvm/versions/default/bin/",
    "dart.flutterSdkPath": "/home/katekko/fvm/versions/default",
}
```
![image](https://github.com/user-attachments/assets/c97274aa-c86b-49f7-b28d-408520ea0cc5)

But if I change for the specifc version, it will work.

`"dart.flutterSdkPath": "/home/katekko/fvm/versions/3.22.2",`

Is there something that am I missing, or is just impossible use the symlink like this?

Btw, I'm using the symlink in my bash and it's work like a charm.

- OS: llinux ubuntu 24.04 LTS
- FVM Version: 3.1.7

**Additional context**
Project:
┌─────────────────────────────┬───────────────────────────────────┐
│ Project                     │ poke_arena                        │
├─────────────────────────────┼───────────────────────────────────┤
│ Directory                   │ /home/katekko/Projects/poke_arena │
├─────────────────────────────┼───────────────────────────────────┤
│ Active Flavor               │ None                              │
├─────────────────────────────┼───────────────────────────────────┤
│ Is Flutter Project          │ No                                │
├─────────────────────────────┼───────────────────────────────────┤
│ Dart Tool Generator Version │ Not available                     │
├─────────────────────────────┼───────────────────────────────────┤
│ Dart tool version           │ Not available                     │
├─────────────────────────────┼───────────────────────────────────┤
│ .gitignore Present          │ No                                │
├─────────────────────────────┼───────────────────────────────────┤
│ Config Present              │ No                                │
├─────────────────────────────┼───────────────────────────────────┤
│ Pinned Version              │ None                              │
├─────────────────────────────┼───────────────────────────────────┤
│ Config path                 │ .fvmrc                            │
├─────────────────────────────┼───────────────────────────────────┤
│ Local cache dir             │ .fvm/versions                     │
├─────────────────────────────┼───────────────────────────────────┤
│ Version symlink             │ .fvm/versions                     │
└─────────────────────────────┴───────────────────────────────────┘

IDEs:
┌────────────────────────────────┬─────────────────────────────────────────────────────┐
│ IDEs                           │ Value                                               │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ VSCode                         │                                                     │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ VSCode                         │ No .vscode directory found                          │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │                                                     │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │ No local.properties file found in android directory │
├────────────────────────────────┼─────────────────────────────────────────────────────┤
│ IntelliJ (Android Studio, ...) │ No .idea folder found                               │
└────────────────────────────────┴─────────────────────────────────────────────────────┘

Environment:
┌────────────────────────┬───────────────────────────────────────┐
│ Environment Variables  │ Value                                 │
├────────────────────────┼───────────────────────────────────────┤
│ Flutter PATH           │ /home/katekko/fvm/default/bin/flutter │
├────────────────────────┼───────────────────────────────────────┤
│ Dart PATH              │ /home/katekko/fvm/default/bin/dart    │
├────────────────────────┼───────────────────────────────────────┤
│ FVM_CACHE_PATH         │ N/A                                   │
├────────────────────────┼───────────────────────────────────────┤
│ FVM_USE_GIT_CACHE      │ N/A                                   │
├────────────────────────┼───────────────────────────────────────┤
│ FVM_GIT_CACHE_PATH     │ N/A                                   │
├────────────────────────┼───────────────────────────────────────┤
│ FVM_FLUTTER_URL        │ N/A                                   │
├────────────────────────┼───────────────────────────────────────┤
│ FVM_PRIVILEDGED_ACCESS │ N/A                                   │
├────────────────────────┼───────────────────────────────────────┤
│ Flutter PATH           │ /home/katekko/fvm/default/bin/flutter │
├────────────────────────┼───────────────────────────────────────┤
│ Dart PATH              │ /home/katekko/fvm/default/bin/dart    │
└────────────────────────┴───────────────────────────────────────┘
┌──────────────┬──────────────────────────────────────────────────────────────────────────────────────────┐
│ Platform     │ Value                                                                                    │
├──────────────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│ OS           │ linux Linux 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 │
├──────────────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│ Dart Locale  │ en_US.UTF-8                                                                              │
├──────────────┼──────────────────────────────────────────────────────────────────────────────────────────┤
│ Dart runtime │ 3.4.1 (stable) (Tue May 21 15:46:25 2024 +0000) on "linux_x64"                           │
└──────────────┴──────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by leoafarias** [comment]
@Katekko, sorry for the delay on this. I am configuring just the Flutter SDK, as the Dart version will be used automatically. Also, FVM 3+ automatically configures VSCode. Please let me know if that is not the case for you. I am cleaning up the issues, so I will close it, but feel free to reopen if you have a different experience.
