### ISSUE TITLE
Problem while working with Flutter 1.17.0

### ISSUE THREAD

**Issue by pushpendraKh** [leoafarias/fvm#77]
@leoafarias I have installed "Flutter 1.17.0" using `fvm` (v0.8.3)

I can run my android successfully. But when I try to run it on iOS, it says "Upgrading project.pbxproj" which removes `App.framework` and `Flutter.framwork` from Runner/Flutter which causes following error and app gets stuck at launch screen itself
```
[VERBOSE-2:engine.cc(112)] Engine run configuration was invalid.
```

I tried to degrade the version from 1.17.4 to 1.12.13+hotfix.5 which runs smoothly on both platforms. 

Is there anything related to `fvm` which I am doing wrong or have not set up correctly. 

Plus, when I execute `fvm config`, it says "No configuration has been set".

**Comment by leoafarias** [comment]
@pushpendraKh This is related to the version bump and incompatibility most likely. FVM just pulls flutter, and proxys the commands. It does not touch  flutter or modify any of its behavior.

This was the reason why I felt the need for `fvm` to make sure we had consistent builds between our build and our CIs.

If you switch from version 1.12.13+hotfix.5 and use the `flutter channel stable` outside of fvm you will get the same error. 

Regarding the `config` that message is correct and you have not configured anything. This allows you to change the cache-path in case you want to modify where the versions are stored.

**Comment by pushpendraKh** [comment]
I see. So this is not related to fvm. Thanks for the clarification. 

Any suggestions to resolve this, would be appreciated :)

**Comment by leoafarias** [comment]
I believe this is related to the issue you are facing. Follow these instructions 

https://flutter.dev/docs/development/ios-project-migration
