### ISSUE TITLE
`fvm list` says "Needs setup" but doesn't provide instructions

### ISSUE THREAD

**Issue by matthew-carroll** [leoafarias/fvm#772]
Running `fvm list` can show Flutter installations as "Needs setup" but doesn't provide any instructions for how to resolve that. What does it mean to "setup" the Flutter distro?

<img width="951" alt="Screenshot 2024-08-29 at 11 28 46 PM" src="https://github.com/user-attachments/assets/99e47b65-f0f8-4ec5-a1c7-f0c88edb5cdb">

I found experimentally that running something like `fvm flutter pub get` will resolve this. I assume that "Needs setup" in this case means "needs to download Flutter engine". But I can't say for sure.

**Comment by AtomLee4279** [comment]
you can install flutter sdk with "fvm install 2.5.0 --setup",etc.
(https://fvm.app/documentation/guides/basic-commands#options-1)

![Image](https://github.com/user-attachments/assets/24258447-7bbd-4f1c-9db2-b25498151ab1)

**Comment by AdrianoCahete** [comment]
Why setup is not the default? Most of the people install and does not want to setup it?

**Comment by reloveution** [comment]
Same issue with 3.38.3.

<img width="620" height="131" alt="Image" src="https://github.com/user-attachments/assets/9cae155d-5196-4f94-96d4-fd4dc10129af" />

**Comment by jsuo** [comment]
3.38.4 Need setup

<img width="695" height="121" alt="Image" src="https://github.com/user-attachments/assets/61a8237a-b4d2-4f72-82e8-614d51adbcef" />

**Comment by jackielenkhen** [comment]
> Check fvm install location may help you solve this problem! In my case two different fvm install location occur crash

thanks. it work for me. i stalled on homebrew and one more i install as dart pubic.. so when i remove one it work..

**Comment by TeerapatKC** [comment]
> Check fvm install location may help you solve this problem! In my case two different fvm install location occur crash

thanks.

C:\Windows\System32> where fvm
C:\ProgramData\chocolatey\bin\fvm.exe 
C:\Users\XXX\AppData\Local\Pub\Cache\bin\fvm.bat

removed the chocolatey one with:
C:\Windows\System32> choco uninstall fvm -y

then everything works fine again 👌
