### ISSUE TITLE
[BUG] Failed to create symlink.

### ISSUE THREAD

**Issue by khoirul-mustofa** [leoafarias/fvm#796]
# Issue: Permission Denied on Symlink Creation During FVM Installation

**Description:**
While attempting to install FVM on my Linux system using the provided installation script, I encountered a permission error when the script tried to create a symbolic link in `/usr/local/bin`. The error occurred despite using `sudo` with the `curl` command. It seems that the symbolic link creation step inside the bash script requires superuser permissions, but the script itself isn't being executed with the necessary privileges.

System Information:

OS: Pop!_OS (based on Ubuntu)
Architecture: x64
FVM Version: 3.2.1 (detected by the installer)

**Steps to Reproduce:**
1. Run the following command on a Linux system (Pop!_OS in this case):
   ```bash
   sudo curl -fsSL https://fvm.app/install.sh | bash


Workaround: Running the following command resolves the issue:
```bash
curl -fsSL https://fvm.app/install.sh | sudo bash

**Comment by khoirul-mustofa** [comment]
Issue: Permission Denied on Symlink Creation During FVM Installation

**Comment by zakblacki** [comment]
Same issue

**Comment by sgehrman** [comment]
didn't work
