### ISSUE TITLE
Won't switch version

### ISSUE THREAD

**Issue by jascodes** [leoafarias/fvm#8]
So I had flutter installed in folder and its bin folder in path. Installed fvm via go get. Now when switch via fvm, its still directed to old my flutter. If I try to remove mine from path and try install it complains to need flutter in path. I am on ubuntu 19.04.

Thx

**Comment by leoafarias** [comment]
@jascides can you give the exact message you are receiving?

**Comment by jascodes** [comment]
Thats the thing, I get not message of failute after switch.
If I remove my flutter folder from path, I get the following.
`Please set your flutter path before using the tool`

To be honest, I expect the tool to download fresh copy of flutter and build and cache. Current setup is very confusing.

Thx

**Comment by leoafarias** [comment]
@jascodes the tool does that. I believe the way I am doing the symlink is not compatible with Ubuntu. I have an issue open to rework how flutter bin is cached, and that would make it more compatible with flutter channel. I believe I can add this as part of solving this issue also #4

**Comment by jascodes** [comment]
I think warning in instruction not to use `flutter upgrade` should be enough. I would you fix `Please set your flutter path before using the tool` by allowing pulling the fresh copy and saving the builds in seprate folder. Right now I don't understand why you need flutter in path already?

**Comment by leoafarias** [comment]
@jascodes I believe I found the issues, it seems to have to do with the symlink, how it works on ubuntu. I am writing some tests, and will probably have to change the way I am doing this

**Comment by jascodes** [comment]
I had non-empty flutter folder in my home dir. FVM seems to need it. After removing that folder and adding `~/flutter/bin` to path I am not even getting `Please set your flutter path before using the tool`, so it might be due to might my environment and weird fact that I had flutter folder in my home. I think thats why switch might not be happening.

**Comment by leoafarias** [comment]
@jascodes the tool was designed not to need any type of setup of the path. If no path is set or adds to use/local/bin which I think this what the issue might be with Linux. 

It should respect a path that is set and if not it sets a default

**Comment by leoafarias** [comment]
The new version of fvm works in a different way. I believe this also solves this issue. I have updated the readme to reflect that starting with version 0.0.5
