### ISSUE TITLE
Discussion: Dart version management

### ISSUE THREAD

**Issue by jascodes** [leoafarias/fvm#80]
One of cool things about fvm is the ability to lock flutter version. But for me locking dart version in project might as useful. I know it might be allot of work. But @leoafarias what do you think. Does this idea make sense?

Jas

**Comment by leoafarias** [comment]
@jascodes I don't think it is a good idea to have flutter with a different dart dependency from what its shipped within the release.

Are you talking about for projects that do not depend on Flutter?

while building FVM I faced that problem because FVM its not dependent on flutter but it is on Dart.

**Comment by jascodes** [comment]
Oh great I didn't realise that each flutter version had its own local dart version. I was under wrong impression that the system version (installed on machine) of dart is used for compilation in flutter projects; no matter version.

Am I right?

**Comment by leoafarias** [comment]
"Downloading the Flutter SDK also downloads the compatible version of Dart, but if you’ve downloaded the Dart SDK separately, make sure that the Flutter version of dart is first in your path, as the two versions might not be compatible. "
https://flutter.dev/docs/get-started/install/windows#update-your-path

That is why Flutter suggests proxying dart commands like `flutter pub get` that uses the dart sdk within the Flutter release

**Comment by jascodes** [comment]
@leoafarias Awesome, Thx for taking time and explaining. Very helpful and much appreciated. I am going to close this.
