### ISSUE TITLE
Dart / Flutter sdk locations in IntelliJ Idea, is there a way to set them for a specific project?

### ISSUE THREAD

**Issue by atreeon** [leoafarias/fvm#83]
Is there a way to set the Dart / Flutter sdk locations in IntelliJ Idea for a specific project? I'm particularly interested in setting this for Flutter / Dart as I have different installed versions for different projects (I'm using fvm).

I know how to set them in the system preferences -> language & framesworks but this sets them for all projects and I'd like to have a specific fvm install for a specific flutter project.

**Comment by kuhnroyal** [comment]
I am manually adjusting the paths in `.idea\libraries\Dart_SDK.xml` to something like

```xml
<root url="file://$PROJECT_DIR$/.fvm/flutter_sdk/bin/cache/dart-sdk/lib/async" />
```

**Comment by atreeon** [comment]
ah thanks @kuhnroyal, is there a way to set the Flutter sdk too?

**Comment by kuhnroyal** [comment]
@atreeon Right, I am not sure where IntelliJ looks for the Flutter path but once I run `fvm flutter pub get` it is always configured correctly.

**Comment by atreeon** [comment]
ah ok, for me it is set in

Preferences -> Languages & Frameworks -> Flutter -> SDK path

but that is set for all projects and not specific to my current project.  When I installed fvm I set this sdk location to my fvm flutter location but that set it for all projects.  It's ok, it is much easier with fvm to switch, it would just be really nice to have each project set to specific flutter versions.  There is a way to do it in VS Code I think using the Flutter plugin but it seems not possible or I don't know how to in Intellij.

**Comment by kuhnroyal** [comment]
Yea, it is configured there for me as well. But different for every project and I have never manually set it.

**Comment by leoafarias** [comment]
@kuhnroyal Please let me know if there is any further documentation we should provide in regards to the setup on IntelliJ

**Comment by kuhnroyal** [comment]
@leoafarias Not from my side but I am not the one having problems :)

**Comment by leoafarias** [comment]
@kuhnroyal understand, wanted to make sure there was not something missing on the docs from your point of view, thanks for helping @atreeon

**Comment by atreeon** [comment]
Hi @leoafarias, I think sometimes IntelliJ gets confused and doesn't use the fvm version.  I could be useful to write something like 'check the dart sdk and flutter sdk paths have been updated by going to Preferences -> Languages & Frameworks -> Dart -> Dart SDK path'

Thank you
