### ISSUE TITLE
[Feature Request] Change global fvm directory location

### ISSUE THREAD

**Issue by svenjacobs** [leoafarias/fvm#84]
I would like to change the global fvm directory location from `/Users/sven/fvm` to `/Users/sven/.fvm`. However this does not seem to be possible at the moment, right? Maybe fvm can honor an environment variable like `FVM_HOME` if set?

**Comment by svenjacobs** [comment]
See pull request #85. I hope you like it 😃

**Comment by leoafarias** [comment]
@all-contributors please add @svenjacobs for code
