### ISSUE TITLE
Upgrade Flutter from FVM

### ISSUE THREAD

**Issue by e200** [leoafarias/fvm#91]
There is now way to upgrade the Flutter being used.

```fvm upgrade stable```

**Comment by leoafarias** [comment]
Assuming you have set to use the stable channel. You should be able to use 'fvm flutter upgrade'

**Comment by LeoK987** [comment]
When I set a version for use global, if there any difference between the following 2 commands?

$ flutter upgrade
$ fvm flutter upgrade

**Comment by leoafarias** [comment]
That will work fine. Just make sure the path is configured pointing to the global default

**Comment by leoafarias** [comment]
@e200 let me know if that clarified for you, and I will go ahead and close this issue.

**Comment by e200** [comment]
Its clear for me now, thank you 😊

I just want to suggest to change the command args order.

`fvm upgrade flutter` seems more logical for me than `fvm flutter upgrade`.

**Comment by leoafarias** [comment]
You are correct. This is more of an effort to not override or extend flutter cli commands.

I am working on some improvements to channels to allow pinning the version, and will look into that also.

Thanks
