### ISSUE TITLE
[BUG]channel unknown • unknown source

### ISSUE THREAD

**Issue by LeoK987** [leoafarias/fvm#94]
**Describe the bug**

$ flutter --version
Flutter 1.20.0-7.2.pre • channel unknown • unknown source
Framework • revision a2bde82fbd (4 days ago) • 2020-07-18 15:16:35 -0700
Engine • revision 60b269d898
Tools • Dart 2.9.0 (build 2.9.0-21.2.beta)

I am not sure if this may cause any issue using flutter.

*To Reproduce**
1. fvm install 1.20.0-7.2.pre
2. fvm use 1.20.0-7.2.pre --global
3. export PATH="/home/xxx/fvm/default/bin":"$PATH"
4. flutter --version

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - FVM Version [e.g. 22]

**Additional context**

**Comment by leoafarias** [comment]
This is due to how flutter grabs a non-channel version flutter/flutter#48147, not sure if this will be fixed but does not impact development as it is a supported flutter feature.

**Comment by leoafarias** [comment]
@LeoK987 will be closing this but let me know if you have any other questions that I can help you with.
