### ISSUE TITLE
[Feature Request] install .pub-cache out of flutter directory

### ISSUE THREAD

**Issue by LeoK987** [leoafarias/fvm#96]
**Is your feature request related to a problem? Please describe.**
Since fvm is to manage various versions of flutter, it makes sense to install the package independent from a flutter install.  Then the existing flutter install can be added automatically as a flutter version available under fvm.

After installing fvm, I moved .pub-cache into ~/fvm and set PATH accordingly.  Then I manually moved my flutter install of dev channel into versions and renamed it accordingly.  That saves disk space and bandwidth.  So far I don't see problems.

Comments?

**Comment by leoafarias** [comment]
@LeoK987 does .pub-cache changes based on the flutter version that is used for pub?

**Comment by LeoK987** [comment]
@leoafarias I am not sure if I understand your question.

.pub-cache was created when I did "flutter pub global activate fvm", where flutter was the version I had at that time.  So it was created under flutter/bin/.

So now I moved .pub-cache out of flutter/bin and into ~/fvm, and moved the entire flutter directory into fvm/versions and renamed it as 1.21.0-1.0.pre.

I don't see problems now.  But will this create problems, I need to ask you guys.

**Comment by leoafarias** [comment]
@LeoK987 Did you see any issue by not moving the pub-cache before?

**Comment by LeoK987** [comment]
Not moving pub-cache?  I didn't notice problems.  But I didn't use it like that for long.

One issue I see is the env variable FLUTTER_HOME still pointing to the original flutter folder, which becomes obsolete with the use of fvm.  But I didn't see any problem due to it and am not sure where the variable is used.

**Comment by leoafarias** [comment]
Fvm does not set any env vars.

**Comment by LeoK987** [comment]
not set by fvm.  FLUTTER_HOME was set when regular flutter was installed.

**Comment by leoafarias** [comment]
@LeoK987 I believe going forward the default way to install fvm should be the `pub global activate fvm`. That would solve the issue of the pub-cache and fvm.
