### ISSUE TITLE
Unable to install the specified version[BUG]

### ISSUE THREAD

**Issue by Dukro** [leoafarias/fvm#98]
Last login: Mon Jul 27 13:33:57 on ttys002

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm help
Flutter Version Management: A cli to manage Flutter SDK versions.

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Config fvm options
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm releases
⚠️  Could not fetch Flutter releases.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm install 1.17.5
⚠️  Could not fetch Flutter releases.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ vim ~/.bash_profile
StyLookDukrodeMacBook-Pro:~ stylookdukro$ source ~/.bash_profile
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm flutter run
⚠️  No such file or directory
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm list
No SDKs have been installed yet. Flutter SDKs installed outside of fvm will not be displayed.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm list
No SDKs have been installed yet. Flutter SDKs installed outside of fvm will not be displayed.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm install
⚠️  Need to provide a channel or a version.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm install 1.17.5-stable
⚠️  Could not fetch Flutter releases.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm install 1.17.5-stable
⚠️  Could not fetch Flutter releases.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm --version
⚠️  Could not find an option named "version".
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm -version
⚠️  Could not find an option with short name "-v".
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm -
⚠️  Could not find a command named "-".
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm -v
⚠️  Could not find an option or flag "-v".
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm
Flutter Version Management: A cli to manage Flutter SDK versions.

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Config fvm options
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.
StyLookDukrodeMacBook-Pro:~ stylookdukro$

**Comment by leoafarias** [comment]
@Dukro could you type `fvm version` so I can see the version you are using?

**Comment by Dukro** [comment]
> 您可以键入@Dukro，`fvm version`以便我可以看到您使用的版本吗？

Last login: Mon Jul 27 17:41:04 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm
Flutter Version Management: A cli to manage Flutter SDK versions.

Usage: fvm <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Print verbose output.

Available commands:
  config     Config fvm options
  flutter    Proxies Flutter Commands
  install    Installs Flutter SDK Version
  list       Lists installed Flutter SDK Version
  releases   Lists Flutter SDK releases.
  remove     Removes Flutter SDK Version
  use        Which Flutter SDK Version you would like to use
  version    Prints the currently-installed version of FVM

Run "fvm help <command>" for more information about a command.
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm version
1.1.3
StyLookDukrodeMacBook-Pro:~ stylookdukro$

**Comment by leoafarias** [comment]
Thanks @Dukro could you please do one more thing and run the commands with the `--verbose` flag. Example: `fvm releases --verbose`

**Comment by Dukro** [comment]
> 感谢@Dukro，您能再做一件事，并运行带有`--verbose`标志的命令吗？例：`fvm releases --verbose`
> 
StyLookDukrodeMacBook-Pro:~ stylookdukro$ fvm releases --verbose
[ 3m 56.216s] ⚠️  Could not fetch Flutter releases.
#0      getReleases (package:fvm/utils/releases_helper.dart:24:5)
<asynchronous suspension>
#1      ReleasesCommand.run (package:fvm/commands/releases.dart:23:28)
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#4      new Future.sync (dart:async/future.dart:224:31)
#5      CommandRunner.run (package:args/command_runner.dart:112:14)
#6      fvmRunner (package:fvm/fvm.dart:28:23)
#7      main (file:///Users/stylookdukro/.pub-cache/hosted/http%2558%2547%2547mirrors.cnnic.cn%2547dart-pub/fvm-1.1.3/bin/main.dart:4:9)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Unhandled exception:
Could not fetch Flutter releases.
#0      getReleases (package:fvm/utils/releases_helper.dart:24:5)
<asynchronous suspension>
#1      ReleasesCommand.run (package:fvm/commands/releases.dart:23:28)
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#4      new Future.sync (dart:async/future.dart:224:31)
#5      CommandRunner.run (package:args/command_runner.dart:112:14)
#6      fvmRunner (package:fvm/fvm.dart:28:23)
#7      main (file:///Users/stylookdukro/.pub-cache/hosted/http%2558%2547%2547mirrors.cnnic.cn%2547dart-pub/fvm-1.1.3/bin/main.dart:4:9)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by leoafarias** [comment]
@Dukro please update to version 1.1.5, I believe is that the default flutter storage url is being changed. I added an error message and how to take action. https://flutter.dev/community/china, it will now respect FLUTTER_STORAGE_BASE_URL env var.
